/* Daily word & sentence data for the ESLnote homepage. Rotates by day of year.
   Level: intermediate to advanced. */
var WORDS = [
  {w:"accomplish", pos:"verb", ipa:"/əˈkɑːmplɪʃ/", def:"To succeed in doing something.", ex:"She accomplished her goal in six months."},
  {w:"accurate", pos:"adjective", ipa:"/ˈækjərət/", def:"Correct; exact.", ex:"Please give me an accurate address."},
  {w:"adapt", pos:"verb", ipa:"/əˈdæpt/", def:"To change to fit a new situation.", ex:"It took months to adapt to the new job."},
  {w:"adequate", pos:"adjective", ipa:"/ˈædɪkwət/", def:"Enough; satisfactory.", ex:"His English is adequate for the job."},
  {w:"adjust", pos:"verb", ipa:"/əˈdʒʌst/", def:"To change slightly.", ex:"I need to adjust my schedule."},
  {w:"admire", pos:"verb", ipa:"/ədˈmaɪər/", def:"To respect and like.", ex:"I admire her dedication."},
  {w:"adopt", pos:"verb", ipa:"/əˈdɑːpt/", def:"To take and use as your own.", ex:"We adopted a new policy."},
  {w:"advance", pos:"verb", ipa:"/ədˈvæns/", def:"To move forward.", ex:"The treatment advanced quickly."},
  {w:"advise", pos:"verb", ipa:"/ədˈvaɪz/", def:"To give advice.", ex:"I advise you to rest."},
  {w:"advocate", pos:"verb", ipa:"/ˈædvəkeɪt/", def:"To support publicly.", ex:"She advocates for better schools."},
  {w:"affect", pos:"verb", ipa:"/əˈfekt/", def:"To influence.", ex:"The delay affected our plans."},
  {w:"agenda", pos:"noun", ipa:"/əˈdʒendə/", def:"A list of things to discuss.", ex:"What's on today's agenda?"},
  {w:"allocate", pos:"verb", ipa:"/ˈæləkeɪt/", def:"To set aside for a purpose.", ex:"We allocated $500 for repairs."},
  {w:"ambitious", pos:"adjective", ipa:"/æmˈbɪʃəs/", def:"Wanting success badly.", ex:"She has ambitious career goals."},
  {w:"amend", pos:"verb", ipa:"/əˈmend/", def:"To change; to improve.", ex:"They amended the contract."},
  {w:"ample", pos:"adjective", ipa:"/ˈæmpəl/", def:"More than enough.", ex:"We have ample time."},
  {w:"analyze", pos:"verb", ipa:"/ˈænəlaɪz/", def:"To study carefully.", ex:"We need to analyze the data."},
  {w:"annual", pos:"adjective", ipa:"/ˈænjuəl/", def:"Happening once a year.", ex:"Our annual checkup is in June."},
  {w:"anticipate", pos:"verb", ipa:"/ænˈtɪsɪpeɪt/", def:"To expect.", ex:"We anticipate a busy weekend."},
  {w:"anxious", pos:"adjective", ipa:"/ˈæŋkʃəs/", def:"Worried; eager.", ex:"She felt anxious before the test."},
  {w:"appeal", pos:"verb", ipa:"/əˈpiːl/", def:"To make a serious request.", ex:"He appealed for help."},
  {w:"appoint", pos:"verb", ipa:"/əˈpɔɪnt/", def:"To choose for a job.", ex:"They appointed a new manager."},
  {w:"appreciate", pos:"verb", ipa:"/əˈpriːʃieɪt/", def:"To be grateful for.", ex:"I appreciate your help."},
  {w:"appropriate", pos:"adjective", ipa:"/əˈproʊpriət/", def:"Suitable.", ex:"Wear appropriate shoes for hiking."},
  {w:"approve", pos:"verb", ipa:"/əˈpruːv/", def:"To agree officially.", ex:"The bank approved our loan."},
  {w:"arise", pos:"verb", ipa:"/əˈraɪz/", def:"To come up; to happen.", ex:"Problems arose during the move."},
  {w:"aspect", pos:"noun", ipa:"/ˈæspekt/", def:"One part of something.", ex:"We discussed every aspect."},
  {w:"aspire", pos:"verb", ipa:"/əˈspaɪər/", def:"To want strongly.", ex:"She aspires to be a nurse."},
  {w:"assemble", pos:"verb", ipa:"/əˈsembəl/", def:"To put together; to gather.", ex:"We assembled the furniture."},
  {w:"assert", pos:"verb", ipa:"/əˈsɜːrt/", def:"To state firmly.", ex:"He asserted his innocence."},
  {w:"assess", pos:"verb", ipa:"/əˈses/", def:"To evaluate.", ex:"The teacher assessed our progress."},
  {w:"asset", pos:"noun", ipa:"/ˈæset/", def:"Something valuable.", ex:"Her experience is a real asset."},
  {w:"assign", pos:"verb", ipa:"/əˈsaɪn/", def:"To give a task.", ex:"The teacher assigned homework."},
  {w:"assist", pos:"verb", ipa:"/əˈsɪst/", def:"To help.", ex:"She assisted the new employee."},
  {w:"assume", pos:"verb", ipa:"/əˈsuːm/", def:"To suppose; to take on.", ex:"Don't assume the worst."},
  {w:"assure", pos:"verb", ipa:"/əˈʃʊr/", def:"To promise; to make certain.", ex:"He assured me it was safe."},
  {w:"attach", pos:"verb", ipa:"/əˈtætʃ/", def:"To join; to include.", ex:"I attached the file to the email."},
  {w:"attain", pos:"verb", ipa:"/əˈteɪn/", def:"To achieve.", ex:"She attained her degree at 40."},
  {w:"attempt", pos:"verb", ipa:"/əˈtempt/", def:"To try.", ex:"He attempted the exam twice."},
  {w:"attend", pos:"verb", ipa:"/əˈtend/", def:"To go to.", ex:"She attends night classes."},
  {w:"attitude", pos:"noun", ipa:"/ˈætɪtuːd/", def:"A way of thinking.", ex:"He has a positive attitude."},
  {w:"attract", pos:"verb", ipa:"/əˈtrækt/", def:"To draw interest.", ex:"The sale attracted crowds."},
  {w:"authentic", pos:"adjective", ipa:"/ɔːˈθentɪk/", def:"Real; genuine.", ex:"This is authentic Italian food."},
  {w:"avert", pos:"verb", ipa:"/əˈvɜːrt/", def:"To prevent.", ex:"Quick action averted a crisis."},
  {w:"avid", pos:"adjective", ipa:"/ˈævɪd/", def:"Very eager.", ex:"He's an avid reader."},
  {w:"await", pos:"verb", ipa:"/əˈweɪt/", def:"To wait for.", ex:"We await your reply."},
  {w:"aware", pos:"adjective", ipa:"/əˈwer/", def:"Knowing.", ex:"Are you aware of the change?"},
  {w:"awkward", pos:"adjective", ipa:"/ˈɔːkwərd/", def:"Uncomfortable; clumsy.", ex:"There was an awkward silence."},
  {w:"ban", pos:"verb", ipa:"/bæn/", def:"To forbid.", ex:"They banned smoking indoors."},
  {w:"bargain", pos:"noun", ipa:"/ˈbɑːrɡən/", def:"A good deal.", ex:"This jacket was a bargain."},
  {w:"barrier", pos:"noun", ipa:"/ˈbæriər/", def:"Something that blocks.", ex:"Language is a barrier for some."},
  {w:"behalf", pos:"noun", ipa:"/bɪˈhæf/", def:"In place of someone.", ex:"She spoke on my behalf."},
  {w:"behave", pos:"verb", ipa:"/bɪˈheɪv/", def:"To act.", ex:"The children behaved well."},
  {w:"belief", pos:"noun", ipa:"/bɪˈliːf/", def:"Something accepted as true.", ex:"His beliefs guide him."},
  {w:"beloved", pos:"adjective", ipa:"/bɪˈlʌvɪd/", def:"Deeply loved.", ex:"She visited her beloved grandmother."},
  {w:"benefit", pos:"noun", ipa:"/ˈbenɪfɪt/", def:"An advantage.", ex:"Exercise has many benefits."},
  {w:"betray", pos:"verb", ipa:"/bɪˈtreɪ/", def:"To be disloyal to.", ex:"He betrayed their trust."},
  {w:"beware", pos:"verb", ipa:"/bɪˈwer/", def:"To be careful.", ex:"Beware of scams."},
  {w:"bias", pos:"noun", ipa:"/ˈbaɪəs/", def:"Unfair preference.", ex:"The test was free of bias."},
  {w:"bizarre", pos:"adjective", ipa:"/bɪˈzɑːr/", def:"Very strange.", ex:"It was a bizarre dream."},
  {w:"blame", pos:"verb", ipa:"/bleɪm/", def:"To say someone is at fault.", ex:"Don't blame yourself."},
  {w:"blend", pos:"verb", ipa:"/blend/", def:"To mix.", ex:"Blend the colors gently."},
  {w:"blunt", pos:"adjective", ipa:"/blʌnt/", def:"Direct; not sharp.", ex:"Let me be blunt: we can't afford it."},
  {w:"boast", pos:"verb", ipa:"/boʊst/", def:"To brag.", ex:"He boasted about his promotion."},
  {w:"bold", pos:"adjective", ipa:"/boʊld/", def:"Brave; striking.", ex:"She made a bold decision."},
  {w:"bond", pos:"noun", ipa:"/bɑːnd/", def:"A close connection.", ex:"They share a strong bond."},
  {w:"bonus", pos:"noun", ipa:"/ˈboʊnəs/", def:"Extra pay or gift.", ex:"We got a holiday bonus."},
  {w:"boost", pos:"verb", ipa:"/buːst/", def:"To increase.", ex:"The win boosted morale."},
  {w:"boundary", pos:"noun", ipa:"/ˈbaʊndri/", def:"A limit.", ex:"Set clear boundaries at work."},
  {w:"breach", pos:"noun", ipa:"/briːtʃ/", def:"A break; a violation.", ex:"It was a breach of trust."},
  {w:"bribe", pos:"noun", ipa:"/braɪb/", def:"Money paid to influence illegally.", ex:"He refused the bribe."},
  {w:"brief", pos:"adjective", ipa:"/briːf/", def:"Short.", ex:"Give me a brief summary."},
  {w:"brisk", pos:"adjective", ipa:"/brɪsk/", def:"Quick; lively.", ex:"We took a brisk walk."},
  {w:"broaden", pos:"verb", ipa:"/ˈbrɔːdən/", def:"To widen.", ex:"Travel broadens the mind."},
  {w:"brochure", pos:"noun", ipa:"/broʊˈʃʊr/", def:"A pamphlet.", ex:"Pick up a brochure at the desk."},
  {w:"bruise", pos:"noun", ipa:"/bruːz/", def:"A dark mark from injury.", ex:"He has a bruise on his arm."},
  {w:"brutal", pos:"adjective", ipa:"/ˈbruːtəl/", def:"Very harsh.", ex:"The winter was brutal."},
  {w:"budget", pos:"noun", ipa:"/ˈbʌdʒɪt/", def:"A spending plan.", ex:"We set a monthly budget."},
  {w:"bulky", pos:"adjective", ipa:"/ˈbʌlki/", def:"Large and heavy.", ex:"The bulky box didn't fit."},
  {w:"burden", pos:"noun", ipa:"/ˈbɜːrdən/", def:"A heavy load.", ex:"Debt is a heavy burden."},
  {w:"bureau", pos:"noun", ipa:"/ˈbjʊroʊ/", def:"An office or agency.", ex:"Contact the travel bureau."},
  {w:"burst", pos:"verb", ipa:"/bɜːrst/", def:"To break open suddenly.", ex:"The pipe burst."},
  {w:"bustling", pos:"adjective", ipa:"/ˈbʌslɪŋ/", def:"Full of activity.", ex:"The market was bustling."},
  {w:"bypass", pos:"verb", ipa:"/ˈbaɪpæs/", def:"To go around.", ex:"We bypassed the traffic jam."},
  {w:"caliber", pos:"noun", ipa:"/ˈkælɪbər/", def:"Quality level.", ex:"We hire people of high caliber."},
  {w:"candid", pos:"adjective", ipa:"/ˈkændɪd/", def:"Honest and direct.", ex:"Let me be candid with you."},
  {w:"capable", pos:"adjective", ipa:"/ˈkeɪpəbəl/", def:"Able to do something.", ex:"She's capable of more."},
  {w:"capacity", pos:"noun", ipa:"/kəˈpæsəti/", def:"Maximum amount; ability.", ex:"The hall was at full capacity."},
  {w:"caption", pos:"noun", ipa:"/ˈkæpʃən/", def:"Text under a picture.", ex:"Read the caption below."},
  {w:"capture", pos:"verb", ipa:"/ˈkæptʃər/", def:"To catch; to record.", ex:"The photo captured the moment."},
  {w:"cargo", pos:"noun", ipa:"/ˈkɑːrɡoʊ/", def:"Goods carried.", ex:"The cargo arrived late."},
  {w:"carve", pos:"verb", ipa:"/kɑːrv/", def:"To cut into shape.", ex:"He carved the turkey."},
  {w:"casual", pos:"adjective", ipa:"/ˈkæʒuəl/", def:"Relaxed; informal.", ex:"The dress code is casual."},
  {w:"caution", pos:"noun", ipa:"/ˈkɔːʃən/", def:"Carefulness.", ex:"Drive with caution."},
  {w:"cease", pos:"verb", ipa:"/siːs/", def:"To stop.", ex:"The rain ceased at noon."},
  {w:"censor", pos:"verb", ipa:"/ˈsensər/", def:"To remove unacceptable parts.", ex:"The scene was censored."},
  {w:"census", pos:"noun", ipa:"/ˈsensəs/", def:"An official population count.", ex:"The census is every ten years."},
  {w:"ceremony", pos:"noun", ipa:"/ˈserəmoʊni/", def:"A formal event.", ex:"The wedding ceremony was lovely."},
  {w:"certify", pos:"verb", ipa:"/ˈsɜːrtɪfaɪ/", def:"To confirm officially.", ex:"She is certified to teach."},
  {w:"chafe", pos:"verb", ipa:"/tʃeɪf/", def:"To irritate by rubbing.", ex:"His shoes chafed his feet."},
  {w:"chaos", pos:"noun", ipa:"/ˈkeɪɑːs/", def:"Total disorder.", ex:"The move was pure chaos."},
  {w:"cherish", pos:"verb", ipa:"/ˈtʃerɪʃ/", def:"To treasure.", ex:"She cherishes those memories."},
  {w:"chronic", pos:"adjective", ipa:"/ˈkrɑːnɪk/", def:"Long-lasting.", ex:"He has chronic back pain."},
  {w:"circulate", pos:"verb", ipa:"/ˈsɜːrkjəleɪt/", def:"To move around; to spread.", ex:"A rumor circulated online."},
  {w:"circumstance", pos:"noun", ipa:"/ˈsɜːrkəmstæns/", def:"A condition or fact.", ex:"Under the circumstances, we left."},
  {w:"cite", pos:"verb", ipa:"/saɪt/", def:"To mention as an example.", ex:"She cited three reasons."},
  {w:"civic", pos:"adjective", ipa:"/ˈsɪvɪk/", def:"Relating to a city or citizens.", ex:"Voting is a civic duty."},
  {w:"clarify", pos:"verb", ipa:"/ˈklærəfaɪ/", def:"To make clear.", ex:"Could you clarify that?"},
  {w:"clash", pos:"verb", ipa:"/klæʃ/", def:"To conflict.", ex:"Our schedules clashed."},
  {w:"classify", pos:"verb", ipa:"/ˈklæsɪfaɪ/", def:"To arrange in groups.", ex:"The files are classified by date."},
  {w:"clause", pos:"noun", ipa:"/klɔːz/", def:"A part of a contract or sentence.", ex:"Read the fine-print clause."},
  {w:"client", pos:"noun", ipa:"/ˈklaɪənt/", def:"A customer.", ex:"She met with a client."},
  {w:"climax", pos:"noun", ipa:"/ˈklaɪmæks/", def:"The most exciting point.", ex:"The movie's climax surprised us."},
  {w:"cling", pos:"verb", ipa:"/klɪŋ/", def:"To hold tightly.", ex:"The child clung to her mother."},
  {w:"clinical", pos:"adjective", ipa:"/ˈklɪnɪkəl/", def:"Medical; cold and plain.", ex:"The room looked clinical."},
  {w:"clip", pos:"verb", ipa:"/klɪp/", def:"To cut; to attach.", ex:"Clip the coupon from the paper."},
  {w:"clique", pos:"noun", ipa:"/kliːk/", def:"An exclusive group.", ex:"She never joined a clique."},
  {w:"coarse", pos:"adjective", ipa:"/kɔːrs/", def:"Rough.", ex:"The coarse fabric scratched."},
  {w:"coax", pos:"verb", ipa:"/koʊks/", def:"To persuade gently.", ex:"She coaxed him to try."},
  {w:"coherent", pos:"adjective", ipa:"/koʊˈhɪrənt/", def:"Clear and logical.", ex:"Write a coherent essay."},
  {w:"coincide", pos:"verb", ipa:"/ˌkoʊɪnˈsaɪd/", def:"To happen at the same time.", ex:"The events coincided."},
  {w:"collaborate", pos:"verb", ipa:"/kəˈlæbəreɪt/", def:"To work together.", ex:"We collaborated on the project."},
  {w:"collapse", pos:"verb", ipa:"/kəˈlæps/", def:"To fall down.", ex:"He collapsed from exhaustion."},
  {w:"colleague", pos:"noun", ipa:"/ˈkɑːliːɡ/", def:"A coworker.", ex:"My colleague helped me."},
  {w:"collide", pos:"verb", ipa:"/kəˈlaɪd/", def:"To crash into.", ex:"The cars collided."},
  {w:"comical", pos:"adjective", ipa:"/ˈkɑːmɪkəl/", def:"Funny.", ex:"It was a comical misunderstanding."},
  {w:"commence", pos:"verb", ipa:"/kəˈmens/", def:"To begin.", ex:"The ceremony will commence at noon."},
  {w:"commend", pos:"verb", ipa:"/kəˈmend/", def:"To praise.", ex:"The boss commended her work."},
  {w:"commodity", pos:"noun", ipa:"/kəˈmɑːdəti/", def:"A product bought and sold.", ex:"Rice is a basic commodity."},
  {w:"commonplace", pos:"adjective", ipa:"/ˈkɑːmənpleɪs/", def:"Ordinary.", ex:"Traffic jams are commonplace here."},
  {w:"communal", pos:"adjective", ipa:"/kəˈmjuːnəl/", def:"Shared by a group.", ex:"We share a communal kitchen."},
  {w:"commute", pos:"verb", ipa:"/kəˈmjuːt/", def:"To travel to work.", ex:"She commutes by train."},
  {w:"compact", pos:"adjective", ipa:"/kəmˈpækt/", def:"Small and dense.", ex:"It's a compact car."},
  {w:"compel", pos:"verb", ipa:"/kəmˈpel/", def:"To force.", ex:"The evidence compelled him to confess."},
  {w:"compensate", pos:"verb", ipa:"/ˈkɑːmpənseɪt/", def:"To pay; to make up for.", ex:"They compensated us for the delay."},
  {w:"compete", pos:"verb", ipa:"/kəmˈpiːt/", def:"To try to win.", ex:"Our team competes every spring."},
  {w:"competent", pos:"adjective", ipa:"/ˈkɑːmpɪtənt/", def:"Capable.", ex:"She's a competent driver."},
  {w:"compile", pos:"verb", ipa:"/kəmˈpaɪl/", def:"To gather together.", ex:"He compiled a list."},
  {w:"complacent", pos:"adjective", ipa:"/kəmˈpleɪsənt/", def:"Too satisfied to improve.", ex:"Don't get complacent."},
  {w:"complement", pos:"noun", ipa:"/ˈkɑːmplɪmənt/", def:"Something that completes.", ex:"The sauce is a perfect complement."},
  {w:"complex", pos:"adjective", ipa:"/kəmˈpleks/", def:"Complicated.", ex:"It's a complex issue."},
  {w:"complicate", pos:"verb", ipa:"/ˈkɑːmplɪkeɪt/", def:"To make difficult.", ex:"Don't complicate things."},
  {w:"comply", pos:"verb", ipa:"/kəmˈplaɪ/", def:"To follow rules.", ex:"You must comply with the policy."},
  {w:"compose", pos:"verb", ipa:"/kəmˈpoʊz/", def:"To write; to make up.", ex:"She composed a letter."},
  {w:"compound", pos:"noun", ipa:"/ˈkɑːmpaʊnd/", def:"A mixture.", ex:"The medicine is a compound."},
  {w:"comprehend", pos:"verb", ipa:"/ˌkɑːmprɪˈhend/", def:"To understand.", ex:"I couldn't comprehend the lecture."},
  {w:"compress", pos:"verb", ipa:"/kəmˈpres/", def:"To squeeze.", ex:"Compress the files before sending."},
  {w:"comprise", pos:"verb", ipa:"/kəmˈpraɪz/", def:"To consist of.", ex:"The team comprises ten people."},
  {w:"compromise", pos:"noun", ipa:"/ˈkɑːmprəmaɪz/", def:"A mutual agreement.", ex:"We reached a compromise."},
  {w:"concede", pos:"verb", ipa:"/kənˈsiːd/", def:"To admit.", ex:"He conceded the election."},
  {w:"conceive", pos:"verb", ipa:"/kənˈsiːv/", def:"To imagine; to think of.", ex:"She conceived the idea last year."},
  {w:"concentrate", pos:"verb", ipa:"/ˈkɑːnsəntreɪt/", def:"To focus.", ex:"I can't concentrate with noise."},
  {w:"concept", pos:"noun", ipa:"/ˈkɑːnsept/", def:"An idea.", ex:"It's a simple concept."},
  {w:"concern", pos:"noun", ipa:"/kənˈsɜːrn/", def:"Worry.", ex:"Safety is our main concern."},
  {w:"concise", pos:"adjective", ipa:"/kənˈsaɪs/", def:"Brief and clear.", ex:"Keep your answers concise."},
  {w:"conclude", pos:"verb", ipa:"/kənˈkluːd/", def:"To finish; to decide.", ex:"We concluded the meeting at five."},
  {w:"concrete", pos:"adjective", ipa:"/kɑːnˈkriːt/", def:"Specific; real.", ex:"Give me a concrete example."},
  {w:"concur", pos:"verb", ipa:"/kənˈkɜːr/", def:"To agree.", ex:"I concur with your decision."},
  {w:"condemn", pos:"verb", ipa:"/kənˈdem/", def:"To criticize strongly.", ex:"Leaders condemned the attack."},
  {w:"condense", pos:"verb", ipa:"/kənˈdens/", def:"To shorten.", ex:"Condense the report to one page."},
  {w:"condone", pos:"verb", ipa:"/kənˈdoʊn/", def:"To accept wrongdoing.", ex:"We don't condone cheating."},
  {w:"conducive", pos:"adjective", ipa:"/kənˈduːsɪv/", def:"Helping something happen.", ex:"Quiet rooms are conducive to study."},
  {w:"confer", pos:"verb", ipa:"/kənˈfɜːr/", def:"To discuss; to grant.", ex:"They conferred for an hour."},
  {w:"confess", pos:"verb", ipa:"/kənˈfes/", def:"To admit.", ex:"She confessed her mistake."},
  {w:"confide", pos:"verb", ipa:"/kənˈfaɪd/", def:"To share a secret.", ex:"She confided in her friend."},
  {w:"confine", pos:"verb", ipa:"/kənˈfaɪn/", def:"To limit.", ex:"Please confine your remarks to the topic."},
  {w:"confirm", pos:"verb", ipa:"/kənˈfɜːrm/", def:"To verify.", ex:"Please confirm your appointment."},
  {w:"confiscate", pos:"verb", ipa:"/ˈkɑːnfɪskeɪt/", def:"To take away officially.", ex:"They confiscated his phone."},
  {w:"conflict", pos:"noun", ipa:"/ˈkɑːnflɪkt/", def:"A disagreement.", ex:"We resolved the conflict."},
  {w:"conform", pos:"verb", ipa:"/kənˈfɔːrm/", def:"To follow the norm.", ex:"She refused to conform."},
  {w:"confront", pos:"verb", ipa:"/kənˈfrʌnt/", def:"To face.", ex:"He confronted the problem directly."},
  {w:"confuse", pos:"verb", ipa:"/kənˈfjuːz/", def:"To make unclear.", ex:"The map confused me."},
  {w:"congenial", pos:"adjective", ipa:"/kənˈdʒiːniəl/", def:"Pleasant.", ex:"We had a congenial dinner."},
  {w:"congested", pos:"adjective", ipa:"/kənˈdʒestɪd/", def:"Overcrowded.", ex:"The roads were congested."},
  {w:"congratulate", pos:"verb", ipa:"/kənˈɡrætʃəleɪt/", def:"To praise for success.", ex:"We congratulated the graduate."},
  {w:"congregate", pos:"verb", ipa:"/ˈkɑːŋɡrɪɡeɪt/", def:"To gather.", ex:"Fans congregated outside."},
  {w:"conquer", pos:"verb", ipa:"/ˈkɑːŋkər/", def:"To overcome.", ex:"She conquered her fear."},
  {w:"conscience", pos:"noun", ipa:"/ˈkɑːnʃəns/", def:"Moral sense.", ex:"His conscience bothered him."},
  {w:"conscientious", pos:"adjective", ipa:"/ˌkɑːnʃiˈenʃəs/", def:"Careful and responsible.", ex:"She's a conscientious worker."},
  {w:"conscious", pos:"adjective", ipa:"/ˈkɑːnʃəs/", def:"Awake; aware.", ex:"He was conscious during surgery."},
  {w:"consensus", pos:"noun", ipa:"/kənˈsensəs/", def:"General agreement.", ex:"We reached a consensus."},
  {w:"consent", pos:"verb", ipa:"/kənˈsent/", def:"To agree.", ex:"She consented to the treatment."},
  {w:"consequence", pos:"noun", ipa:"/ˈkɑːnsɪkwens/", def:"A result.", ex:"Think about the consequences."},
  {w:"conserve", pos:"verb", ipa:"/kənˈsɜːrv/", def:"To save.", ex:"We must conserve water."},
  {w:"considerable", pos:"adjective", ipa:"/kənˈsɪdərəbəl/", def:"Large.", ex:"It was a considerable amount."},
  {w:"considerate", pos:"adjective", ipa:"/kənˈsɪdərət/", def:"Thoughtful of others.", ex:"It was considerate of you."},
  {w:"consist", pos:"verb", ipa:"/kənˈsɪst/", def:"To be made up of.", ex:"The class consists of adults."},
  {w:"console", pos:"verb", ipa:"/kənˈsoʊl/", def:"To comfort.", ex:"She consoled the crying child."},
  {w:"consolidate", pos:"verb", ipa:"/kənˈsɑːlɪdeɪt/", def:"To combine.", ex:"We consolidated our debts."},
  {w:"conspicuous", pos:"adjective", ipa:"/kənˈspɪkjuəs/", def:"Very noticeable.", ex:"Her red coat was conspicuous."},
  {w:"conspire", pos:"verb", ipa:"/kənˈspaɪər/", def:"To plot secretly.", ex:"They conspired against him."},
  {w:"constant", pos:"adjective", ipa:"/ˈkɑːnstənt/", def:"Unchanging.", ex:"The noise was constant."},
  {w:"constrain", pos:"verb", ipa:"/kənˈstreɪn/", def:"To limit.", ex:"The budget constrains us."},
  {w:"construct", pos:"verb", ipa:"/kənˈstrʌkt/", def:"To build.", ex:"They constructed a new school."},
  {w:"consult", pos:"verb", ipa:"/kənˈsʌlt/", def:"To seek advice.", ex:"Consult a doctor."},
  {w:"consume", pos:"verb", ipa:"/kənˈsuːm/", def:"To use up.", ex:"The fire consumed the house."},
  {w:"contact", pos:"noun", ipa:"/ˈkɑːntækt/", def:"Communication.", ex:"We lost contact."},
  {w:"contagious", pos:"adjective", ipa:"/kənˈteɪdʒəs/", def:"Spreading easily.", ex:"Laughter is contagious."},
  {w:"contain", pos:"verb", ipa:"/kənˈteɪn/", def:"To hold; to control.", ex:"The box contains books."},
  {w:"contaminate", pos:"verb", ipa:"/kənˈtæmɪneɪt/", def:"To pollute.", ex:"The water was contaminated."},
  {w:"contemplate", pos:"verb", ipa:"/ˈkɑːntəmpleɪt/", def:"To think deeply.", ex:"She contemplated quitting."},
  {w:"contemporary", pos:"adjective", ipa:"/kənˈtempəreri/", def:"Modern.", ex:"I like contemporary art."},
  {w:"contempt", pos:"noun", ipa:"/kənˈtempt/", def:"Lack of respect.", ex:"He felt contempt for liars."},
  {w:"contend", pos:"verb", ipa:"/kənˈtend/", def:"To compete; to claim.", ex:"She contends the decision was unfair."},
  {w:"content", pos:"adjective", ipa:"/kənˈtent/", def:"Satisfied.", ex:"He's content with his life."},
  {w:"contest", pos:"noun", ipa:"/ˈkɑːntest/", def:"A competition.", ex:"She won the contest."},
  {w:"context", pos:"noun", ipa:"/ˈkɑːntekst/", def:"Surrounding situation.", ex:"Read it in context."},
  {w:"contingent", pos:"adjective", ipa:"/kənˈtɪndʒənt/", def:"Depending on.", ex:"Our plans are contingent on weather."},
  {w:"continual", pos:"adjective", ipa:"/kənˈtɪnjuəl/", def:"Repeated.", ex:"The continual noise annoyed us."},
  {w:"contort", pos:"verb", ipa:"/kənˈtɔːrt/", def:"To twist.", ex:"She contorted her face."},
  {w:"contract", pos:"noun", ipa:"/ˈkɑːntrækt/", def:"A legal agreement.", ex:"We signed the contract."},
  {w:"contradict", pos:"verb", ipa:"/ˌkɑːntrəˈdɪkt/", def:"To say the opposite.", ex:"Don't contradict your boss."},
  {w:"contrary", pos:"adjective", ipa:"/ˈkɑːntreri/", def:"Opposite.", ex:"Contrary to rumors, we're open."},
  {w:"contrast", pos:"noun", ipa:"/ˈkɑːntræst/", def:"A clear difference.", ex:"The contrast is striking."},
  {w:"contribute", pos:"verb", ipa:"/kənˈtrɪbjuːt/", def:"To give.", ex:"Everyone contributed ideas."},
  {w:"contrive", pos:"verb", ipa:"/kənˈtraɪv/", def:"To plan cleverly.", ex:"She contrived an excuse."},
  {w:"controversial", pos:"adjective", ipa:"/ˌkɑːntrəˈvɜːrʃəl/", def:"Causing disagreement.", ex:"It's a controversial topic."},
  {w:"convene", pos:"verb", ipa:"/kənˈviːn/", def:"To gather.", ex:"The board convened at noon."},
  {w:"convenient", pos:"adjective", ipa:"/kənˈviːniənt/", def:"Easy and useful.", ex:"It's convenient for me."},
  {w:"converge", pos:"verb", ipa:"/kənˈvɜːrdʒ/", def:"To come together.", ex:"The roads converge here."},
  {w:"converse", pos:"verb", ipa:"/kənˈvɜːrs/", def:"To talk.", ex:"We conversed for hours."},
  {w:"convert", pos:"verb", ipa:"/kənˈvɜːrt/", def:"To change.", ex:"We converted the garage."},
  {w:"convey", pos:"verb", ipa:"/kənˈveɪ/", def:"To communicate.", ex:"Please convey my thanks."},
  {w:"convict", pos:"verb", ipa:"/kənˈvɪkt/", def:"To find guilty.", ex:"He was convicted of theft."},
  {w:"convince", pos:"verb", ipa:"/kənˈvɪns/", def:"To persuade.", ex:"She convinced me to join."},
  {w:"convoluted", pos:"adjective", ipa:"/ˌkɑːnvəˈluːtɪd/", def:"Very complex.", ex:"The plot was convoluted."},
  {w:"cooperate", pos:"verb", ipa:"/koʊˈɑːpəreɪt/", def:"To work together.", ex:"Please cooperate with staff."},
  {w:"coordinate", pos:"verb", ipa:"/koʊˈɔːrdɪneɪt/", def:"To organize.", ex:"She coordinated the event."},
  {w:"cordial", pos:"adjective", ipa:"/ˈkɔːrdʒəl/", def:"Warm and friendly.", ex:"We had a cordial meeting."},
  {w:"core", pos:"noun", ipa:"/kɔːr/", def:"The central part.", ex:"Honesty is her core value."},
  {w:"corporate", pos:"adjective", ipa:"/ˈkɔːrpərət/", def:"Business-related.", ex:"She works in corporate law."},
  {w:"correlate", pos:"verb", ipa:"/ˈkɔːrəleɪt/", def:"To be related.", ex:"Stress correlates with illness."},
  {w:"correspond", pos:"verb", ipa:"/ˌkɔːrəˈspɑːnd/", def:"To match; to write letters.", ex:"The dates don't correspond."},
  {w:"corroborate", pos:"verb", ipa:"/kəˈrɑːbəreɪt/", def:"To confirm.", ex:"Witnesses corroborated her story."},
  {w:"corrode", pos:"verb", ipa:"/kəˈroʊd/", def:"To eat away.", ex:"Rust corroded the pipe."},
  {w:"corrupt", pos:"adjective", ipa:"/kəˈrʌpt/", def:"Dishonest.", ex:"The official was corrupt."},
  {w:"counsel", pos:"verb", ipa:"/ˈkaʊnsəl/", def:"To advise.", ex:"She counsels students."},
  {w:"counter", pos:"verb", ipa:"/ˈkaʊntər/", def:"To respond against.", ex:"He countered every argument."},
  {w:"counterpart", pos:"noun", ipa:"/ˈkaʊntərpɑːrt/", def:"A matching person.", ex:"I met my French counterpart."},
  {w:"countless", pos:"adjective", ipa:"/ˈkaʊntləs/", def:"Very many.", ex:"We've had countless meetings."},
  {w:"courteous", pos:"adjective", ipa:"/ˈkɜːrtiəs/", def:"Polite.", ex:"The staff was courteous."},
  {w:"crackdown", pos:"noun", ipa:"/ˈkrækdaʊn/", def:"Strong enforcement.", ex:"There's a crackdown on speeding."},
  {w:"cradle", pos:"noun", ipa:"/ˈkreɪdəl/", def:"A baby's bed.", ex:"The baby slept in the cradle."},
  {w:"craft", pos:"noun", ipa:"/kræft/", def:"A skill; a trade.", ex:"She mastered her craft."},
  {w:"cram", pos:"verb", ipa:"/kræm/", def:"To stuff; to study hard.", ex:"He crammed for the test."},
  {w:"cranky", pos:"adjective", ipa:"/ˈkræŋki/", def:"Irritable.", ex:"The baby was cranky."},
  {w:"crash", pos:"verb", ipa:"/kræʃ/", def:"To collide.", ex:"The computer crashed."},
  {w:"crate", pos:"noun", ipa:"/kreɪt/", def:"A wooden box.", ex:"The apples came in a crate."},
  {w:"crave", pos:"verb", ipa:"/kreɪv/", def:"To want strongly.", ex:"She craved chocolate."},
  {w:"crawl", pos:"verb", ipa:"/krɔːl/", def:"To move slowly on hands and knees.", ex:"The baby crawled."},
  {w:"craze", pos:"noun", ipa:"/kreɪz/", def:"A fad.", ex:"The fitness craze spread fast."},
  {w:"creak", pos:"verb", ipa:"/kriːk/", def:"To make a squeaking sound.", ex:"The door creaked."},
  {w:"credible", pos:"adjective", ipa:"/ˈkredəbəl/", def:"Believable.", ex:"She's a credible witness."},
  {w:"credit", pos:"noun", ipa:"/ˈkredɪt/", def:"Praise; a loan system.", ex:"Give credit where it's due."},
  {w:"creep", pos:"verb", ipa:"/kriːp/", def:"To move quietly.", ex:"He crept upstairs."},
  {w:"crest", pos:"noun", ipa:"/krest/", def:"The top.", ex:"We reached the crest of the hill."},
  {w:"crevice", pos:"noun", ipa:"/ˈkrevɪs/", def:"A narrow crack.", ex:"Water seeped into the crevice."},
  {w:"crew", pos:"noun", ipa:"/kruː/", def:"A team of workers.", ex:"The crew finished early."},
  {w:"crisp", pos:"adjective", ipa:"/krɪsp/", def:"Fresh and firm.", ex:"The air was crisp."},
  {w:"criteria", pos:"noun", ipa:"/kraɪˈtɪriə/", def:"Standards.", ex:"We judged by clear criteria."},
  {w:"critic", pos:"noun", ipa:"/ˈkrɪtɪk/", def:"One who judges.", ex:"The critic praised the film."},
  {w:"critique", pos:"noun", ipa:"/krɪˈtiːk/", def:"An evaluation.", ex:"She gave a fair critique."},
  {w:"crook", pos:"noun", ipa:"/krʊk/", def:"A criminal.", ex:"The crook was arrested."},
  {w:"cross", pos:"adjective", ipa:"/krɔːs/", def:"Angry.", ex:"She was cross with me."},
  {w:"crouch", pos:"verb", ipa:"/kraʊtʃ/", def:"To bend low.", ex:"He crouched behind the wall."},
  {w:"crucial", pos:"adjective", ipa:"/ˈkruːʃəl/", def:"Very important.", ex:"This is a crucial decision."},
  {w:"crude", pos:"adjective", ipa:"/kruːd/", def:"Rough; rude.", ex:"It was a crude joke."},
  {w:"cruise", pos:"verb", ipa:"/kruːz/", def:"To travel smoothly.", ex:"We cruised along the coast."},
  {w:"crumble", pos:"verb", ipa:"/ˈkrʌmbəl/", def:"To break apart.", ex:"The cookie crumbled."},
  {w:"crumple", pos:"verb", ipa:"/ˈkrʌmpəl/", def:"To crush.", ex:"He crumpled the paper."},
  {w:"crunch", pos:"verb", ipa:"/krʌntʃ/", def:"To crush noisily.", ex:"She crunched the numbers."},
  {w:"crusade", pos:"noun", ipa:"/kruːˈseɪd/", def:"A campaign.", ex:"She led a crusade for literacy."},
  {w:"crush", pos:"verb", ipa:"/krʌʃ/", def:"To press hard.", ex:"Don't crush the box."},
  {w:"crust", pos:"noun", ipa:"/krʌst/", def:"Hard outer layer.", ex:"He ate the bread crust."},
  {w:"crux", pos:"noun", ipa:"/krʌks/", def:"The main point.", ex:"That's the crux of the matter."},
  {w:"cue", pos:"noun", ipa:"/kjuː/", def:"A signal.", ex:"That's my cue to leave."},
  {w:"culinary", pos:"adjective", ipa:"/ˈkʌlɪneri/", def:"Related to cooking.", ex:"She took culinary classes."},
  {w:"culminate", pos:"verb", ipa:"/ˈkʌlmɪneɪt/", def:"To reach the highest point.", ex:"The festival culminated in fireworks."},
  {w:"culpable", pos:"adjective", ipa:"/ˈkʌlpəbəl/", def:"Deserving blame.", ex:"He was culpable for the error."},
  {w:"cultivate", pos:"verb", ipa:"/ˈkʌltɪveɪt/", def:"To grow; to develop.", ex:"She cultivated friendships."},
  {w:"cunning", pos:"adjective", ipa:"/ˈkʌnɪŋ/", def:"Clever in a tricky way.", ex:"It was a cunning plan."},
  {w:"curb", pos:"verb", ipa:"/kɜːrb/", def:"To control.", ex:"We must curb spending."},
  {w:"curfew", pos:"noun", ipa:"/ˈkɜːrfjuː/", def:"A time limit.", ex:"The teen has a 10 p.m. curfew."},
  {w:"curious", pos:"adjective", ipa:"/ˈkjʊriəs/", def:"Eager to learn.", ex:"The kids were curious."},
  {w:"curl", pos:"verb", ipa:"/kɜːrl/", def:"To form rings.", ex:"She curled her hair."},
  {w:"currency", pos:"noun", ipa:"/ˈkɜːrənsi/", def:"Money.", ex:"What's the local currency?"},
  {w:"current", pos:"adjective", ipa:"/ˈkɜːrənt/", def:"Present.", ex:"The current policy works."},
  {w:"curriculum", pos:"noun", ipa:"/kəˈrɪkjələm/", def:"A course of study.", ex:"The curriculum changed."},
  {w:"curse", pos:"noun", ipa:"/kɜːrs/", def:"A swear; a misfortune.", ex:"He muttered a curse."},
  {w:"curt", pos:"adjective", ipa:"/kɜːrt/", def:"Rudely brief.", ex:"His reply was curt."},
  {w:"curtail", pos:"verb", ipa:"/kɜːrˈteɪl/", def:"To cut short.", ex:"We curtailed the trip."},
  {w:"cushion", pos:"noun", ipa:"/ˈkʊʃən/", def:"A soft pillow; protection.", ex:"Savings are a cushion."},
  {w:"custody", pos:"noun", ipa:"/ˈkʌstədi/", def:"Legal care.", ex:"She won custody of the kids."},
  {w:"custom", pos:"noun", ipa:"/ˈkʌstəm/", def:"A tradition.", ex:"It's our custom to gather."},
  {w:"customary", pos:"adjective", ipa:"/ˈkʌstəməri/", def:"Usual.", ex:"It's customary to tip."},
  {w:"cutback", pos:"noun", ipa:"/ˈkʌtbæk/", def:"A reduction.", ex:"There were cutbacks at work."},
  {w:"cycle", pos:"noun", ipa:"/ˈsaɪkəl/", def:"A repeating series.", ex:"The news cycle is fast."},
  {w:"cynical", pos:"adjective", ipa:"/ˈsɪnɪkəl/", def:"Distrustful.", ex:"He's cynical about politics."},
  {w:"dabble", pos:"verb", ipa:"/ˈdæbəl/", def:"To try briefly.", ex:"She dabbled in painting."},
  {w:"dainty", pos:"adjective", ipa:"/ˈdeɪnti/", def:"Delicate.", ex:"She took dainty bites."},
  {w:"damp", pos:"adjective", ipa:"/dæmp/", def:"Slightly wet.", ex:"The basement was damp."},
  {w:"dangle", pos:"verb", ipa:"/ˈdæŋɡəl/", def:"To hang loosely.", ex:"He dangled the keys."},
  {w:"dapper", pos:"adjective", ipa:"/ˈdæpər/", def:"Neatly dressed.", ex:"He looked dapper."},
  {w:"dart", pos:"verb", ipa:"/dɑːrt/", def:"To move quickly.", ex:"She darted across the street."},
  {w:"dash", pos:"verb", ipa:"/dæʃ/", def:"To rush.", ex:"He dashed to the store."},
  {w:"daunting", pos:"adjective", ipa:"/ˈdɔːntɪŋ/", def:"Intimidating.", ex:"The task seemed daunting."},
  {w:"dawdle", pos:"verb", ipa:"/ˈdɔːdəl/", def:"To waste time.", ex:"Stop dawdling!"},
  {w:"dazzle", pos:"verb", ipa:"/ˈdæzəl/", def:"To impress.", ex:"The lights dazzled us."},
  {w:"deadline", pos:"noun", ipa:"/ˈdedlaɪn/", def:"Due date.", ex:"The deadline is Friday."},
  {w:"deadlock", pos:"noun", ipa:"/ˈdedlɑːk/", def:"A standstill.", ex:"Talks ended in deadlock."},
  {w:"deadly", pos:"adjective", ipa:"/ˈdedli/", def:"Lethal.", ex:"The virus proved deadly."},
  {w:"deafening", pos:"adjective", ipa:"/ˈdefənɪŋ/", def:"Very loud.", ex:"The roar was deafening."},
  {w:"dearth", pos:"noun", ipa:"/dɜːrθ/", def:"A lack.", ex:"There's a dearth of housing."},
  {w:"debacle", pos:"noun", ipa:"/dɪˈbɑːkəl/", def:"A disaster.", ex:"The launch was a debacle."},
  {w:"debris", pos:"noun", ipa:"/dəˈbriː/", def:"Scattered remains.", ex:"Crews cleared the debris."},
  {w:"debut", pos:"noun", ipa:"/deɪˈbjuː/", def:"A first appearance.", ex:"She made her debut on stage."},
  {w:"decorum", pos:"noun", ipa:"/dɪˈkɔːrəm/", def:"Proper behavior.", ex:"Maintain decorum in court."},
  {w:"decree", pos:"noun", ipa:"/dɪˈkriː/", def:"An official order.", ex:"The decree took effect."},
  {w:"decry", pos:"verb", ipa:"/dɪˈkraɪ/", def:"To condemn publicly.", ex:"They decried the decision."},
  {w:"dedicate", pos:"verb", ipa:"/ˈdedɪkeɪt/", def:"To devote.", ex:"She dedicated her life to teaching."},
  {w:"deduce", pos:"verb", ipa:"/dɪˈduːs/", def:"To figure out logically.", ex:"We deduced the answer."},
  {w:"deem", pos:"verb", ipa:"/diːm/", def:"To consider.", ex:"They deemed it unsafe."},
  {w:"deface", pos:"verb", ipa:"/dɪˈfeɪs/", def:"To damage the appearance.", ex:"Vandals defaced the wall."},
  {w:"default", pos:"noun", ipa:"/dɪˈfɔːlt/", def:"Failure to pay; preset.", ex:"He defaulted on the loan."},
  {w:"defeat", pos:"noun", ipa:"/dɪˈfiːt/", def:"A loss.", ex:"They accepted defeat gracefully."},
  {w:"defect", pos:"noun", ipa:"/ˈdiːfekt/", def:"A flaw.", ex:"The car had a defect."},
  {w:"defend", pos:"verb", ipa:"/dɪˈfend/", def:"To protect.", ex:"She defended her friend."},
  {w:"defer", pos:"verb", ipa:"/dɪˈfɜːr/", def:"To postpone.", ex:"We deferred the decision."},
  {w:"defiant", pos:"adjective", ipa:"/dɪˈfaɪənt/", def:"Boldly resisting.", ex:"The teen was defiant."},
  {w:"deficient", pos:"adjective", ipa:"/dɪˈfɪʃənt/", def:"Lacking.", ex:"His diet is deficient in iron."},
  {w:"deficit", pos:"noun", ipa:"/ˈdefɪsɪt/", def:"A shortfall.", ex:"The budget deficit grew."},
  {w:"definitive", pos:"adjective", ipa:"/dɪˈfɪnɪtɪv/", def:"Final; authoritative.", ex:"This is the definitive guide."},
  {w:"deflate", pos:"verb", ipa:"/dɪˈfleɪt/", def:"To let air out; to reduce.", ex:"The news deflated him."},
  {w:"deflect", pos:"verb", ipa:"/dɪˈflekt/", def:"To turn aside.", ex:"She deflected the question."},
  {w:"defraud", pos:"verb", ipa:"/dɪˈfrɔːd/", def:"To cheat.", ex:"He defrauded investors."},
  {w:"defrost", pos:"verb", ipa:"/diːˈfrɔːst/", def:"To thaw.", ex:"Defrost the chicken overnight."},
  {w:"deft", pos:"adjective", ipa:"/deft/", def:"Skillful.", ex:"She gave a deft reply."},
  {w:"defunct", pos:"adjective", ipa:"/dɪˈfʌŋkt/", def:"No longer existing.", ex:"The store is defunct."},
  {w:"degrade", pos:"verb", ipa:"/dɪˈɡreɪd/", def:"To lower in quality.", ex:"Don't degrade yourself."},
  {w:"dehydrate", pos:"verb", ipa:"/diːˈhaɪdreɪt/", def:"To lose water.", ex:"Drink water so you don't dehydrate."},
  {w:"deject", pos:"verb", ipa:"/dɪˈdʒekt/", def:"To dishearten.", ex:"The loss dejected the team."},
  {w:"delay", pos:"noun", ipa:"/dɪˈleɪ/", def:"Lateness.", ex:"The flight had a delay."},
  {w:"delectable", pos:"adjective", ipa:"/dɪˈlektəbəl/", def:"Delicious.", ex:"The cake was delectable."},
  {w:"delegate", pos:"verb", ipa:"/ˈdelɪɡeɪt/", def:"To assign.", ex:"She delegated the task."},
  {w:"deliberate", pos:"adjective", ipa:"/dɪˈlɪbərət/", def:"Intentional.", ex:"It was a deliberate choice."},
  {w:"delicate", pos:"adjective", ipa:"/ˈdelɪkət/", def:"Fragile; sensitive.", ex:"It's a delicate situation."},
  {w:"delirious", pos:"adjective", ipa:"/dɪˈlɪriəs/", def:"Wildly excited; feverish.", ex:"The fans were delirious."},
  {w:"deliver", pos:"verb", ipa:"/dɪˈlɪvər/", def:"To bring; to give.", ex:"They deliver groceries."},
  {w:"delude", pos:"verb", ipa:"/dɪˈluːd/", def:"To mislead.", ex:"Don't delude yourself."},
  {w:"deluge", pos:"noun", ipa:"/ˈdeljuːdʒ/", def:"A flood.", ex:"We got a deluge of emails."},
  {w:"delusion", pos:"noun", ipa:"/dɪˈluːʒən/", def:"A false belief.", ex:"It's a delusion that he's fine."},
  {w:"delve", pos:"verb", ipa:"/delv/", def:"To dig into.", ex:"Let's delve deeper."},
  {w:"demand", pos:"noun", ipa:"/dɪˈmænd/", def:"A strong request.", ex:"There's high demand."},
  {w:"demeanor", pos:"noun", ipa:"/dɪˈmiːnər/", def:"Behavior.", ex:"His calm demeanor helped."},
  {w:"demise", pos:"noun", ipa:"/dɪˈmaɪz/", def:"Death; end.", ex:"The store's demise surprised us."},
  {w:"demolish", pos:"verb", ipa:"/dɪˈmɑːlɪʃ/", def:"To destroy.", ex:"They demolished the old mall."},
  {w:"demonstrate", pos:"verb", ipa:"/ˈdemənstreɪt/", def:"To show.", ex:"She demonstrated the app."},
  {w:"demure", pos:"adjective", ipa:"/dɪˈmjʊr/", def:"Shy and modest.", ex:"She gave a demure smile."},
  {w:"denote", pos:"verb", ipa:"/dɪˈnoʊt/", def:"To mean.", ex:"A red light denotes stop."},
  {w:"denounce", pos:"verb", ipa:"/dɪˈnaʊns/", def:"To condemn publicly.", ex:"They denounced the policy."},
  {w:"dense", pos:"adjective", ipa:"/dens/", def:"Thick.", ex:"The fog was dense."},
  {w:"dent", pos:"noun", ipa:"/dent/", def:"A small hollow.", ex:"There's a dent in the car."},
  {w:"depart", pos:"verb", ipa:"/dɪˈpɑːrt/", def:"To leave.", ex:"The train departs at six."},
  {w:"depend", pos:"verb", ipa:"/dɪˈpend/", def:"To rely.", ex:"We depend on each other."},
  {w:"depict", pos:"verb", ipa:"/dɪˈpɪkt/", def:"To show; to describe.", ex:"The film depicts real events."}
];
var SENTENCES = [
  {s:"She submitted her application in September, months before the deadline — the early bird really does catch the worm.", m:"Proverb: acting early gives you an advantage."},
  {s:"Honey found in ancient Egyptian tombs was still perfectly edible after 3,000 years.", m:"True: honey's low moisture keeps it from spoiling."},
  {s:"My phone's weekly screen-time report and I have agreed never to speak of it again.", m:"Humor: we all check our phones too much."},
  {s:"Discipline is choosing what you want most over what you want now — especially on rainy Monday mornings.", m:"Motivation: long-term goals beat short-term comfort."},
  {s:"He promised to help us move, then never showed up; as my grandmother says, actions speak louder than words.", m:"Proverb: what people do matters more than what they say."},
  {s:"An octopus has three hearts, and two of them stop beating when it swims.", m:"True: that is why octopuses prefer crawling to swimming."},
  {s:"Would you mind forwarding me the receipt at your earliest convenience?", m:"Polite: request a document promptly."},
  {s:"Nothing unites coworkers faster than the office Wi-Fi going down.", m:"Humor: shared suffering builds teamwork."},
  {s:"Don't count your chickens before they hatch — wait until the contract is signed before you celebrate.", m:"Proverb: don't assume success before it happens."},
  {s:"Botanically speaking, bananas are berries — but strawberries are not.", m:"True: berry is a scientific term about seeds and skin."},
  {s:"You don't need to be the fastest learner in the room; you need to be the one who comes back tomorrow.", m:"Motivation: consistency beats speed."},
  {s:"I've given you all the information I have, so now the ball is in your court.", m:"Idiom: it is your turn to act or decide."},
  {s:"Adulthood is mostly Googling is this normal with increasing urgency.", m:"Humor: grown-ups still feel unsure."},
  {s:"The Eiffel Tower grows about 15 centimeters taller every summer.", m:"True: heat makes iron expand."},
  {s:"I appreciate you flagging this issue before it became urgent.", m:"Professional: thank someone for an early warning."},
  {s:"To break the ice at the meeting, she asked everyone to share their favorite weekend activity.", m:"Idiom: to do something that makes people feel relaxed."},
  {s:"Every expert was once a beginner who refused to quit on a bad day.", m:"Motivation: persistence creates mastery."},
  {s:"Under the right conditions, hot water can freeze faster than cold water.", m:"True: this strange effect is called the Mpemba effect."},
  {s:"The elevator is the only place where strangers silently agree to stare at numbers together.", m:"Humor: elevators have unwritten rules."},
  {s:"Taking night classes while working full time and raising twins? Don't bite off more than you can chew.", m:"Idiom: don't take on more than you can handle."},
  {s:"When the teacher said the test was too long, Maya nodded — he had hit the nail on the head.", m:"Idiom: to say exactly the right thing."},
  {s:"Sharks have existed on Earth longer than trees have.", m:"True: sharks are about 450 million years old; trees about 350 million."},
  {s:"My houseplants have better survival instincts than my New Year's resolutions.", m:"Humor: resolutions rarely last."},
  {s:"Small steps taken daily will carry you farther than giant leaps taken rarely.", m:"Motivation: steady progress wins."},
  {s:"My brother calls once in a blue moon, usually when he needs help moving furniture.", m:"Idiom: very rarely."},
  {s:"A single day on Venus lasts longer than an entire year on Venus.", m:"True: it spins extremely slowly — 243 Earth days per rotation."},
  {s:"Could we push the deadline back by a couple of days?", m:"Workplace: ask for more time politely."},
  {s:"Working from home means your commute is eleven steps and the dress code is negotiable.", m:"Humor: remote work changed daily routines."},
  {s:"She stayed home from work, feeling a bit under the weather after the long flight.", m:"Idiom: feeling slightly sick."},
  {s:"Wombats are the only known animals whose droppings are cube-shaped.", m:"True: their intestines stretch unevenly, forming cubes."},
  {s:"The best time to start was yesterday; the second-best time is this morning.", m:"Motivation: start now, not someday."},
  {s:"Losing that job was a blessing in disguise — it pushed her to start the business she had always dreamed about.", m:"Idiom: something bad that leads to something good."},
  {s:"The most honest relationship in my life is with my alarm clock — it never pretends I'll get up on time.", m:"Humor: mornings are hard for everyone."},
  {s:"The heart of a shrimp is located in its head.", m:"True: its main organs sit just behind its eyes."},
  {s:"Let's circle back on this once we've had time to think it over.", m:"Workplace: revisit a topic later."},
  {s:"With finals approaching, he burned the midnight oil for two weeks straight.", m:"Idiom: to work late into the night."},
  {s:"Mistakes are proof that you are trying — a blank page teaches nothing.", m:"Motivation: errors are part of learning."},
  {s:"Sea otters hold hands while they sleep so they don't drift apart.", m:"True: this behavior is called rafting."},
  {s:"I have 47 browser tabs open, and I am emotionally attached to every one of them.", m:"Humor: tab hoarding is universal."},
  {s:"Working from home gives her the best of both worlds: a real salary and lunch with her kids.", m:"Idiom: the advantages of two different situations."},
  {s:"He accidentally let the cat out of the bag about the surprise party.", m:"Idiom: to reveal a secret by mistake."},
  {s:"Oxford University is older than the Aztec Empire.", m:"True: teaching began at Oxford around 1096; the Aztec capital rose in 1325."},
  {s:"My budget has two categories: bills and I deserved this.", m:"Humor: we all justify impulse spending."},
  {s:"Don't compare your chapter one to someone else's chapter twenty.", m:"Motivation: everyone's journey has its own timeline."},
  {s:"Fixing the car's transmission cost an arm and a leg, but at least it runs now.", m:"Idiom: very expensive."},
  {s:"Cleopatra lived closer in time to the iPhone than to the building of the pyramids.", m:"True: she died in 30 BCE; the pyramids rose around 2560 BCE."},
  {s:"I'd be grateful if you could keep me posted on any changes.", m:"Polite: ask for updates."},
  {s:"Autocorrect has ended more friendships than honest disagreements ever did.", m:"Humor: phones change our words."},
  {s:"After a month of practice, the driving test was a piece of cake.", m:"Idiom: very easy."},
  {s:"There are more ways to shuffle a deck of cards than there are atoms on Earth.", m:"True: 52 factorial is about 8 times 10 to the 67th power."},
  {s:"Courage isn't the absence of fear; it's sending the email anyway.", m:"Motivation: act despite nervousness."},
  {s:"When pigs fly, he said, I'll give up coffee — so don't hold your breath.", m:"Idiom: something that will never happen."},
  {s:"The gym is fullest in January and emptiest by March — hope has a season.", m:"Humor: resolutions fade quickly."},
  {s:"Nintendo was founded in 1889 — as a playing card company.", m:"True: it made hand-painted cards long before video games."},
  {s:"Please don't hesitate to reach out if anything comes up.", m:"Friendly: offer help openly."},
  {s:"We got soaked walking home; it was raining cats and dogs.", m:"Idiom: raining very heavily."},
  {s:"Your future self is watching what you do today — give them something to thank you for.", m:"Motivation: present choices shape the future."},
  {s:"The first computer programmer was a woman: Ada Lovelace, in the 1840s.", m:"True: she wrote an algorithm before computers existed."},
  {s:"Nothing tests a relationship like assembling flat-pack furniture together.", m:"Humor: furniture assembly challenges couples."},
  {s:"During the interview she spilled the beans about why she left her last job — too honestly, perhaps.", m:"Idiom: to reveal the truth or a secret."},
  {s:"When her daughter took her first steps, she was on cloud nine for days.", m:"Idiom: extremely happy."},
  {s:"In the 1830s, ketchup was sold as medicine.", m:"True: it was marketed as a cure for indigestion."},
  {s:"My spam folder believes I am a billionaire with twelve inheritances waiting.", m:"Humor: spam emails make wild promises."},
  {s:"Growth lives just outside your comfort zone, one awkward conversation at a time.", m:"Motivation: discomfort means you're improving."},
  {s:"He kills two birds with one stone by biking to work: exercise and no gas money.", m:"Idiom: to achieve two things with one action."},
  {s:"The inventor of the Pringles can had his ashes buried in one.", m:"True: Fred Baur's family honored his request in 2008."},
  {s:"Would it be possible to reschedule our meeting for Thursday afternoon?", m:"Professional: propose a new meeting time."},
  {s:"The printer only jams when the document is urgent — this is a law of nature.", m:"Humor: technology fails at the worst moment."},
  {s:"She hesitated too long and missed the boat on the cheap apartment.", m:"Idiom: to miss an opportunity."},
  {s:"The first item ever sold on eBay was a broken laser pointer.", m:"True: the founder was testing whether the site worked."},
  {s:"Reading twenty pages a day becomes twenty-four books a year — small habits compound.", m:"Motivation: tiny routines create big results."},
  {s:"The first recipe failed completely, so we're back to square one.", m:"Idiom: back to the beginning after a failure."},
  {s:"Just five more minutes is the biggest lie adults tell themselves daily.", m:"Humor: snoozing never works as planned."},
  {s:"The inventor of the frisbee was cremated, and his ashes were made into frisbees.", m:"True: Walter Morrison's family followed his wishes."},
  {s:"I wanted to follow up on the proposal I sent last week.", m:"Workplace: check on a pending item."},
  {s:"The contractor cut corners on the paint job, and now the walls are peeling.", m:"Idiom: to do something cheaply or carelessly."},
  {s:"The obstacle is often the path: the hard thing teaches what the easy thing never could.", m:"Motivation: difficulties build skill."},
  {s:"The @ symbol is more than 500 years old.", m:"True: merchants used it in the 1500s to mean at the price of."},
  {s:"Video calls taught us that everyone has a good side of their room.", m:"Humor: we curate what others see."},
  {s:"Nobody mentioned the layoffs at lunch; the elephant in the room was impossible to ignore.", m:"Idiom: an obvious problem everyone avoids discussing."},
  {s:"The nurse went the extra mile, staying late to explain the medication to the worried family.", m:"Idiom: to do more than expected."},
  {s:"The QWERTY keyboard was designed to slow typists down.", m:"True: it prevented early typewriter keys from jamming."},
  {s:"The self-checkout machine trusts me less than my own mother does.", m:"Humor: unexpected item in bagging area frustrates everyone."},
  {s:"You are allowed to be both a work in progress and a success story.", m:"Motivation: progress and pride can coexist."},
  {s:"Asked whether pineapple belongs on pizza, he sat on the fence and changed the subject.", m:"Idiom: to avoid taking sides."},
  {s:"The first computer bug was a real moth, found in 1947.", m:"True: Grace Hopper taped it into her logbook."},
  {s:"Thanks for your patience while we sort this out.", m:"Customer service: acknowledge a delay."},
  {s:"My car makes a strange noise until the mechanic listens — then it purrs like a kitten.", m:"Humor: problems hide from experts."},
  {s:"We have no fixed plan for Saturday — let's just play it by ear.", m:"Idiom: to decide as you go, without a plan."},
  {s:"The word robot comes from the Czech word robota, meaning forced labor.", m:"True: it appeared in a 1920 Czech play."},
  {s:"Ask the question — everyone else in the room is wondering too.", m:"Motivation: curiosity helps the whole group."},
  {s:"Phone cases are a dime a dozen at the night market.", m:"Idiom: very common and cheap."},
  {s:"Group chats have two kinds of people: those who reply instantly and those who read everything in silence.", m:"Humor: we all know a lurker."},
  {s:"A jiffy is a real unit of time: one-hundredth of a second.", m:"True: engineers use it in computing."},
  {s:"Could you walk me through the process one more time?", m:"Learning: ask for a repeated explanation."},
  {s:"They stayed close through thick and thin, from college dorms to retirement.", m:"Idiom: through good times and bad."},
  {s:"Done is better than perfect; a finished draft beats a perfect idea.", m:"Motivation: completion beats perfectionism."},
  {s:"The dot over the letters i and j has a name: a tittle.", m:"True: it comes from a Latin word for a tiny mark."},
  {s:"The terms and conditions page is the longest story nobody has ever read.", m:"Humor: everyone clicks agree blindly."},
  {s:"On her first day she hit the ground running, finishing three reports by noon.", m:"Idiom: to start something with energy and success."},
  {s:"After two warnings from his boss, he knew he was on thin ice.", m:"Idiom: in a risky situation."},
  {s:"The plastic tips on shoelaces are called aglets.", m:"True: they stop the laces from fraying."},
  {s:"My to-do list grows faster than my motivation — it's the only thing in my life that compounds.", m:"Humor: tasks multiply on their own."},
  {s:"Rest is not a reward for finishing; it's fuel for continuing.", m:"Motivation: breaks protect your energy."},
  {s:"She bit the bullet and called the dentist after months of tooth pain.", m:"Idiom: to face something unpleasant bravely."},
  {s:"Mount Everest grows about 4 millimeters taller every year.", m:"True: tectonic plates keep pushing it upward."},
  {s:"I'm afraid I have a prior commitment that evening.", m:"Polite: decline an invitation."},
  {s:"Coffee is a hug in a mug, and Monday mornings require several hugs.", m:"Humor: coffee culture is real."},
  {s:"Let sleeping dogs lie, her mother advised — don't bring up the old argument at dinner.", m:"Proverb: don't restart old conflicts."},
  {s:"The Sahara Desert was once green, with lakes and rivers.", m:"True: it was fertile about 6,000 years ago."},
  {s:"Learn from everyone: the beginner's question often reveals the expert's blind spot.", m:"Motivation: humility accelerates learning."},
  {s:"The delayed flight was the last straw; he switched airlines for good.", m:"Idiom: the final problem that makes you act."},
  {s:"The weather app said zero percent chance of rain, so naturally I got soaked.", m:"Humor: forecasts are unreliable."},
  {s:"The Moon is drifting about 3.8 centimeters farther from Earth each year.", m:"True: measured with lasers bounced off reflectors left by astronauts."},
  {s:"Let's touch base early next week to compare notes.", m:"Workplace: schedule a brief check-in."},
  {s:"If you think the quiet intern caused the leak, you're barking up the wrong tree.", m:"Idiom: to blame or pursue the wrong person."},
  {s:"Your English doesn't need to be perfect to be powerful — it needs to be used.", m:"Motivation: practice matters more than perfection."},
  {s:"Saturn is less dense than water, so it would float in a giant bathtub.", m:"True: it is the only planet lighter than water."},
  {s:"Parking far away for exercise, then circling ten minutes to park closer — modern fitness logic.", m:"Humor: our habits contradict themselves."},
  {s:"Stop beating around the bush and tell me what the test results say.", m:"Idiom: to avoid saying what you mean."},
  {s:"Searching for his keys in the whole stadium was a wild goose chase.", m:"Idiom: a hopeless search."},
  {s:"A teaspoon of neutron-star material would weigh about a billion tons.", m:"True: neutron stars pack a sun's mass into a city-sized ball."},
  {s:"My smartwatch congratulates me for standing up, which tells you everything about my lifestyle.", m:"Humor: fitness trackers set a low bar."},
  {s:"Ten minutes of practice beats zero minutes of planning to practice.", m:"Motivation: start small today."},
  {s:"He was in hot water after forgetting his anniversary — again.", m:"Idiom: in trouble."},
  {s:"There are more trees on Earth than stars in the Milky Way.", m:"True: about 3 trillion trees versus a few hundred billion stars."},
  {s:"I sincerely appreciate you taking the time to explain.", m:"Polite: thank someone for help."},
  {s:"I'll start Monday is the official motto of every diet ever attempted.", m:"Humor: we delay healthy habits."},
  {s:"She left a bad job for a worse one: out of the frying pan and into the fire.", m:"Idiom: from a bad situation to a worse one."},
  {s:"Your stomach grows a new lining every three to four days.", m:"True: otherwise it would digest itself."},
  {s:"The student who asks why learns twice: the answer and the thinking behind it.", m:"Motivation: curiosity deepens understanding."},
  {s:"The storm canceled the picnic, but every cloud has a silver lining — we finally cleaned the garage.", m:"Proverb: something good can come from bad situations."},
  {s:"The microwave beeps until acknowledged, like a tiny, persistent manager.", m:"Humor: appliances demand attention."},
  {s:"The human brain runs on about 20 watts — like a dim light bulb.", m:"True: it does this while managing your entire body."},
  {s:"Would you be available for a quick call tomorrow morning?", m:"Professional: request a short phone meeting."},
  {s:"She reminded herself that Rome wasn't built in a day when the new language felt impossible.", m:"Proverb: important things take time."},
  {s:"Failure is a teacher with strict methods but unforgettable lessons.", m:"Motivation: setbacks instruct."},
  {s:"Your tongue print is as unique as your fingerprint.", m:"True: no two tongue prints are alike."},
  {s:"Nothing says adult like getting excited about a new vacuum cleaner.", m:"Humor: priorities change with age."},
  {s:"His free throws improved because practice makes perfect, even at forty.", m:"Proverb: repeating something makes you better at it."},
  {s:"Look before you leap — read the lease carefully before you sign it.", m:"Proverb: think before you act."},
  {s:"You cannot hum while pinching your nose shut — try it.", m:"True: humming needs air to escape through the nose."},
  {s:"My passwords must contain a capital, a number, a symbol, and the tears of my ancestors.", m:"Humor: password rules are absurd."},
  {s:"Plant the tree today; shade comes later, but it always comes.", m:"Motivation: patient effort pays off."},
  {s:"She started learning piano at sixty: better late than never.", m:"Proverb: it's never too late to start."},
  {s:"Fingernails grow about four times faster than toenails.", m:"True: scientists think it's because fingers get more use."},
  {s:"Please let me know if there's anything I can do to help.", m:"Friendly: offer assistance."},
  {s:"The laundry chair holds clothes that are neither clean nor dirty — a third category science ignores.", m:"Humor: everyone has the chair."},
  {s:"Two heads are better than one, so they solved the puzzle together in half the time.", m:"Proverb: two people think better than one alone."},
  {s:"Ounce for ounce, human bone is stronger than concrete.", m:"True: it is both light and remarkably tough."},
  {s:"Speak up in the meeting — your quiet idea might be the loud solution.", m:"Motivation: your voice has value."},
  {s:"She keeps savings in two banks — don't put all your eggs in one basket.", m:"Proverb: don't risk everything on one plan."},
  {s:"Video meeting rule: whoever says can you hear me controls the next five minutes.", m:"Humor: tech issues dominate calls."},
  {s:"Lightning is about five times hotter than the surface of the sun.", m:"True: a bolt can reach 30,000 kelvins."},
  {s:"I'd like to confirm our reservation for two on Friday.", m:"Travel: verify a booking."},
  {s:"The grass always looks greener on the other side, until you have to mow it.", m:"Proverb: other people's lives seem better than they are."},
  {s:"Progress is rarely a straight line; expect detours, not dead ends.", m:"Motivation: setbacks are normal."},
  {s:"Antarctica is technically the largest desert on Earth.", m:"True: a desert is defined by dryness, not heat."},
  {s:"I bought a planner to get organized; now I need a planner to manage my planners.", m:"Humor: organizing can become the task itself."},
  {s:"A quick oil change now beats a broken engine later: a stitch in time saves nine.", m:"Proverb: fixing small problems early prevents big ones."},
  {s:"Where there's smoke, there's fire — three neighbors complaining means something is wrong.", m:"Proverb: rumors usually have some truth."},
  {s:"The shortest war in history lasted about 38 minutes.", m:"True: Britain defeated Zanzibar in 1896 before lunch."},
  {s:"The fridge light is the only thing that works the night shift without complaining.", m:"Humor: midnight snacks are universal."},
  {s:"The most reliable motivation is a routine that doesn't ask how you feel.", m:"Motivation: systems beat moods."},
  {s:"Curiosity killed the cat, her teacher joked, but it also made her a scientist.", m:"Proverb: curiosity can cause trouble (often said playfully)."},
  {s:"Alaska is the northernmost, westernmost, and easternmost U.S. state.", m:"True: its Aleutian Islands cross the 180th meridian."},
  {s:"Could you recommend a reliable plumber in the area?", m:"Everyday: ask for a local referral."},
  {s:"My neighbor's dog barks at the mail carrier daily, as if the mail were optional.", m:"Humor: dogs take their jobs seriously."},
  {s:"Don't judge a book by its cover — the quietest student wrote the best essay.", m:"Proverb: appearances can mislead."},
  {s:"The unicorn is the national animal of Scotland.", m:"True: it has symbolized the country since the 1400s."},
  {s:"Celebrate the small win: finishing the chapter counts, and chapters become books.", m:"Motivation: acknowledge progress."},
  {s:"Still waters run deep: the shy newcomer turned out to be a chess champion.", m:"Proverb: quiet people often have hidden depths."},
  {s:"Quick question emails are never quick and rarely just one question.", m:"Humor: workplace euphemisms decoded."},
  {s:"LEGO bricks made in the 1970s still click perfectly with bricks made today.", m:"True: the design has barely changed in decades."},
  {s:"I'm writing to inquire about the position advertised online.", m:"Job search: open a cover message."},
  {s:"Birds of a feather flock together — no wonder the two musicians became best friends.", m:"Proverb: people with similar interests attract each other."},
  {s:"Nobody remembers the typos in your first draft — they remember that you finished.", m:"Motivation: output over polish."},
  {s:"Woolly mammoths were still alive when the pyramids were built.", m:"True: a small herd survived on an Arctic island until about 1700 BCE."},
  {s:"I clean the house before the cleaning service arrives, which defeats the entire purpose.", m:"Humor: we perform tidiness for others."},
  {s:"An apple a day keeps the doctor away, though the dentist might disagree.", m:"Proverb: healthy habits prevent illness."},
  {s:"You can't have your cake and eat it too — working weekends means missing the games.", m:"Proverb: you can't have everything at once."},
  {s:"Carrots were originally purple, not orange.", m:"True: Dutch farmers developed the orange variety in the 1600s."},
  {s:"Traffic jams are just group meditation nobody signed up for.", m:"Humor: commuting tests patience."},
  {s:"A year from now, you'll wish you had started today — so start today.", m:"Motivation: act now."},
  {s:"Beggars can't be choosers, so he accepted the night shift gratefully.", m:"Proverb: accept what you're offered when options are few."},
  {s:"The first oranges were green.", m:"True: they grew in Southeast Asia, where warm weather keeps citrus green."},
  {s:"Thank you for getting back to me so promptly.", m:"Professional: appreciate a fast reply."},
  {s:"My plants die of attention or neglect — there is no middle setting.", m:"Humor: houseplants are dramatic."},
  {s:"The pen is mightier than the sword — one letter from the lawyer ended the dispute.", m:"Proverb: words can be more powerful than force."},
  {s:"Apples float because a quarter of their volume is air.", m:"True: that is why apple-bobbing works."},
  {s:"Kindness costs nothing and pays interest in ways money never will.", m:"Motivation: generosity compounds."},
  {s:"All that glitters is not gold; the luxury car spent more time in the shop than on the road.", m:"Proverb: attractive things aren't always valuable."},
  {s:"The snooze button is a time machine that only travels nine minutes into disappointment.", m:"Humor: snoozing never helps."},
  {s:"Peanut oil can be processed into an ingredient used in dynamite.", m:"True: it contains glycerol, which becomes nitroglycerin."},
  {s:"Let's agree to disagree and move on to the next item.", m:"Discussion: end a debate politely."},
  {s:"Honesty is the best policy, so she admitted the mistake before anyone noticed.", m:"Proverb: telling the truth is wisest."},
  {s:"The best network is built one genuine conversation at a time, not one business card at a time.", m:"Motivation: authentic connections last."},
  {s:"Sound travels more than four times faster in water than in air.", m:"True: whales can hear each other across entire oceans."},
  {s:"Online shopping carts are where budgets go to dream.", m:"Humor: carts fill faster than wallets allow."},
  {s:"Absence makes the heart grow fonder — after a month apart, they couldn't stop talking.", m:"Proverb: being apart can strengthen feelings."},
  {s:"Out of sight, out of mind: he forgot the gym the week he stopped walking past it.", m:"Proverb: we forget things we don't see."},
  {s:"Venus spins backward compared to most planets.", m:"True: on Venus the sun rises in the west."},
  {s:"Per my last email is office language for I already told you.", m:"Humor: polite phrases hide frustration."},
  {s:"Learn the skill before you need it; opportunity rarely waits for preparation.", m:"Motivation: prepare in advance."},
  {s:"Fortune favors the bold — she asked for the raise and got it.", m:"Proverb: brave action is often rewarded."},
  {s:"Your nose can detect roughly a trillion different scents.", m:"True: a 2014 study overturned the old 10,000-smells limit."},
  {s:"I'd love to take you up on that offer when things settle down.", m:"Friendly: accept later, politely."},
  {s:"The best parking spot is always taken by someone leaving as you arrive — the universe has rules.", m:"Humor: timing is everything."},
  {s:"Slow and steady wins the race; he studied thirty minutes daily and passed with ease.", m:"Proverb: consistent effort beats rushing."},
  {s:"The sun holds about 1.3 million Earths inside it.", m:"True: it contains 99.8 percent of the solar system's mass."},
  {s:"Your competition isn't other people — it's yesterday's version of you.", m:"Motivation: compete with yourself."},
  {s:"Don't bite the hand that feeds you — thank the mentor who opened that door.", m:"Proverb: don't harm those who help you."},
  {s:"My phone battery lasts all day except when I actually need it.", m:"Humor: batteries die at critical moments."},
  {s:"Sunlight takes about eight minutes to reach Earth.", m:"True: the sun is 150 million kilometers away."},
  {s:"Could you clarify what you meant by the second point?", m:"Meeting: ask for explanation."},
  {s:"A picture is worth a thousand words, so she sent a photo of the damage to the landlord.", m:"Idiom: images explain better than descriptions."},
  {s:"Write down your goals; a dream with a deadline becomes a plan.", m:"Motivation: clarity creates action."},
  {s:"It may rain diamonds on Neptune and Uranus.", m:"True: scientists believe pressure turns carbon into diamond showers."},
  {s:"Cooking shows make it look easy; my smoke detector disagrees.", m:"Humor: real cooking is messier."},
  {s:"When in Rome, do as the Romans do — she learned to greet with a bow in Kyoto.", m:"Proverb: follow local customs when traveling."},
  {s:"The squeaky wheel gets the grease: after three polite emails, one firm call fixed the billing error.", m:"Proverb: those who complain get attention."},
  {s:"A giant cloud of water vapor in deep space holds 140 trillion times Earth's oceans.", m:"True: astronomers found it around a distant quasar in 2011."},
  {s:"Weekends are proof that time flies when you're finally enjoying it.", m:"Humor: free time passes fastest."},
  {s:"Energy follows attention — guard yours like the resource it is.", m:"Motivation: focus protects energy."},
  {s:"No pain, no gain — the marathon hurt, but the medal was worth it.", m:"Proverb: effort is required for results."},
  {s:"Dolphins use signature whistles the way humans use names.", m:"True: each dolphin develops its own identifying call."},
  {s:"I completely understand — family comes first.", m:"Empathy: respond to a cancellation kindly."},
  {s:"My umbrella's only job is to guarantee sunshine.", m:"Humor: preparation prevents the problem."},
  {s:"What goes around comes around: the manager who helped everyone got promoted by unanimous vote.", m:"Proverb: your actions return to you."},
  {s:"Crows can recognize human faces — and hold grudges for years.", m:"True: researchers who trapped crows were scolded by their descendants."},
  {s:"The right book at the right time can change the direction of a life.", m:"Motivation: reading transforms thinking."},
  {s:"Easy come, easy go — he spent the bonus in a single weekend.", m:"Proverb: money gained quickly is spent quickly."},
  {s:"The quietest person in the meeting always has the idea that saves the project.", m:"Humor: listen to the quiet ones."},
  {s:"Honeybees can learn to recognize human faces.", m:"True: they process faces the way we do, in pieces."},
  {s:"Would you mind keeping the noise down after ten?", m:"Neighborly: make a polite request."},
  {s:"Like father, like son — both fall asleep during documentaries.", m:"Proverb: children resemble their parents."},
  {s:"Saying no to the good lets you say yes to the great.", m:"Motivation: priorities require sacrifice."},
  {s:"Hummingbirds are the only birds that can fly backward.", m:"True: their wings rotate in a full circle."},
  {s:"Diet tip: eat cake on your birthday — everyone knows holiday calories don't count.", m:"Humor: we invent food rules."},
  {s:"The apple doesn't fall far from the tree: her daughter argues just like she does.", m:"Proverb: children are similar to their parents."},
  {s:"Too many cooks spoil the broth — with six editors, the report made no sense.", m:"Proverb: too many people involved ruins the result."},
  {s:"Owls cannot move their eyes; their eyeballs are tube-shaped.", m:"True: they turn their whole heads instead — up to 270 degrees."},
  {s:"The office coffee machine has witnessed more drama than daytime television.", m:"Humor: break rooms are social hubs."},
  {s:"Master the boring fundamentals; brilliance is built on basics.", m:"Motivation: foundations matter most."},
  {s:"A watched pot never boils; the page loaded the moment she looked away.", m:"Proverb: waiting makes time feel slower."},
  {s:"A group of owls is called a parliament.", m:"True: English has poetic names for many animal groups."},
  {s:"I'm delighted to accept your invitation — see you Saturday.", m:"Social: accept warmly."},
  {s:"I meant to save money this month, but the sale signs staged an intervention.", m:"Humor: sales are irresistible."},
  {s:"You reap what you sow — months of kindness came back as help when she needed it.", m:"Proverb: your efforts determine your results."},
  {s:"A group of flamingos is called a flamboyance.", m:"True: the name fits their pink feathers perfectly."},
  {s:"Teach what you learn — explaining it will teach it to you twice.", m:"Motivation: teaching deepens mastery."},
  {s:"Strike while the iron is hot: apply for the grant before the deadline rush.", m:"Proverb: act while the opportunity lasts."},
  {s:"GPS says arrived while I'm clearly in the middle of nowhere.", m:"Humor: navigation isn't perfect."},
  {s:"Sloths can hold their breath longer than dolphins can.", m:"True: about 40 minutes, by slowing their heart rate."},
  {s:"Please accept my apologies for the delayed response.", m:"Professional: apologize for lateness."},
  {s:"Make hay while the sun shines — save money during the busy season.", m:"Proverb: use good conditions while they last."},
  {s:"Luck favors the prepared: the overnight success usually took ten years.", m:"Motivation: preparation creates opportunity."},
  {s:"Reindeer eyes turn blue in winter.", m:"True: the change helps them see in months of darkness."},
  {s:"My fitness app and my couch are in a long-term disagreement.", m:"Humor: exercise intentions versus reality."},
  {s:"A leopard can't change its spots, but people can change their habits with effort.", m:"Proverb: basic nature is hard to change (often debated playfully)."},
  {s:"Don't cry over spilled milk — the vase is broken, so let's clean up and move on.", m:"Proverb: don't waste time regretting mistakes."},
  {s:"A polar bear's fur is not white — each hair is a transparent tube, and its skin is black.", m:"True: the hollow hairs trap heat from the sun."},
  {s:"The hardest part of working out is putting on the shoes.", m:"Humor: starting is the real battle."},
  {s:"Your attitude is the one remote control you always hold.", m:"Motivation: choose your response."},
  {s:"Let bygones be bygones, they agreed, and the old friends laughed like teenagers again.", m:"Proverb: forgive past offenses."},
  {s:"A blue whale's heart is about the size of a small car.", m:"True: its heartbeat can be heard from 3 kilometers away."},
  {s:"I'd be happy to lend a hand with the move this weekend.", m:"Friendly: volunteer help."},
  {s:"Limited time offer has been running for three years at my favorite store.", m:"Humor: marketing creates false urgency."},
  {s:"After the health scare, he turned over a new leaf: vegetables, walks, and eight hours of sleep.", m:"Idiom: to start behaving better."},
  {s:"Baby elephants suck their trunks the way human babies suck their thumbs.", m:"True: it comforts them while they learn to use it."},
  {s:"Difficult conversations, held kindly, prevent difficult consequences later.", m:"Motivation: honesty now saves pain later."},
  {s:"A new broom sweeps clean — the new manager reorganized everything in a week.", m:"Proverb: new leaders make big changes."},
  {s:"My keyboard knows my typos better than my vocabulary.", m:"Humor: autocorrect learns our mistakes."},
  {s:"Glass is made mostly from sand.", m:"True: heated sand becomes the glass in your windows."},
  {s:"Could we split the bill? I had the salad and the soup.", m:"Dining: suggest sharing costs fairly."},
  {s:"The proof of the pudding is in the eating — try the method yourself before judging it.", m:"Proverb: test something to judge it fairly."},
  {s:"Invest in skills — markets crash, but ability compounds forever.", m:"Motivation: learning is the safest investment."},
  {s:"Bananas are slightly radioactive.", m:"True: they contain potassium-40; you'd need millions at once for harm."},
  {s:"The remote control always hides when the show gets good.", m:"Humor: small annoyances, big frustration."},
  {s:"All's well that ends well: the lost luggage arrived before the wedding.", m:"Proverb: a good ending excuses earlier trouble."},
  {s:"Better safe than sorry — she backed up her files before the update.", m:"Proverb: caution is wiser than regret."},
  {s:"The coldest temperature ever recorded on Earth was minus 89.2 degrees Celsius in Antarctica.", m:"True: measured at Vostok Station in 1983."},
  {s:"Mondays should come with a snooze button.", m:"Humor: everyone dreads Mondays."},
  {s:"The mountain looks smaller from the top; every step changes the view.", m:"Motivation: progress changes perspective."},
  {s:"Haste makes waste: rushing the paint job meant doing it twice.", m:"Proverb: hurrying causes mistakes."},
  {s:"The word google came from googol, the number 1 followed by 100 zeros.", m:"True: the founders wanted a name meaning huge amounts of information."},
  {s:"I'm afraid we're fully booked this weekend, but next Friday is open.", m:"Service: decline yet offer an alternative."},
  {s:"I trust my GPS, but I still study the map like a co-pilot.", m:"Humor: old habits persist."},
  {s:"Once bitten, twice shy — after one bad landlord, she reads every lease twice.", m:"Proverb: a bad experience makes you cautious."},
  {s:"The Statue of Liberty was a gift from France.", m:"True: it arrived in New York in 1886."},
  {s:"Forgive yourself for the slow days; even rivers pause in deep pools.", m:"Motivation: rest is part of flow."},
  {s:"Third time's the charm: she passed the driving test on her third try.", m:"Idiom: the third attempt often succeeds."},
  {s:"The clearance rack is where hope and budgets negotiate.", m:"Humor: bargain-hunting psychology."},
  {s:"The first email was sent in 1971.", m:"True: engineer Ray Tomlinson sent it to himself as a test."},
  {s:"Thank you for your understanding during this busy period.", m:"Professional: acknowledge someone's patience."},
  {s:"Keep your chin up — one rejection letter is not the end of the story.", m:"Idiom: stay positive during difficulty."},
  {s:"Show up especially when you don't feel like it — that's when it counts most.", m:"Motivation: discipline on hard days."},
  {s:"Shakespeare invented words we still use, including eyeball and fashionable.", m:"True: he coined over a thousand English words."},
  {s:"My inbox has 3,000 unread emails, and I've made peace with that.", m:"Humor: email overload is normal now."},
  {s:"Keep your eyes on the prize and the boring drills become bearable.", m:"Idiom: stay focused on your goal."},
  {s:"Read between the lines of his polite email: he's not happy with the delay.", m:"Idiom: understand the hidden meaning."},
  {s:"In medieval times, a moment was a real unit of time — about 90 seconds.", m:"True: an hour was divided into 40 moments."},
  {s:"The best ideas arrive in the shower, where notebooks fear to go.", m:"Humor: inspiration strikes inconveniently."},
  {s:"A calm mind solves in an hour what a worried mind can't solve in a day.", m:"Motivation: composure improves thinking."},
  {s:"Take online reviews with a grain of salt — some are written by competitors.", m:"Idiom: don't accept something as completely true."},
  {s:"Astronauts struggle to burp in space.", m:"True: without gravity, gas doesn't separate from liquid in the stomach."},
  {s:"Let's put our heads together and find a workaround.", m:"Teamwork: propose collaborative problem-solving."},
  {s:"One more episode is the official lie of streaming services.", m:"Humor: binge-watching traps us."},
  {s:"The missed deadline was just the tip of the iceberg; the whole project was behind.", m:"Idiom: a small visible part of a bigger problem."},
  {s:"The Great Wall of China was partly held together with sticky rice.", m:"True: rice mortar made it stronger than plain mortar."},
  {s:"Build the habit first; motivation will move in later.", m:"Motivation: action creates drive."},
  {s:"Finding an affordable dentist in this city is like looking for a needle in a haystack.", m:"Idiom: extremely difficult to find."},
  {s:"My house has 200 channels and nothing worth watching — the modern paradox.", m:"Humor: choice doesn't equal quality."},
  {s:"The longest word in major English dictionaries has 45 letters.", m:"True: it names a lung disease caused by volcanic dust."},
  {s:"I'd prefer to pay by card, if that's all right.", m:"Shopping: state a payment preference."},
  {s:"The design flopped, so it's back to the drawing board.", m:"Idiom: start over after a failure."},
  {s:"Your story isn't finished — today's hard chapter isn't the ending.", m:"Motivation: keep going."},
  {s:"There are more possible chess games than atoms in the observable universe.", m:"True: the Shannon number is about 10 to the 120th power."},
  {s:"The vending machine ate my dollar, and now we have a personal conflict.", m:"Humor: machines test our patience."},
  {s:"After twelve hours of moving boxes, they called it a day.", m:"Idiom: to stop working for the day."},
  {s:"Exhausted from the trip, she hit the sack at eight in the evening.", m:"Idiom: to go to bed."},
  {s:"Cows form close friendships and get stressed when separated.", m:"True: research shows they even have best friends."},
  {s:"Winter is nature's way of asking if you really needed to go outside.", m:"Humor: cold weather keeps us home."},
  {s:"Help someone climb, and you'll find your own footing surer.", m:"Motivation: helping others strengthens you."},
  {s:"He got cold feet the night before the wedding and called his best friend at midnight.", m:"Idiom: to become too nervous to do something."},
  {s:"The inventor of the microwave oven got the idea from a melted chocolate bar.", m:"True: Percy Spencer noticed it near radar equipment in 1945."},
  {s:"Could you hold that thought while I grab a pen?", m:"Conversation: pause politely to take notes."},
  {s:"My calendar is full of meetings that could have been emails.", m:"Humor: meetings multiply unnecessarily."},
  {s:"Before her first presentation, she had butterflies in her stomach.", m:"Idiom: to feel nervous."},
  {s:"Your body produces about 25 million new cells every second.", m:"True: most are blood cells made in your bone marrow."},
  {s:"The expert in anything was once confused by everything.", m:"Motivation: confusion precedes clarity."},
  {s:"As the only engineer at the art retreat, he felt like a fish out of water.", m:"Idiom: uncomfortable in unfamiliar surroundings."},
  {s:"The doorbell rings only when I'm in the shower — physics, probably.", m:"Humor: timing is cruelly perfect."},
  {s:"The human eye can distinguish about 10 million different colors.", m:"True: yet most languages name only a handful."},
  {s:"I'm running about ten minutes behind — please start without me.", m:"Professional: warn of lateness."},
  {s:"Her promotion stole his thunder, though he pretended not to mind.", m:"Idiom: to take attention away from someone."},
  {s:"Choose the harder right over the easier wrong — character compounds too.", m:"Motivation: integrity builds over time."},
  {s:"Raindrops can fall at 22 kilometers per hour.", m:"True: larger drops fall faster than drizzle."},
  {s:"I watered my plastic plant for six months before noticing.", m:"Humor: we run on autopilot."},
  {s:"Don't rain on her parade — let her enjoy the acceptance letter first.", m:"Idiom: don't spoil someone's happiness."},
  {s:"After three failed attempts, he threw in the towel and hired a professional.", m:"Idiom: to give up."},
  {s:"The Pacific Ocean is wider than the Moon.", m:"True: about 19,800 km across versus the Moon's 3,474 km diameter."},
  {s:"Reply all should require a license and a background check.", m:"Humor: email mistakes are public."},
  {s:"Time spent learning is never wasted; it waits quietly until you need it.", m:"Motivation: knowledge keeps."},
  {s:"Everyone is jumping on the bandwagon now, but she was recycling years ago.", m:"Idiom: to join something because it's popular."},
  {s:"A single cloud can weigh as much as 100 elephants.", m:"True: it floats because the weight spreads over a huge volume."},
  {s:"It was a pleasure meeting you — let's stay in touch.", m:"Networking: close a first meeting warmly."},
  {s:"The scale and I have different definitions of a little.", m:"Humor: we negotiate with ourselves."},
  {s:"Cut to the chase: are we getting the refund or not?", m:"Idiom: get to the point directly."},
  {s:"Your body contains enough carbon to make about 9,000 pencils.", m:"True: the classic estimate counts the carbon in an average adult."},
  {s:"Begin before you feel ready — readiness is a rumor.", m:"Motivation: start now."},
  {s:"Let's get the ball rolling on the move — I'll rent the truck today.", m:"Idiom: to start an activity."},
  {s:"The low-battery warning appears exactly when the map matters most.", m:"Humor: phones die at critical moments."},
  {s:"The Great Barrier Reef is the largest living structure on Earth.", m:"True: it is visible from space and built by billions of coral polyps."},
  {s:"Would you mind repeating that a bit more slowly?", m:"Learning: ask someone to slow down."},
  {s:"You're putting the cart before the horse by buying furniture for an apartment you haven't rented.", m:"Idiom: doing things in the wrong order."},
  {s:"One honest hour of work beats three distracted ones.", m:"Motivation: focus multiplies effort."},
  {s:"Dragonflies see in nearly every direction at once.", m:"True: their huge eyes give them almost 360-degree vision."},
  {s:"My dog judges my cooking, then eats the evidence.", m:"Humor: dogs are honest critics."},
  {s:"Don't rock the boat during your first week — observe and learn first.", m:"Idiom: don't cause trouble in a new situation."},
  {s:"Once the visa arrived, it was smooth sailing to the departure date.", m:"Idiom: easy progress without problems."},
  {s:"The average driver spends about six months of life waiting at red lights.", m:"Estimate: traffic studies put the lifetime total near half a year."},
  {s:"Decluttering videos are the only clutter I willingly collect.", m:"Humor: we watch organizing instead of doing it."},
  {s:"The door you fear to open often leads to the room where you belong.", m:"Motivation: face the fear."},
  {s:"It took him a month to learn the ropes at the warehouse.", m:"Idiom: to learn how to do a job."}
];
(function(){
  var wOff = 0, sOff = 0;
  function dayOfYear(d){var s=new Date(d.getFullYear(),0,0);return Math.floor((d-s)/864e5);}
  function idx(off,n){var i=(dayOfYear(new Date())+off)%n;return i<0?i+n:i;}
  function fmtDate(off){var d=new Date();d.setDate(d.getDate()+off);
    return d.toLocaleDateString('en-US',{month:'short',day:'numeric'});}
  function speak(t){try{if('speechSynthesis' in window){speechSynthesis.cancel();
    speechSynthesis.speak(new SpeechSynthesisUtterance(t));}}catch(e){}}
  function render(){
    var w=WORDS[idx(wOff,WORDS.length)];
    document.getElementById('dw-word').textContent=w.w;
    document.getElementById('dw-meta').textContent=w.pos+'  '+w.ipa;
    document.getElementById('dw-def').textContent=w.def;
    document.getElementById('dw-ex').textContent='“'+w.ex+'”';
    document.getElementById('dw-date').textContent=fmtDate(wOff);
    var s=SENTENCES[idx(sOff,SENTENCES.length)];
    document.getElementById('ds-text').textContent='“'+s.s+'”';
    document.getElementById('ds-meaning').textContent=s.m;
    document.getElementById('ds-date').textContent=fmtDate(sOff);
  }
  document.getElementById('dw-prev').addEventListener('click',function(){wOff--;render();});
  document.getElementById('dw-next').addEventListener('click',function(){wOff++;render();});
  document.getElementById('ds-prev').addEventListener('click',function(){sOff--;render();});
  document.getElementById('ds-next').addEventListener('click',function(){sOff++;render();});
  document.getElementById('dw-speak').addEventListener('click',function(){
    var w=WORDS[idx(wOff,WORDS.length)];speak(w.w+'. '+w.def+' '+w.ex);});
  document.getElementById('ds-speak').addEventListener('click',function(){
    var s=SENTENCES[idx(sOff,SENTENCES.length)];speak(s.s);});
  render();
})();
