/* Daily word & sentence data for the ESLnote homepage. Rotates by day of year.
   Level: intermediate to advanced. */
var WORDS = [
  {w:"accomplish", pos:"verb", ipa:"/əˈkɑːmplɪʃ/", def:"To succeed in doing something.", ex:"She accomplished her goal in six months."},
  {w:"accurate", pos:"adjective", ipa:"/ˈækjərət/", def:"Correct; exact.", ex:"Please give me an accurate address."},
  {w:"adapt", pos:"verb", ipa:"/əˈdæpt/", def:"To change to fit a new situation.", ex:"It took months to adapt to the new job."},
  {w:"adequate", pos:"adjective", ipa:"/ˈædɪkwət/", def:"Enough; satisfactory.", ex:"His English is adequate for the job."},
  {w:"adjust", pos:"verb", ipa:"/əˈdʒʌst/", def:"To change slightly.", ex:"I need to adjust my schedule."},
  {w:"admire", pos:"verb", ipa:"/ədˈmaɪər/", def:"To respect and like.", ex:"I admire her dedication."},
  {w:"adopt", pos:"verb", ipa:"/əˈdɑːpt/", def:"To take and use as your own.", ex:"We adopted a new policy."},
  {w:"advance", pos:"verb", ipa:"/ədˈvæns/", def:"To move forward.", ex:"The treatment advanced quickly."},
  {w:"advise", pos:"verb", ipa:"/ədˈvaɪz/", def:"To give advice.", ex:"I advise you to rest."},
  {w:"advocate", pos:"verb", ipa:"/ˈædvəkeɪt/", def:"To support publicly.", ex:"She advocates for better schools."},
  {w:"affect", pos:"verb", ipa:"/əˈfekt/", def:"To influence.", ex:"The delay affected our plans."},
  {w:"agenda", pos:"noun", ipa:"/əˈdʒendə/", def:"A list of things to discuss.", ex:"What's on today's agenda?"},
  {w:"allocate", pos:"verb", ipa:"/ˈæləkeɪt/", def:"To set aside for a purpose.", ex:"We allocated $500 for repairs."},
  {w:"ambitious", pos:"adjective", ipa:"/æmˈbɪʃəs/", def:"Wanting success badly.", ex:"She has ambitious career goals."},
  {w:"amend", pos:"verb", ipa:"/əˈmend/", def:"To change; to improve.", ex:"They amended the contract."},
  {w:"ample", pos:"adjective", ipa:"/ˈæmpəl/", def:"More than enough.", ex:"We have ample time."},
  {w:"analyze", pos:"verb", ipa:"/ˈænəlaɪz/", def:"To study carefully.", ex:"We need to analyze the data."},
  {w:"annual", pos:"adjective", ipa:"/ˈænjuəl/", def:"Happening once a year.", ex:"Our annual checkup is in June."},
  {w:"anticipate", pos:"verb", ipa:"/ænˈtɪsɪpeɪt/", def:"To expect.", ex:"We anticipate a busy weekend."},
  {w:"anxious", pos:"adjective", ipa:"/ˈæŋkʃəs/", def:"Worried; eager.", ex:"She felt anxious before the test."},
  {w:"appeal", pos:"verb", ipa:"/əˈpiːl/", def:"To make a serious request.", ex:"He appealed for help."},
  {w:"appoint", pos:"verb", ipa:"/əˈpɔɪnt/", def:"To choose for a job.", ex:"They appointed a new manager."},
  {w:"appreciate", pos:"verb", ipa:"/əˈpriːʃieɪt/", def:"To be grateful for.", ex:"I appreciate your help."},
  {w:"appropriate", pos:"adjective", ipa:"/əˈproʊpriət/", def:"Suitable.", ex:"Wear appropriate shoes for hiking."},
  {w:"approve", pos:"verb", ipa:"/əˈpruːv/", def:"To agree officially.", ex:"The bank approved our loan."},
  {w:"arise", pos:"verb", ipa:"/əˈraɪz/", def:"To come up; to happen.", ex:"Problems arose during the move."},
  {w:"aspect", pos:"noun", ipa:"/ˈæspekt/", def:"One part of something.", ex:"We discussed every aspect."},
  {w:"aspire", pos:"verb", ipa:"/əˈspaɪər/", def:"To want strongly.", ex:"She aspires to be a nurse."},
  {w:"assemble", pos:"verb", ipa:"/əˈsembəl/", def:"To put together; to gather.", ex:"We assembled the furniture."},
  {w:"assert", pos:"verb", ipa:"/əˈsɜːrt/", def:"To state firmly.", ex:"He asserted his innocence."},
  {w:"assess", pos:"verb", ipa:"/əˈses/", def:"To evaluate.", ex:"The teacher assessed our progress."},
  {w:"asset", pos:"noun", ipa:"/ˈæset/", def:"Something valuable.", ex:"Her experience is a real asset."},
  {w:"assign", pos:"verb", ipa:"/əˈsaɪn/", def:"To give a task.", ex:"The teacher assigned homework."},
  {w:"assist", pos:"verb", ipa:"/əˈsɪst/", def:"To help.", ex:"She assisted the new employee."},
  {w:"assume", pos:"verb", ipa:"/əˈsuːm/", def:"To suppose; to take on.", ex:"Don't assume the worst."},
  {w:"assure", pos:"verb", ipa:"/əˈʃʊr/", def:"To promise; to make certain.", ex:"He assured me it was safe."},
  {w:"attach", pos:"verb", ipa:"/əˈtætʃ/", def:"To join; to include.", ex:"I attached the file to the email."},
  {w:"attain", pos:"verb", ipa:"/əˈteɪn/", def:"To achieve.", ex:"She attained her degree at 40."},
  {w:"attempt", pos:"verb", ipa:"/əˈtempt/", def:"To try.", ex:"He attempted the exam twice."},
  {w:"attend", pos:"verb", ipa:"/əˈtend/", def:"To go to.", ex:"She attends night classes."},
  {w:"attitude", pos:"noun", ipa:"/ˈætɪtuːd/", def:"A way of thinking.", ex:"He has a positive attitude."},
  {w:"attract", pos:"verb", ipa:"/əˈtrækt/", def:"To draw interest.", ex:"The sale attracted crowds."},
  {w:"authentic", pos:"adjective", ipa:"/ɔːˈθentɪk/", def:"Real; genuine.", ex:"This is authentic Italian food."},
  {w:"avert", pos:"verb", ipa:"/əˈvɜːrt/", def:"To prevent.", ex:"Quick action averted a crisis."},
  {w:"avid", pos:"adjective", ipa:"/ˈævɪd/", def:"Very eager.", ex:"He's an avid reader."},
  {w:"await", pos:"verb", ipa:"/əˈweɪt/", def:"To wait for.", ex:"We await your reply."},
  {w:"aware", pos:"adjective", ipa:"/əˈwer/", def:"Knowing.", ex:"Are you aware of the change?"},
  {w:"awkward", pos:"adjective", ipa:"/ˈɔːkwərd/", def:"Uncomfortable; clumsy.", ex:"There was an awkward silence."},
  {w:"ban", pos:"verb", ipa:"/bæn/", def:"To forbid.", ex:"They banned smoking indoors."},
  {w:"bargain", pos:"noun", ipa:"/ˈbɑːrɡən/", def:"A good deal.", ex:"This jacket was a bargain."},
  {w:"barrier", pos:"noun", ipa:"/ˈbæriər/", def:"Something that blocks.", ex:"Language is a barrier for some."},
  {w:"behalf", pos:"noun", ipa:"/bɪˈhæf/", def:"In place of someone.", ex:"She spoke on my behalf."},
  {w:"behave", pos:"verb", ipa:"/bɪˈheɪv/", def:"To act.", ex:"The children behaved well."},
  {w:"belief", pos:"noun", ipa:"/bɪˈliːf/", def:"Something accepted as true.", ex:"His beliefs guide him."},
  {w:"beloved", pos:"adjective", ipa:"/bɪˈlʌvɪd/", def:"Deeply loved.", ex:"She visited her beloved grandmother."},
  {w:"benefit", pos:"noun", ipa:"/ˈbenɪfɪt/", def:"An advantage.", ex:"Exercise has many benefits."},
  {w:"betray", pos:"verb", ipa:"/bɪˈtreɪ/", def:"To be disloyal to.", ex:"He betrayed their trust."},
  {w:"beware", pos:"verb", ipa:"/bɪˈwer/", def:"To be careful.", ex:"Beware of scams."},
  {w:"bias", pos:"noun", ipa:"/ˈbaɪəs/", def:"Unfair preference.", ex:"The test was free of bias."},
  {w:"bizarre", pos:"adjective", ipa:"/bɪˈzɑːr/", def:"Very strange.", ex:"It was a bizarre dream."},
  {w:"blame", pos:"verb", ipa:"/bleɪm/", def:"To say someone is at fault.", ex:"Don't blame yourself."},
  {w:"blend", pos:"verb", ipa:"/blend/", def:"To mix.", ex:"Blend the colors gently."},
  {w:"blunt", pos:"adjective", ipa:"/blʌnt/", def:"Direct; not sharp.", ex:"Let me be blunt: we can't afford it."},
  {w:"boast", pos:"verb", ipa:"/boʊst/", def:"To brag.", ex:"He boasted about his promotion."},
  {w:"bold", pos:"adjective", ipa:"/boʊld/", def:"Brave; striking.", ex:"She made a bold decision."},
  {w:"bond", pos:"noun", ipa:"/bɑːnd/", def:"A close connection.", ex:"They share a strong bond."},
  {w:"bonus", pos:"noun", ipa:"/ˈboʊnəs/", def:"Extra pay or gift.", ex:"We got a holiday bonus."},
  {w:"boost", pos:"verb", ipa:"/buːst/", def:"To increase.", ex:"The win boosted morale."},
  {w:"boundary", pos:"noun", ipa:"/ˈbaʊndri/", def:"A limit.", ex:"Set clear boundaries at work."},
  {w:"breach", pos:"noun", ipa:"/briːtʃ/", def:"A break; a violation.", ex:"It was a breach of trust."},
  {w:"bribe", pos:"noun", ipa:"/braɪb/", def:"Money paid to influence illegally.", ex:"He refused the bribe."},
  {w:"brief", pos:"adjective", ipa:"/briːf/", def:"Short.", ex:"Give me a brief summary."},
  {w:"brisk", pos:"adjective", ipa:"/brɪsk/", def:"Quick; lively.", ex:"We took a brisk walk."},
  {w:"broaden", pos:"verb", ipa:"/ˈbrɔːdən/", def:"To widen.", ex:"Travel broadens the mind."},
  {w:"brochure", pos:"noun", ipa:"/broʊˈʃʊr/", def:"A pamphlet.", ex:"Pick up a brochure at the desk."},
  {w:"bruise", pos:"noun", ipa:"/bruːz/", def:"A dark mark from injury.", ex:"He has a bruise on his arm."},
  {w:"brutal", pos:"adjective", ipa:"/ˈbruːtəl/", def:"Very harsh.", ex:"The winter was brutal."},
  {w:"budget", pos:"noun", ipa:"/ˈbʌdʒɪt/", def:"A spending plan.", ex:"We set a monthly budget."},
  {w:"bulky", pos:"adjective", ipa:"/ˈbʌlki/", def:"Large and heavy.", ex:"The bulky box didn't fit."},
  {w:"burden", pos:"noun", ipa:"/ˈbɜːrdən/", def:"A heavy load.", ex:"Debt is a heavy burden."},
  {w:"bureau", pos:"noun", ipa:"/ˈbjʊroʊ/", def:"An office or agency.", ex:"Contact the travel bureau."},
  {w:"burst", pos:"verb", ipa:"/bɜːrst/", def:"To break open suddenly.", ex:"The pipe burst."},
  {w:"bustling", pos:"adjective", ipa:"/ˈbʌslɪŋ/", def:"Full of activity.", ex:"The market was bustling."},
  {w:"bypass", pos:"verb", ipa:"/ˈbaɪpæs/", def:"To go around.", ex:"We bypassed the traffic jam."},
  {w:"caliber", pos:"noun", ipa:"/ˈkælɪbər/", def:"Quality level.", ex:"We hire people of high caliber."},
  {w:"candid", pos:"adjective", ipa:"/ˈkændɪd/", def:"Honest and direct.", ex:"Let me be candid with you."},
  {w:"capable", pos:"adjective", ipa:"/ˈkeɪpəbəl/", def:"Able to do something.", ex:"She's capable of more."},
  {w:"capacity", pos:"noun", ipa:"/kəˈpæsəti/", def:"Maximum amount; ability.", ex:"The hall was at full capacity."},
  {w:"caption", pos:"noun", ipa:"/ˈkæpʃən/", def:"Text under a picture.", ex:"Read the caption below."},
  {w:"capture", pos:"verb", ipa:"/ˈkæptʃər/", def:"To catch; to record.", ex:"The photo captured the moment."},
  {w:"cargo", pos:"noun", ipa:"/ˈkɑːrɡoʊ/", def:"Goods carried.", ex:"The cargo arrived late."},
  {w:"carve", pos:"verb", ipa:"/kɑːrv/", def:"To cut into shape.", ex:"He carved the turkey."},
  {w:"casual", pos:"adjective", ipa:"/ˈkæʒuəl/", def:"Relaxed; informal.", ex:"The dress code is casual."},
  {w:"caution", pos:"noun", ipa:"/ˈkɔːʃən/", def:"Carefulness.", ex:"Drive with caution."},
  {w:"cease", pos:"verb", ipa:"/siːs/", def:"To stop.", ex:"The rain ceased at noon."},
  {w:"censor", pos:"verb", ipa:"/ˈsensər/", def:"To remove unacceptable parts.", ex:"The scene was censored."},
  {w:"census", pos:"noun", ipa:"/ˈsensəs/", def:"An official population count.", ex:"The census is every ten years."},
  {w:"ceremony", pos:"noun", ipa:"/ˈserəmoʊni/", def:"A formal event.", ex:"The wedding ceremony was lovely."},
  {w:"certify", pos:"verb", ipa:"/ˈsɜːrtɪfaɪ/", def:"To confirm officially.", ex:"She is certified to teach."},
  {w:"chafe", pos:"verb", ipa:"/tʃeɪf/", def:"To irritate by rubbing.", ex:"His shoes chafed his feet."},
  {w:"chaos", pos:"noun", ipa:"/ˈkeɪɑːs/", def:"Total disorder.", ex:"The move was pure chaos."},
  {w:"cherish", pos:"verb", ipa:"/ˈtʃerɪʃ/", def:"To treasure.", ex:"She cherishes those memories."},
  {w:"chronic", pos:"adjective", ipa:"/ˈkrɑːnɪk/", def:"Long-lasting.", ex:"He has chronic back pain."},
  {w:"circulate", pos:"verb", ipa:"/ˈsɜːrkjəleɪt/", def:"To move around; to spread.", ex:"A rumor circulated online."},
  {w:"circumstance", pos:"noun", ipa:"/ˈsɜːrkəmstæns/", def:"A condition or fact.", ex:"Under the circumstances, we left."},
  {w:"cite", pos:"verb", ipa:"/saɪt/", def:"To mention as an example.", ex:"She cited three reasons."},
  {w:"civic", pos:"adjective", ipa:"/ˈsɪvɪk/", def:"Relating to a city or citizens.", ex:"Voting is a civic duty."},
  {w:"clarify", pos:"verb", ipa:"/ˈklærəfaɪ/", def:"To make clear.", ex:"Could you clarify that?"},
  {w:"clash", pos:"verb", ipa:"/klæʃ/", def:"To conflict.", ex:"Our schedules clashed."},
  {w:"classify", pos:"verb", ipa:"/ˈklæsɪfaɪ/", def:"To arrange in groups.", ex:"The files are classified by date."},
  {w:"clause", pos:"noun", ipa:"/klɔːz/", def:"A part of a contract or sentence.", ex:"Read the fine-print clause."},
  {w:"client", pos:"noun", ipa:"/ˈklaɪənt/", def:"A customer.", ex:"She met with a client."},
  {w:"climax", pos:"noun", ipa:"/ˈklaɪmæks/", def:"The most exciting point.", ex:"The movie's climax surprised us."},
  {w:"cling", pos:"verb", ipa:"/klɪŋ/", def:"To hold tightly.", ex:"The child clung to her mother."},
  {w:"clinical", pos:"adjective", ipa:"/ˈklɪnɪkəl/", def:"Medical; cold and plain.", ex:"The room looked clinical."},
  {w:"clip", pos:"verb", ipa:"/klɪp/", def:"To cut; to attach.", ex:"Clip the coupon from the paper."},
  {w:"clique", pos:"noun", ipa:"/kliːk/", def:"An exclusive group.", ex:"She never joined a clique."},
  {w:"coarse", pos:"adjective", ipa:"/kɔːrs/", def:"Rough.", ex:"The coarse fabric scratched."},
  {w:"coax", pos:"verb", ipa:"/koʊks/", def:"To persuade gently.", ex:"She coaxed him to try."},
  {w:"coherent", pos:"adjective", ipa:"/koʊˈhɪrənt/", def:"Clear and logical.", ex:"Write a coherent essay."},
  {w:"coincide", pos:"verb", ipa:"/ˌkoʊɪnˈsaɪd/", def:"To happen at the same time.", ex:"The events coincided."},
  {w:"collaborate", pos:"verb", ipa:"/kəˈlæbəreɪt/", def:"To work together.", ex:"We collaborated on the project."},
  {w:"collapse", pos:"verb", ipa:"/kəˈlæps/", def:"To fall down.", ex:"He collapsed from exhaustion."},
  {w:"colleague", pos:"noun", ipa:"/ˈkɑːliːɡ/", def:"A coworker.", ex:"My colleague helped me."},
  {w:"collide", pos:"verb", ipa:"/kəˈlaɪd/", def:"To crash into.", ex:"The cars collided."},
  {w:"comical", pos:"adjective", ipa:"/ˈkɑːmɪkəl/", def:"Funny.", ex:"It was a comical misunderstanding."},
  {w:"commence", pos:"verb", ipa:"/kəˈmens/", def:"To begin.", ex:"The ceremony will commence at noon."},
  {w:"commend", pos:"verb", ipa:"/kəˈmend/", def:"To praise.", ex:"The boss commended her work."},
  {w:"commodity", pos:"noun", ipa:"/kəˈmɑːdəti/", def:"A product bought and sold.", ex:"Rice is a basic commodity."},
  {w:"commonplace", pos:"adjective", ipa:"/ˈkɑːmənpleɪs/", def:"Ordinary.", ex:"Traffic jams are commonplace here."},
  {w:"communal", pos:"adjective", ipa:"/kəˈmjuːnəl/", def:"Shared by a group.", ex:"We share a communal kitchen."},
  {w:"commute", pos:"verb", ipa:"/kəˈmjuːt/", def:"To travel to work.", ex:"She commutes by train."},
  {w:"compact", pos:"adjective", ipa:"/kəmˈpækt/", def:"Small and dense.", ex:"It's a compact car."},
  {w:"compel", pos:"verb", ipa:"/kəmˈpel/", def:"To force.", ex:"The evidence compelled him to confess."},
  {w:"compensate", pos:"verb", ipa:"/ˈkɑːmpənseɪt/", def:"To pay; to make up for.", ex:"They compensated us for the delay."},
  {w:"compete", pos:"verb", ipa:"/kəmˈpiːt/", def:"To try to win.", ex:"Our team competes every spring."},
  {w:"competent", pos:"adjective", ipa:"/ˈkɑːmpɪtənt/", def:"Capable.", ex:"She's a competent driver."},
  {w:"compile", pos:"verb", ipa:"/kəmˈpaɪl/", def:"To gather together.", ex:"He compiled a list."},
  {w:"complacent", pos:"adjective", ipa:"/kəmˈpleɪsənt/", def:"Too satisfied to improve.", ex:"Don't get complacent."},
  {w:"complement", pos:"noun", ipa:"/ˈkɑːmplɪmənt/", def:"Something that completes.", ex:"The sauce is a perfect complement."},
  {w:"complex", pos:"adjective", ipa:"/kəmˈpleks/", def:"Complicated.", ex:"It's a complex issue."},
  {w:"complicate", pos:"verb", ipa:"/ˈkɑːmplɪkeɪt/", def:"To make difficult.", ex:"Don't complicate things."},
  {w:"comply", pos:"verb", ipa:"/kəmˈplaɪ/", def:"To follow rules.", ex:"You must comply with the policy."},
  {w:"compose", pos:"verb", ipa:"/kəmˈpoʊz/", def:"To write; to make up.", ex:"She composed a letter."},
  {w:"compound", pos:"noun", ipa:"/ˈkɑːmpaʊnd/", def:"A mixture.", ex:"The medicine is a compound."},
  {w:"comprehend", pos:"verb", ipa:"/ˌkɑːmprɪˈhend/", def:"To understand.", ex:"I couldn't comprehend the lecture."},
  {w:"compress", pos:"verb", ipa:"/kəmˈpres/", def:"To squeeze.", ex:"Compress the files before sending."},
  {w:"comprise", pos:"verb", ipa:"/kəmˈpraɪz/", def:"To consist of.", ex:"The team comprises ten people."},
  {w:"compromise", pos:"noun", ipa:"/ˈkɑːmprəmaɪz/", def:"A mutual agreement.", ex:"We reached a compromise."},
  {w:"concede", pos:"verb", ipa:"/kənˈsiːd/", def:"To admit.", ex:"He conceded the election."},
  {w:"conceive", pos:"verb", ipa:"/kənˈsiːv/", def:"To imagine; to think of.", ex:"She conceived the idea last year."},
  {w:"concentrate", pos:"verb", ipa:"/ˈkɑːnsəntreɪt/", def:"To focus.", ex:"I can't concentrate with noise."},
  {w:"concept", pos:"noun", ipa:"/ˈkɑːnsept/", def:"An idea.", ex:"It's a simple concept."},
  {w:"concern", pos:"noun", ipa:"/kənˈsɜːrn/", def:"Worry.", ex:"Safety is our main concern."},
  {w:"concise", pos:"adjective", ipa:"/kənˈsaɪs/", def:"Brief and clear.", ex:"Keep your answers concise."},
  {w:"conclude", pos:"verb", ipa:"/kənˈkluːd/", def:"To finish; to decide.", ex:"We concluded the meeting at five."},
  {w:"concrete", pos:"adjective", ipa:"/kɑːnˈkriːt/", def:"Specific; real.", ex:"Give me a concrete example."},
  {w:"concur", pos:"verb", ipa:"/kənˈkɜːr/", def:"To agree.", ex:"I concur with your decision."},
  {w:"condemn", pos:"verb", ipa:"/kənˈdem/", def:"To criticize strongly.", ex:"Leaders condemned the attack."},
  {w:"condense", pos:"verb", ipa:"/kənˈdens/", def:"To shorten.", ex:"Condense the report to one page."},
  {w:"condone", pos:"verb", ipa:"/kənˈdoʊn/", def:"To accept wrongdoing.", ex:"We don't condone cheating."},
  {w:"conducive", pos:"adjective", ipa:"/kənˈduːsɪv/", def:"Helping something happen.", ex:"Quiet rooms are conducive to study."},
  {w:"confer", pos:"verb", ipa:"/kənˈfɜːr/", def:"To discuss; to grant.", ex:"They conferred for an hour."},
  {w:"confess", pos:"verb", ipa:"/kənˈfes/", def:"To admit.", ex:"She confessed her mistake."},
  {w:"confide", pos:"verb", ipa:"/kənˈfaɪd/", def:"To share a secret.", ex:"She confided in her friend."},
  {w:"confine", pos:"verb", ipa:"/kənˈfaɪn/", def:"To limit.", ex:"Please confine your remarks to the topic."},
  {w:"confirm", pos:"verb", ipa:"/kənˈfɜːrm/", def:"To verify.", ex:"Please confirm your appointment."},
  {w:"confiscate", pos:"verb", ipa:"/ˈkɑːnfɪskeɪt/", def:"To take away officially.", ex:"They confiscated his phone."},
  {w:"conflict", pos:"noun", ipa:"/ˈkɑːnflɪkt/", def:"A disagreement.", ex:"We resolved the conflict."},
  {w:"conform", pos:"verb", ipa:"/kənˈfɔːrm/", def:"To follow the norm.", ex:"She refused to conform."},
  {w:"confront", pos:"verb", ipa:"/kənˈfrʌnt/", def:"To face.", ex:"He confronted the problem directly."},
  {w:"confuse", pos:"verb", ipa:"/kənˈfjuːz/", def:"To make unclear.", ex:"The map confused me."},
  {w:"congenial", pos:"adjective", ipa:"/kənˈdʒiːniəl/", def:"Pleasant.", ex:"We had a congenial dinner."},
  {w:"congested", pos:"adjective", ipa:"/kənˈdʒestɪd/", def:"Overcrowded.", ex:"The roads were congested."},
  {w:"congratulate", pos:"verb", ipa:"/kənˈɡrætʃəleɪt/", def:"To praise for success.", ex:"We congratulated the graduate."},
  {w:"congregate", pos:"verb", ipa:"/ˈkɑːŋɡrɪɡeɪt/", def:"To gather.", ex:"Fans congregated outside."},
  {w:"conquer", pos:"verb", ipa:"/ˈkɑːŋkər/", def:"To overcome.", ex:"She conquered her fear."},
  {w:"conscience", pos:"noun", ipa:"/ˈkɑːnʃəns/", def:"Moral sense.", ex:"His conscience bothered him."},
  {w:"conscientious", pos:"adjective", ipa:"/ˌkɑːnʃiˈenʃəs/", def:"Careful and responsible.", ex:"She's a conscientious worker."},
  {w:"conscious", pos:"adjective", ipa:"/ˈkɑːnʃəs/", def:"Awake; aware.", ex:"He was conscious during surgery."},
  {w:"consensus", pos:"noun", ipa:"/kənˈsensəs/", def:"General agreement.", ex:"We reached a consensus."},
  {w:"consent", pos:"verb", ipa:"/kənˈsent/", def:"To agree.", ex:"She consented to the treatment."},
  {w:"consequence", pos:"noun", ipa:"/ˈkɑːnsɪkwens/", def:"A result.", ex:"Think about the consequences."},
  {w:"conserve", pos:"verb", ipa:"/kənˈsɜːrv/", def:"To save.", ex:"We must conserve water."},
  {w:"considerable", pos:"adjective", ipa:"/kənˈsɪdərəbəl/", def:"Large.", ex:"It was a considerable amount."},
  {w:"considerate", pos:"adjective", ipa:"/kənˈsɪdərət/", def:"Thoughtful of others.", ex:"It was considerate of you."},
  {w:"consist", pos:"verb", ipa:"/kənˈsɪst/", def:"To be made up of.", ex:"The class consists of adults."},
  {w:"console", pos:"verb", ipa:"/kənˈsoʊl/", def:"To comfort.", ex:"She consoled the crying child."},
  {w:"consolidate", pos:"verb", ipa:"/kənˈsɑːlɪdeɪt/", def:"To combine.", ex:"We consolidated our debts."},
  {w:"conspicuous", pos:"adjective", ipa:"/kənˈspɪkjuəs/", def:"Very noticeable.", ex:"Her red coat was conspicuous."},
  {w:"conspire", pos:"verb", ipa:"/kənˈspaɪər/", def:"To plot secretly.", ex:"They conspired against him."},
  {w:"constant", pos:"adjective", ipa:"/ˈkɑːnstənt/", def:"Unchanging.", ex:"The noise was constant."},
  {w:"constrain", pos:"verb", ipa:"/kənˈstreɪn/", def:"To limit.", ex:"The budget constrains us."},
  {w:"construct", pos:"verb", ipa:"/kənˈstrʌkt/", def:"To build.", ex:"They constructed a new school."},
  {w:"consult", pos:"verb", ipa:"/kənˈsʌlt/", def:"To seek advice.", ex:"Consult a doctor."},
  {w:"consume", pos:"verb", ipa:"/kənˈsuːm/", def:"To use up.", ex:"The fire consumed the house."},
  {w:"contact", pos:"noun", ipa:"/ˈkɑːntækt/", def:"Communication.", ex:"We lost contact."},
  {w:"contagious", pos:"adjective", ipa:"/kənˈteɪdʒəs/", def:"Spreading easily.", ex:"Laughter is contagious."},
  {w:"contain", pos:"verb", ipa:"/kənˈteɪn/", def:"To hold; to control.", ex:"The box contains books."},
  {w:"contaminate", pos:"verb", ipa:"/kənˈtæmɪneɪt/", def:"To pollute.", ex:"The water was contaminated."},
  {w:"contemplate", pos:"verb", ipa:"/ˈkɑːntəmpleɪt/", def:"To think deeply.", ex:"She contemplated quitting."},
  {w:"contemporary", pos:"adjective", ipa:"/kənˈtempəreri/", def:"Modern.", ex:"I like contemporary art."},
  {w:"contempt", pos:"noun", ipa:"/kənˈtempt/", def:"Lack of respect.", ex:"He felt contempt for liars."},
  {w:"contend", pos:"verb", ipa:"/kənˈtend/", def:"To compete; to claim.", ex:"She contends the decision was unfair."},
  {w:"content", pos:"adjective", ipa:"/kənˈtent/", def:"Satisfied.", ex:"He's content with his life."},
  {w:"contest", pos:"noun", ipa:"/ˈkɑːntest/", def:"A competition.", ex:"She won the contest."},
  {w:"context", pos:"noun", ipa:"/ˈkɑːntekst/", def:"Surrounding situation.", ex:"Read it in context."},
  {w:"contingent", pos:"adjective", ipa:"/kənˈtɪndʒənt/", def:"Depending on.", ex:"Our plans are contingent on weather."},
  {w:"continual", pos:"adjective", ipa:"/kənˈtɪnjuəl/", def:"Repeated.", ex:"The continual noise annoyed us."},
  {w:"contort", pos:"verb", ipa:"/kənˈtɔːrt/", def:"To twist.", ex:"She contorted her face."},
  {w:"contract", pos:"noun", ipa:"/ˈkɑːntrækt/", def:"A legal agreement.", ex:"We signed the contract."},
  {w:"contradict", pos:"verb", ipa:"/ˌkɑːntrəˈdɪkt/", def:"To say the opposite.", ex:"Don't contradict your boss."},
  {w:"contrary", pos:"adjective", ipa:"/ˈkɑːntreri/", def:"Opposite.", ex:"Contrary to rumors, we're open."},
  {w:"contrast", pos:"noun", ipa:"/ˈkɑːntræst/", def:"A clear difference.", ex:"The contrast is striking."},
  {w:"contribute", pos:"verb", ipa:"/kənˈtrɪbjuːt/", def:"To give.", ex:"Everyone contributed ideas."},
  {w:"contrive", pos:"verb", ipa:"/kənˈtraɪv/", def:"To plan cleverly.", ex:"She contrived an excuse."},
  {w:"controversial", pos:"adjective", ipa:"/ˌkɑːntrəˈvɜːrʃəl/", def:"Causing disagreement.", ex:"It's a controversial topic."},
  {w:"convene", pos:"verb", ipa:"/kənˈviːn/", def:"To gather.", ex:"The board convened at noon."},
  {w:"convenient", pos:"adjective", ipa:"/kənˈviːniənt/", def:"Easy and useful.", ex:"It's convenient for me."},
  {w:"converge", pos:"verb", ipa:"/kənˈvɜːrdʒ/", def:"To come together.", ex:"The roads converge here."},
  {w:"converse", pos:"verb", ipa:"/kənˈvɜːrs/", def:"To talk.", ex:"We conversed for hours."},
  {w:"convert", pos:"verb", ipa:"/kənˈvɜːrt/", def:"To change.", ex:"We converted the garage."},
  {w:"convey", pos:"verb", ipa:"/kənˈveɪ/", def:"To communicate.", ex:"Please convey my thanks."},
  {w:"convict", pos:"verb", ipa:"/kənˈvɪkt/", def:"To find guilty.", ex:"He was convicted of theft."},
  {w:"convince", pos:"verb", ipa:"/kənˈvɪns/", def:"To persuade.", ex:"She convinced me to join."},
  {w:"convoluted", pos:"adjective", ipa:"/ˌkɑːnvəˈluːtɪd/", def:"Very complex.", ex:"The plot was convoluted."},
  {w:"cooperate", pos:"verb", ipa:"/koʊˈɑːpəreɪt/", def:"To work together.", ex:"Please cooperate with staff."},
  {w:"coordinate", pos:"verb", ipa:"/koʊˈɔːrdɪneɪt/", def:"To organize.", ex:"She coordinated the event."},
  {w:"cordial", pos:"adjective", ipa:"/ˈkɔːrdʒəl/", def:"Warm and friendly.", ex:"We had a cordial meeting."},
  {w:"core", pos:"noun", ipa:"/kɔːr/", def:"The central part.", ex:"Honesty is her core value."},
  {w:"corporate", pos:"adjective", ipa:"/ˈkɔːrpərət/", def:"Business-related.", ex:"She works in corporate law."},
  {w:"correlate", pos:"verb", ipa:"/ˈkɔːrəleɪt/", def:"To be related.", ex:"Stress correlates with illness."},
  {w:"correspond", pos:"verb", ipa:"/ˌkɔːrəˈspɑːnd/", def:"To match; to write letters.", ex:"The dates don't correspond."},
  {w:"corroborate", pos:"verb", ipa:"/kəˈrɑːbəreɪt/", def:"To confirm.", ex:"Witnesses corroborated her story."},
  {w:"corrode", pos:"verb", ipa:"/kəˈroʊd/", def:"To eat away.", ex:"Rust corroded the pipe."},
  {w:"corrupt", pos:"adjective", ipa:"/kəˈrʌpt/", def:"Dishonest.", ex:"The official was corrupt."},
  {w:"counsel", pos:"verb", ipa:"/ˈkaʊnsəl/", def:"To advise.", ex:"She counsels students."},
  {w:"counter", pos:"verb", ipa:"/ˈkaʊntər/", def:"To respond against.", ex:"He countered every argument."},
  {w:"counterpart", pos:"noun", ipa:"/ˈkaʊntərpɑːrt/", def:"A matching person.", ex:"I met my French counterpart."},
  {w:"countless", pos:"adjective", ipa:"/ˈkaʊntləs/", def:"Very many.", ex:"We've had countless meetings."},
  {w:"courteous", pos:"adjective", ipa:"/ˈkɜːrtiəs/", def:"Polite.", ex:"The staff was courteous."},
  {w:"crackdown", pos:"noun", ipa:"/ˈkrækdaʊn/", def:"Strong enforcement.", ex:"There's a crackdown on speeding."},
  {w:"cradle", pos:"noun", ipa:"/ˈkreɪdəl/", def:"A baby's bed.", ex:"The baby slept in the cradle."},
  {w:"craft", pos:"noun", ipa:"/kræft/", def:"A skill; a trade.", ex:"She mastered her craft."},
  {w:"cram", pos:"verb", ipa:"/kræm/", def:"To stuff; to study hard.", ex:"He crammed for the test."},
  {w:"cranky", pos:"adjective", ipa:"/ˈkræŋki/", def:"Irritable.", ex:"The baby was cranky."},
  {w:"crash", pos:"verb", ipa:"/kræʃ/", def:"To collide.", ex:"The computer crashed."},
  {w:"crate", pos:"noun", ipa:"/kreɪt/", def:"A wooden box.", ex:"The apples came in a crate."},
  {w:"crave", pos:"verb", ipa:"/kreɪv/", def:"To want strongly.", ex:"She craved chocolate."},
  {w:"crawl", pos:"verb", ipa:"/krɔːl/", def:"To move slowly on hands and knees.", ex:"The baby crawled."},
  {w:"craze", pos:"noun", ipa:"/kreɪz/", def:"A fad.", ex:"The fitness craze spread fast."},
  {w:"creak", pos:"verb", ipa:"/kriːk/", def:"To make a squeaking sound.", ex:"The door creaked."},
  {w:"credible", pos:"adjective", ipa:"/ˈkredəbəl/", def:"Believable.", ex:"She's a credible witness."},
  {w:"credit", pos:"noun", ipa:"/ˈkredɪt/", def:"Praise; a loan system.", ex:"Give credit where it's due."},
  {w:"creep", pos:"verb", ipa:"/kriːp/", def:"To move quietly.", ex:"He crept upstairs."},
  {w:"crest", pos:"noun", ipa:"/krest/", def:"The top.", ex:"We reached the crest of the hill."},
  {w:"crevice", pos:"noun", ipa:"/ˈkrevɪs/", def:"A narrow crack.", ex:"Water seeped into the crevice."},
  {w:"crew", pos:"noun", ipa:"/kruː/", def:"A team of workers.", ex:"The crew finished early."},
  {w:"crisp", pos:"adjective", ipa:"/krɪsp/", def:"Fresh and firm.", ex:"The air was crisp."},
  {w:"criteria", pos:"noun", ipa:"/kraɪˈtɪriə/", def:"Standards.", ex:"We judged by clear criteria."},
  {w:"critic", pos:"noun", ipa:"/ˈkrɪtɪk/", def:"One who judges.", ex:"The critic praised the film."},
  {w:"critique", pos:"noun", ipa:"/krɪˈtiːk/", def:"An evaluation.", ex:"She gave a fair critique."},
  {w:"crook", pos:"noun", ipa:"/krʊk/", def:"A criminal.", ex:"The crook was arrested."},
  {w:"cross", pos:"adjective", ipa:"/krɔːs/", def:"Angry.", ex:"She was cross with me."},
  {w:"crouch", pos:"verb", ipa:"/kraʊtʃ/", def:"To bend low.", ex:"He crouched behind the wall."},
  {w:"crucial", pos:"adjective", ipa:"/ˈkruːʃəl/", def:"Very important.", ex:"This is a crucial decision."},
  {w:"crude", pos:"adjective", ipa:"/kruːd/", def:"Rough; rude.", ex:"It was a crude joke."},
  {w:"cruise", pos:"verb", ipa:"/kruːz/", def:"To travel smoothly.", ex:"We cruised along the coast."},
  {w:"crumble", pos:"verb", ipa:"/ˈkrʌmbəl/", def:"To break apart.", ex:"The cookie crumbled."},
  {w:"crumple", pos:"verb", ipa:"/ˈkrʌmpəl/", def:"To crush.", ex:"He crumpled the paper."},
  {w:"crunch", pos:"verb", ipa:"/krʌntʃ/", def:"To crush noisily.", ex:"She crunched the numbers."},
  {w:"crusade", pos:"noun", ipa:"/kruːˈseɪd/", def:"A campaign.", ex:"She led a crusade for literacy."},
  {w:"crush", pos:"verb", ipa:"/krʌʃ/", def:"To press hard.", ex:"Don't crush the box."},
  {w:"crust", pos:"noun", ipa:"/krʌst/", def:"Hard outer layer.", ex:"He ate the bread crust."},
  {w:"crux", pos:"noun", ipa:"/krʌks/", def:"The main point.", ex:"That's the crux of the matter."},
  {w:"cue", pos:"noun", ipa:"/kjuː/", def:"A signal.", ex:"That's my cue to leave."},
  {w:"culinary", pos:"adjective", ipa:"/ˈkʌlɪneri/", def:"Related to cooking.", ex:"She took culinary classes."},
  {w:"culminate", pos:"verb", ipa:"/ˈkʌlmɪneɪt/", def:"To reach the highest point.", ex:"The festival culminated in fireworks."},
  {w:"culpable", pos:"adjective", ipa:"/ˈkʌlpəbəl/", def:"Deserving blame.", ex:"He was culpable for the error."},
  {w:"cultivate", pos:"verb", ipa:"/ˈkʌltɪveɪt/", def:"To grow; to develop.", ex:"She cultivated friendships."},
  {w:"cunning", pos:"adjective", ipa:"/ˈkʌnɪŋ/", def:"Clever in a tricky way.", ex:"It was a cunning plan."},
  {w:"curb", pos:"verb", ipa:"/kɜːrb/", def:"To control.", ex:"We must curb spending."},
  {w:"curfew", pos:"noun", ipa:"/ˈkɜːrfjuː/", def:"A time limit.", ex:"The teen has a 10 p.m. curfew."},
  {w:"curious", pos:"adjective", ipa:"/ˈkjʊriəs/", def:"Eager to learn.", ex:"The kids were curious."},
  {w:"curl", pos:"verb", ipa:"/kɜːrl/", def:"To form rings.", ex:"She curled her hair."},
  {w:"currency", pos:"noun", ipa:"/ˈkɜːrənsi/", def:"Money.", ex:"What's the local currency?"},
  {w:"current", pos:"adjective", ipa:"/ˈkɜːrənt/", def:"Present.", ex:"The current policy works."},
  {w:"curriculum", pos:"noun", ipa:"/kəˈrɪkjələm/", def:"A course of study.", ex:"The curriculum changed."},
  {w:"curse", pos:"noun", ipa:"/kɜːrs/", def:"A swear; a misfortune.", ex:"He muttered a curse."},
  {w:"curt", pos:"adjective", ipa:"/kɜːrt/", def:"Rudely brief.", ex:"His reply was curt."},
  {w:"curtail", pos:"verb", ipa:"/kɜːrˈteɪl/", def:"To cut short.", ex:"We curtailed the trip."},
  {w:"cushion", pos:"noun", ipa:"/ˈkʊʃən/", def:"A soft pillow; protection.", ex:"Savings are a cushion."},
  {w:"custody", pos:"noun", ipa:"/ˈkʌstədi/", def:"Legal care.", ex:"She won custody of the kids."},
  {w:"custom", pos:"noun", ipa:"/ˈkʌstəm/", def:"A tradition.", ex:"It's our custom to gather."},
  {w:"customary", pos:"adjective", ipa:"/ˈkʌstəməri/", def:"Usual.", ex:"It's customary to tip."},
  {w:"cutback", pos:"noun", ipa:"/ˈkʌtbæk/", def:"A reduction.", ex:"There were cutbacks at work."},
  {w:"cycle", pos:"noun", ipa:"/ˈsaɪkəl/", def:"A repeating series.", ex:"The news cycle is fast."},
  {w:"cynical", pos:"adjective", ipa:"/ˈsɪnɪkəl/", def:"Distrustful.", ex:"He's cynical about politics."},
  {w:"dabble", pos:"verb", ipa:"/ˈdæbəl/", def:"To try briefly.", ex:"She dabbled in painting."},
  {w:"dainty", pos:"adjective", ipa:"/ˈdeɪnti/", def:"Delicate.", ex:"She took dainty bites."},
  {w:"damp", pos:"adjective", ipa:"/dæmp/", def:"Slightly wet.", ex:"The basement was damp."},
  {w:"dangle", pos:"verb", ipa:"/ˈdæŋɡəl/", def:"To hang loosely.", ex:"He dangled the keys."},
  {w:"dapper", pos:"adjective", ipa:"/ˈdæpər/", def:"Neatly dressed.", ex:"He looked dapper."},
  {w:"dart", pos:"verb", ipa:"/dɑːrt/", def:"To move quickly.", ex:"She darted across the street."},
  {w:"dash", pos:"verb", ipa:"/dæʃ/", def:"To rush.", ex:"He dashed to the store."},
  {w:"daunting", pos:"adjective", ipa:"/ˈdɔːntɪŋ/", def:"Intimidating.", ex:"The task seemed daunting."},
  {w:"dawdle", pos:"verb", ipa:"/ˈdɔːdəl/", def:"To waste time.", ex:"Stop dawdling!"},
  {w:"dazzle", pos:"verb", ipa:"/ˈdæzəl/", def:"To impress.", ex:"The lights dazzled us."},
  {w:"deadline", pos:"noun", ipa:"/ˈdedlaɪn/", def:"Due date.", ex:"The deadline is Friday."},
  {w:"deadlock", pos:"noun", ipa:"/ˈdedlɑːk/", def:"A standstill.", ex:"Talks ended in deadlock."},
  {w:"deadly", pos:"adjective", ipa:"/ˈdedli/", def:"Lethal.", ex:"The virus proved deadly."},
  {w:"deafening", pos:"adjective", ipa:"/ˈdefənɪŋ/", def:"Very loud.", ex:"The roar was deafening."},
  {w:"dearth", pos:"noun", ipa:"/dɜːrθ/", def:"A lack.", ex:"There's a dearth of housing."},
  {w:"debacle", pos:"noun", ipa:"/dɪˈbɑːkəl/", def:"A disaster.", ex:"The launch was a debacle."},
  {w:"debris", pos:"noun", ipa:"/dəˈbriː/", def:"Scattered remains.", ex:"Crews cleared the debris."},
  {w:"debut", pos:"noun", ipa:"/deɪˈbjuː/", def:"A first appearance.", ex:"She made her debut on stage."},
  {w:"decorum", pos:"noun", ipa:"/dɪˈkɔːrəm/", def:"Proper behavior.", ex:"Maintain decorum in court."},
  {w:"decree", pos:"noun", ipa:"/dɪˈkriː/", def:"An official order.", ex:"The decree took effect."},
  {w:"decry", pos:"verb", ipa:"/dɪˈkraɪ/", def:"To condemn publicly.", ex:"They decried the decision."},
  {w:"dedicate", pos:"verb", ipa:"/ˈdedɪkeɪt/", def:"To devote.", ex:"She dedicated her life to teaching."},
  {w:"deduce", pos:"verb", ipa:"/dɪˈduːs/", def:"To figure out logically.", ex:"We deduced the answer."},
  {w:"deem", pos:"verb", ipa:"/diːm/", def:"To consider.", ex:"They deemed it unsafe."},
  {w:"deface", pos:"verb", ipa:"/dɪˈfeɪs/", def:"To damage the appearance.", ex:"Vandals defaced the wall."},
  {w:"default", pos:"noun", ipa:"/dɪˈfɔːlt/", def:"Failure to pay; preset.", ex:"He defaulted on the loan."},
  {w:"defeat", pos:"noun", ipa:"/dɪˈfiːt/", def:"A loss.", ex:"They accepted defeat gracefully."},
  {w:"defect", pos:"noun", ipa:"/ˈdiːfekt/", def:"A flaw.", ex:"The car had a defect."},
  {w:"defend", pos:"verb", ipa:"/dɪˈfend/", def:"To protect.", ex:"She defended her friend."},
  {w:"defer", pos:"verb", ipa:"/dɪˈfɜːr/", def:"To postpone.", ex:"We deferred the decision."},
  {w:"defiant", pos:"adjective", ipa:"/dɪˈfaɪənt/", def:"Boldly resisting.", ex:"The teen was defiant."},
  {w:"deficient", pos:"adjective", ipa:"/dɪˈfɪʃənt/", def:"Lacking.", ex:"His diet is deficient in iron."},
  {w:"deficit", pos:"noun", ipa:"/ˈdefɪsɪt/", def:"A shortfall.", ex:"The budget deficit grew."},
  {w:"definitive", pos:"adjective", ipa:"/dɪˈfɪnɪtɪv/", def:"Final; authoritative.", ex:"This is the definitive guide."},
  {w:"deflate", pos:"verb", ipa:"/dɪˈfleɪt/", def:"To let air out; to reduce.", ex:"The news deflated him."},
  {w:"deflect", pos:"verb", ipa:"/dɪˈflekt/", def:"To turn aside.", ex:"She deflected the question."},
  {w:"defraud", pos:"verb", ipa:"/dɪˈfrɔːd/", def:"To cheat.", ex:"He defrauded investors."},
  {w:"defrost", pos:"verb", ipa:"/diːˈfrɔːst/", def:"To thaw.", ex:"Defrost the chicken overnight."},
  {w:"deft", pos:"adjective", ipa:"/deft/", def:"Skillful.", ex:"She gave a deft reply."},
  {w:"defunct", pos:"adjective", ipa:"/dɪˈfʌŋkt/", def:"No longer existing.", ex:"The store is defunct."},
  {w:"degrade", pos:"verb", ipa:"/dɪˈɡreɪd/", def:"To lower in quality.", ex:"Don't degrade yourself."},
  {w:"dehydrate", pos:"verb", ipa:"/diːˈhaɪdreɪt/", def:"To lose water.", ex:"Drink water so you don't dehydrate."},
  {w:"deject", pos:"verb", ipa:"/dɪˈdʒekt/", def:"To dishearten.", ex:"The loss dejected the team."},
  {w:"delay", pos:"noun", ipa:"/dɪˈleɪ/", def:"Lateness.", ex:"The flight had a delay."},
  {w:"delectable", pos:"adjective", ipa:"/dɪˈlektəbəl/", def:"Delicious.", ex:"The cake was delectable."},
  {w:"delegate", pos:"verb", ipa:"/ˈdelɪɡeɪt/", def:"To assign.", ex:"She delegated the task."},
  {w:"deliberate", pos:"adjective", ipa:"/dɪˈlɪbərət/", def:"Intentional.", ex:"It was a deliberate choice."},
  {w:"delicate", pos:"adjective", ipa:"/ˈdelɪkət/", def:"Fragile; sensitive.", ex:"It's a delicate situation."},
  {w:"delirious", pos:"adjective", ipa:"/dɪˈlɪriəs/", def:"Wildly excited; feverish.", ex:"The fans were delirious."},
  {w:"deliver", pos:"verb", ipa:"/dɪˈlɪvər/", def:"To bring; to give.", ex:"They deliver groceries."},
  {w:"delude", pos:"verb", ipa:"/dɪˈluːd/", def:"To mislead.", ex:"Don't delude yourself."},
  {w:"deluge", pos:"noun", ipa:"/ˈdeljuːdʒ/", def:"A flood.", ex:"We got a deluge of emails."},
  {w:"delusion", pos:"noun", ipa:"/dɪˈluːʒən/", def:"A false belief.", ex:"It's a delusion that he's fine."},
  {w:"delve", pos:"verb", ipa:"/delv/", def:"To dig into.", ex:"Let's delve deeper."},
  {w:"demand", pos:"noun", ipa:"/dɪˈmænd/", def:"A strong request.", ex:"There's high demand."},
  {w:"demeanor", pos:"noun", ipa:"/dɪˈmiːnər/", def:"Behavior.", ex:"His calm demeanor helped."},
  {w:"demise", pos:"noun", ipa:"/dɪˈmaɪz/", def:"Death; end.", ex:"The store's demise surprised us."},
  {w:"demolish", pos:"verb", ipa:"/dɪˈmɑːlɪʃ/", def:"To destroy.", ex:"They demolished the old mall."},
  {w:"demonstrate", pos:"verb", ipa:"/ˈdemənstreɪt/", def:"To show.", ex:"She demonstrated the app."},
  {w:"demure", pos:"adjective", ipa:"/dɪˈmjʊr/", def:"Shy and modest.", ex:"She gave a demure smile."},
  {w:"denote", pos:"verb", ipa:"/dɪˈnoʊt/", def:"To mean.", ex:"A red light denotes stop."},
  {w:"denounce", pos:"verb", ipa:"/dɪˈnaʊns/", def:"To condemn publicly.", ex:"They denounced the policy."},
  {w:"dense", pos:"adjective", ipa:"/dens/", def:"Thick.", ex:"The fog was dense."},
  {w:"dent", pos:"noun", ipa:"/dent/", def:"A small hollow.", ex:"There's a dent in the car."},
  {w:"depart", pos:"verb", ipa:"/dɪˈpɑːrt/", def:"To leave.", ex:"The train departs at six."},
  {w:"depend", pos:"verb", ipa:"/dɪˈpend/", def:"To rely.", ex:"We depend on each other."},
  {w:"depict", pos:"verb", ipa:"/dɪˈpɪkt/", def:"To show; to describe.", ex:"The film depicts real events."}
];
var SENTENCES = [
  {s:"Could you itemize the bill for me?", m:"Ask for a detailed list of charges."},
  {s:"I'd like to dispute this charge.", m:"Say you disagree with a charge."},
  {s:"Do you offer a payment plan?", m:"Ask to pay in smaller amounts over time."},
  {s:"Is there a cancellation fee?", m:"Ask what it costs to cancel."},
  {s:"Can I get an estimate first?", m:"Ask the approximate cost before agreeing."},
  {s:"I'd like to file a complaint.", m:"Formally report a problem."},
  {s:"Could you put that in writing?", m:"Ask for written confirmation."},
  {s:"What is your return policy?", m:"Ask before buying."},
  {s:"Is there a warranty on this?", m:"Ask about product guarantees."},
  {s:"I'd like to cancel my subscription.", m:"End a service."},
  {s:"Could you lower the price a little?", m:"Negotiate politely."},
  {s:"What's your best price?", m:"Negotiate."},
  {s:"I'll think about it.", m:"Decline politely while shopping."},
  {s:"Just browsing, thanks.", m:"Tell a salesperson you don't need help."},
  {s:"Could you hold this for me until tomorrow?", m:"Ask a store to reserve an item."},
  {s:"Do you price-match?", m:"Ask if the store matches lower prices."},
  {s:"Do you have a loyalty program?", m:"Ask about rewards."},
  {s:"Can I get the refund on my card?", m:"Ask how the refund works."},
  {s:"I'd like to exchange this for a larger size.", m:"At a clothing store."},
  {s:"Where are the fitting rooms?", m:"In a clothing store."},
  {s:"Do you gift-wrap?", m:"Ask about gift services."},
  {s:"When will this be back in stock?", m:"Ask about availability."},
  {s:"Could I see that in a different color?", m:"While shopping."},
  {s:"Is this machine washable?", m:"Ask about clothing care."},
  {s:"Do you have this in stock?", m:"Ask about availability."},
  {s:"I'd like to place an order for pickup.", m:"Order ahead at a store or restaurant."},
  {s:"Can I get a rain check on this sale?", m:"Ask to honor a sale price later."},
  {s:"The total seems off.", m:"Say you think the bill is wrong."},
  {s:"Could you double-bag this?", m:"Ask for extra bags."},
  {s:"I'd like to apply for the store card.", m:"Ask about a store credit card."},
  {s:"Do you validate parking?", m:"Ask if the store covers parking."},
  {s:"Where's the customer service desk?", m:"In a store or mall."},
  {s:"I'd like to leave a review.", m:"Share feedback about a business."},
  {s:"Could I speak to your supervisor?", m:"Escalate politely."},
  {s:"This item rang up at the wrong price.", m:"Report a pricing error."},
  {s:"Do you deliver?", m:"Ask about delivery service."},
  {s:"What's the delivery fee?", m:"Ask about delivery cost."},
  {s:"I'd like to schedule a delivery.", m:"Arrange a delivery time."},
  {s:"Can I change the delivery address?", m:"Update delivery details."},
  {s:"The package never arrived.", m:"Report a missing delivery."},
  {s:"I'd like to track my order.", m:"Check an order's status."},
  {s:"Could you send a replacement?", m:"Ask for a new item."},
  {s:"The item arrived damaged.", m:"Report a problem with delivery."},
  {s:"I'd like to refuse this delivery.", m:"Send a package back."},
  {s:"Do you ship internationally?", m:"Ask about shipping options."},
  {s:"How long will shipping take?", m:"Ask about delivery time."},
  {s:"I'd like to insure this package.", m:"Protect a valuable shipment."},
  {s:"What's the cheapest shipping option?", m:"Save on postage."},
  {s:"Could I get a receipt emailed to me?", m:"Ask for a digital receipt."},
  {s:"I'd like to pay in installments.", m:"Split a payment over time."},
  {s:"Is there a discount for paying cash?", m:"Ask about cash savings."},
  {s:"Do you accept mobile payments?", m:"Ask about payment methods."},
  {s:"A table for two, please.", m:"Request a table at a restaurant."},
  {s:"Do we need a reservation?", m:"Ask before dining."},
  {s:"Could we sit by the window?", m:"Request a specific table."},
  {s:"Is there a wait right now?", m:"Ask about waiting time."},
  {s:"Could we see the menu?", m:"Ask for the menu."},
  {s:"Do you have a children's menu?", m:"Ask for kid options."},
  {s:"What do you recommend?", m:"Ask the server's opinion."},
  {s:"What's the special today?", m:"Ask about daily specials."},
  {s:"Is this dish spicy?", m:"Ask about the food."},
  {s:"Does this contain nuts?", m:"Ask about allergens."},
  {s:"Could I get this without onions?", m:"Customize your order."},
  {s:"How is this cooked?", m:"Ask about preparation."},
  {s:"Could I substitute the fries for a salad?", m:"Change a side dish."},
  {s:"I'd like it medium-rare.", m:"Order steak doneness."},
  {s:"Could we get some more water?", m:"Ask for refills."},
  {s:"Could we have the check, please?", m:"Ask for the bill."},
  {s:"Can we split the check?", m:"Divide the bill."},
  {s:"Was the gratuity included?", m:"Ask if the tip is added."},
  {s:"This isn't what I ordered.", m:"Report a wrong dish politely."},
  {s:"My food is cold.", m:"Complain politely."},
  {s:"Could I get this to go?", m:"Ask for a takeout box."},
  {s:"Do you do takeout?", m:"Ask about ordering to go."},
  {s:"I'd like to place a takeout order.", m:"Order food to go."},
  {s:"How long will the wait be?", m:"Ask about pickup time."},
  {s:"Is there outdoor seating?", m:"Ask about patio options."},
  {s:"Do you have high chairs?", m:"Ask for baby seating."},
  {s:"Could we move to a quieter table?", m:"Request a table change."},
  {s:"The service has been great.", m:"Compliment the staff."},
  {s:"Could I see the dessert menu?", m:"Ask for desserts."},
  {s:"Do you have decaf?", m:"Ask for decaffeinated coffee."},
  {s:"Could I get lemon with that?", m:"Customize a drink."},
  {s:"Is the fish fresh today?", m:"Ask about seafood."},
  {s:"What comes with this dish?", m:"Ask about included sides."},
  {s:"Could you make it less salty?", m:"Request a milder dish."},
  {s:"I'm ready to order.", m:"Tell the server you're ready."},
  {s:"Could we have a few more minutes?", m:"Ask for more time with the menu."},
  {s:"Do you have any gluten-free options?", m:"Ask about dietary needs."},
  {s:"Is this dish vegetarian?", m:"Ask about meat content."},
  {s:"Could I get extra napkins?", m:"Ask for more napkins."},
  {s:"The soup is delicious.", m:"Compliment the food."},
  {s:"Could you pack the leftovers?", m:"Ask for a to-go box."},
  {s:"Do you cater events?", m:"Ask about catering services."},
  {s:"I'd like to book the private room.", m:"Reserve a party space."},
  {s:"What are your hours on weekends?", m:"Ask about opening times."},
  {s:"Do you take walk-ins?", m:"Ask if reservations are needed."},
  {s:"Is there parking nearby?", m:"Ask about parking."},
  {s:"Could you recommend a good dish?", m:"Ask for suggestions."},
  {s:"I'll have what she's having.", m:"Order the same as someone else."},
  {s:"Could we get separate checks?", m:"Each person pays separately."},
  {s:"Keep the change.", m:"Tell the server to keep extra money as a tip."},
  {s:"Could I get a copy of the menu to go?", m:"Take a menu home."},
  {s:"Do you have a bar area?", m:"Ask about seating options."},
  {s:"I'd like to make an appointment.", m:"Call a clinic or office."},
  {s:"Do you take my insurance?", m:"Ask before a medical visit."},
  {s:"I'd like to see a doctor.", m:"At a clinic."},
  {s:"It's urgent.", m:"Say you need help quickly."},
  {s:"Where is the emergency room?", m:"In a hospital."},
  {s:"I need to see a specialist.", m:"Ask for a referral."},
  {s:"What are the side effects?", m:"Ask about medicine."},
  {s:"How often should I take this?", m:"Ask about dosage."},
  {s:"Should I take this with food?", m:"Ask about medicine instructions."},
  {s:"I'm allergic to penicillin.", m:"Tell medical staff."},
  {s:"I have a high fever.", m:"Describe symptoms."},
  {s:"I've had this cough for a week.", m:"Describe symptoms."},
  {s:"It hurts when I breathe.", m:"Describe pain."},
  {s:"The pain is in my lower back.", m:"Describe where it hurts."},
  {s:"On a scale of one to ten, it's a seven.", m:"Rate your pain."},
  {s:"I feel dizzy.", m:"Describe symptoms."},
  {s:"I've been feeling nauseous.", m:"Describe symptoms."},
  {s:"I think I sprained my ankle.", m:"Describe an injury."},
  {s:"I need a refill on my prescription.", m:"At the pharmacy."},
  {s:"Is there a generic version?", m:"Ask about cheaper medicine."},
  {s:"Do I need a prescription for this?", m:"At the pharmacy."},
  {s:"What is this medicine for?", m:"Ask the pharmacist."},
  {s:"Are there any foods I should avoid?", m:"Ask about diet with medicine."},
  {s:"Can I drink alcohol with this?", m:"Ask about interactions."},
  {s:"I'd like a second opinion.", m:"Ask another doctor."},
  {s:"When should I come back?", m:"Ask about follow-up."},
  {s:"Do I need to fast before the test?", m:"Ask about test preparation."},
  {s:"How long until the results come back?", m:"Ask about test timing."},
  {s:"Could you explain the results?", m:"Ask the doctor."},
  {s:"Is this covered by my insurance?", m:"Ask about costs."},
  {s:"What will this cost out of pocket?", m:"Ask about your share."},
  {s:"I'd like an itemized bill.", m:"Ask for detailed medical charges."},
  {s:"Can I set up a payment plan?", m:"Pay medical bills over time."},
  {s:"I need my medical records.", m:"Request your files."},
  {s:"Could you refer me to a dentist?", m:"Ask for a recommendation."},
  {s:"My tooth is aching.", m:"At the dentist."},
  {s:"I need a cleaning.", m:"At the dentist."},
  {s:"Do you accept new patients?", m:"Ask a clinic."},
  {s:"What are your office hours?", m:"Ask a clinic."},
  {s:"I need to cancel my appointment.", m:"Change plans politely."},
  {s:"Can I reschedule for next week?", m:"Move an appointment."},
  {s:"I'm running late for my appointment.", m:"Call ahead."},
  {s:"Do I need to bring anything?", m:"Ask before a visit."},
  {s:"Could you help me fill out this form?", m:"Ask for help with paperwork."},
  {s:"I don't understand this form.", m:"Ask for help."},
  {s:"What does this term mean?", m:"Ask about medical words."},
  {s:"Could you write that down for me?", m:"Ask for written instructions."},
  {s:"I need a note for work.", m:"Ask for a doctor's note."},
  {s:"When can I go back to work?", m:"Ask about recovery."},
  {s:"Should I rest or stay active?", m:"Ask about recovery."},
  {s:"Is this contagious?", m:"Ask about spreading illness."},
  {s:"How can I prevent this?", m:"Ask about prevention."},
  {s:"Could we schedule a meeting?", m:"Arrange a work meeting."},
  {s:"What time works for you?", m:"Ask about availability."},
  {s:"I'll send you the agenda.", m:"Before a meeting."},
  {s:"Let's touch base tomorrow.", m:"Plan a quick check-in."},
  {s:"Could you give me an update?", m:"Ask about progress."},
  {s:"What's the deadline for this?", m:"Ask about due dates."},
  {s:"I need an extension.", m:"Ask for more time."},
  {s:"I'm running behind on this.", m:"Admit you're late."},
  {s:"Could you prioritize this?", m:"Ask to make something urgent."},
  {s:"Let me look into it.", m:"Say you'll investigate."},
  {s:"I'll follow up with you.", m:"Promise to update later."},
  {s:"Could you cc me on that email?", m:"Ask to be included."},
  {s:"I didn't get the attachment.", m:"Report an email problem."},
  {s:"Could you resend the file?", m:"Ask again."},
  {s:"The printer is jammed.", m:"Report an office problem."},
  {s:"Could you show me how this works?", m:"Ask for training."},
  {s:"I'm new here.", m:"Introduce yourself at work."},
  {s:"Who should I report to?", m:"Ask about your boss."},
  {s:"What are my responsibilities?", m:"Ask about your role."},
  {s:"When is payday?", m:"Ask about salary schedule."},
  {s:"How do I request time off?", m:"Ask about vacation."},
  {s:"I'd like to take Friday off.", m:"Request a day off."},
  {s:"I'm calling in sick today.", m:"Report an absence."},
  {s:"Could I work from home tomorrow?", m:"Ask about remote work."},
  {s:"What's the dress code?", m:"Ask about clothing rules."},
  {s:"Where's the break room?", m:"Ask about the office."},
  {s:"I'd like to discuss a raise.", m:"Bring up salary politely."},
  {s:"I'd like to apply for the position.", m:"Express interest in a job."},
  {s:"What does the job involve?", m:"Ask about a role."},
  {s:"What are the hours?", m:"Ask about a schedule."},
  {s:"Is this full-time or part-time?", m:"Ask about employment type."},
  {s:"What benefits do you offer?", m:"Ask about health insurance and more."},
  {s:"When will I hear back?", m:"Ask after an interview."},
  {s:"Thank you for the opportunity.", m:"After an interview."},
  {s:"Could you be a reference for me?", m:"Ask someone to recommend you."},
  {s:"I'd like to give my two weeks' notice.", m:"Resign politely."},
  {s:"Could I have a letter of recommendation?", m:"Ask for a reference letter."},
  {s:"What's the overtime policy?", m:"Ask about extra hours."},
  {s:"Do you offer training?", m:"Ask about learning opportunities."},
  {s:"I'd like to transfer departments.", m:"Request a move."},
  {s:"Who's covering for me?", m:"Ask about your absence."},
  {s:"Could you train the new hire?", m:"Ask a coworker."},
  {s:"Let's divide up the work.", m:"Share tasks fairly."},
  {s:"I can take that on.", m:"Volunteer for a task."},
  {s:"That's not my area.", m:"Decline politely."},
  {s:"Could you walk me through the process?", m:"Ask for step-by-step help."},
  {s:"I need this by end of day.", m:"Set a deadline."},
  {s:"This is time-sensitive.", m:"Say it's urgent."},
  {s:"Let's brainstorm some ideas.", m:"Generate ideas together."},
  {s:"Could we get a second opinion?", m:"Ask someone else."},
  {s:"I disagree, and here's why.", m:"Disagree respectfully."},
  {s:"Let's find a middle ground.", m:"Compromise."},
  {s:"May I speak to Ms. Chen?", m:"Ask for someone on the phone."},
  {s:"She's not available right now.", m:"Take a message politely."},
  {s:"Could I leave a message?", m:"When someone is unavailable."},
  {s:"Could you ask her to call me back?", m:"Request a callback."},
  {s:"What's a good number to reach you?", m:"Ask for contact info."},
  {s:"Could you spell your last name?", m:"Get correct spelling."},
  {s:"Could you repeat that number?", m:"Confirm details."},
  {s:"Sorry, you broke up.", m:"Say the call dropped."},
  {s:"Can you hear me now?", m:"Check the connection."},
  {s:"Let me call you right back.", m:"Pause a call politely."},
  {s:"I'm in a meeting; can I call you later?", m:"Decline a call politely."},
  {s:"Is this a good time to talk?", m:"Check availability."},
  {s:"I only have five minutes.", m:"Limit a call."},
  {s:"Could you hold for a moment?", m:"Ask someone to wait."},
  {s:"Thanks for holding.", m:"Return to a call."},
  {s:"Could you transfer me to billing?", m:"Ask to be connected."},
  {s:"I'd like to speak to a manager.", m:"Escalate on the phone."},
  {s:"What's your name, please?", m:"Ask politely."},
  {s:"Could I have your extension?", m:"Get a direct line."},
  {s:"I'll text you the address.", m:"Follow up after a call."},
  {s:"Did you get my voicemail?", m:"Follow up."},
  {s:"Could you email me the details?", m:"Ask for written info."},
  {s:"I'll send it right over.", m:"Promise to send quickly."},
  {s:"Let me check and get back to you.", m:"Buy time politely."},
  {s:"I need to confirm with my team.", m:"Delay a decision."},
  {s:"Could we set up a call next week?", m:"Schedule a phone meeting."},
  {s:"What time zone are you in?", m:"Coordinate across zones."},
  {s:"Let's do a video call instead.", m:"Suggest video."},
  {s:"Can you see my screen?", m:"During a video call."},
  {s:"You're on mute.", m:"Help someone on a call."},
  {s:"Could you share your screen?", m:"During a video meeting."},
  {s:"The audio isn't working.", m:"Report a tech issue."},
  {s:"Let me try rejoining.", m:"Fix a call problem."},
  {s:"Could you send the link again?", m:"Ask for meeting access."},
  {s:"I'll follow up by email.", m:"End a call with next steps."},
  {s:"Thanks for your time.", m:"End a call politely."},
  {s:"Could you confirm receipt?", m:"Ask if they got it."},
  {s:"I sent it yesterday.", m:"Follow up on a message."},
  {s:"Just checking in.", m:"A friendly follow-up."},
  {s:"Bumping this up.", m:"Remind someone politely by email."},
  {s:"Per my last email.", m:"Refer to a previous message."},
  {s:"Please see attached.", m:"Refer to a file in an email."},
  {s:"Let me know if you have questions.", m:"Close an email helpfully."},
  {s:"Thanks in advance.", m:"Thank someone before a favor."},
  {s:"Sorry for the delayed reply.", m:"Apologize for lateness."},
  {s:"Could you clarify what you mean?", m:"Ask for explanation."},
  {s:"I wanted to make sure we're on the same page.", m:"Confirm understanding."},
  {s:"Let's keep each other in the loop.", m:"Stay mutually informed."},
  {s:"Could you keep this confidential?", m:"Ask for privacy."},
  {s:"I need to run this by my manager.", m:"Say you need approval."},
  {s:"What's the best way to reach you?", m:"Ask for preferred contact."},
  {s:"I'll keep you posted.", m:"Promise updates."},
  {s:"Is this the right bus for downtown?", m:"Ask about transit."},
  {s:"How much is the fare?", m:"Ask about ticket price."},
  {s:"Where do I transfer?", m:"Ask about connections."},
  {s:"Does this train stop at Union Station?", m:"Ask about stops."},
  {s:"Could I get a day pass?", m:"Buy transit tickets."},
  {s:"Is there a senior discount?", m:"Ask about reduced fares."},
  {s:"My car won't start.", m:"Report car trouble."},
  {s:"I need a jump-start.", m:"Ask for battery help."},
  {s:"Could you tow my car?", m:"Call for roadside help."},
  {s:"I have a flat tire.", m:"Report car trouble."},
  {s:"Where's the nearest gas station?", m:"Ask for directions."},
  {s:"Could you check the tire pressure?", m:"At a gas station or shop."},
  {s:"I need an oil change.", m:"At a mechanic."},
  {s:"Could you give me an estimate?", m:"Before car repairs."},
  {s:"How long will the repair take?", m:"Ask a mechanic."},
  {s:"Is this covered under warranty?", m:"Ask about repair costs."},
  {s:"I'd like to test-drive this car.", m:"At a dealership."},
  {s:"What's the mileage on this?", m:"Ask about a used car."},
  {s:"Has it been in any accidents?", m:"Ask about car history."},
  {s:"Could I see the vehicle history report?", m:"Before buying."},
  {s:"What's your asking price?", m:"Negotiate."},
  {s:"Is the price negotiable?", m:"Negotiate."},
  {s:"I'd like to make an offer.", m:"Negotiate."},
  {s:"Could I take it to my mechanic?", m:"Before buying a used car."},
  {s:"When is the registration due?", m:"Ask about car paperwork."},
  {s:"I need to renew my license.", m:"At the DMV."},
  {s:"What documents do I need?", m:"Ask about requirements."},
  {s:"Could I get a copy of that?", m:"Ask for documents."},
  {s:"I lost my ID.", m:"Report a lost card."},
  {s:"I'd like to report a lost wallet.", m:"At police or lost-and-found."},
  {s:"Where's the lost and found?", m:"In a public place."},
  {s:"I left my bag on the bus.", m:"Report lost property."},
  {s:"Could you check if it was turned in?", m:"Ask about lost items."},
  {s:"I'd like to file a report.", m:"At the police station."},
  {s:"Someone broke into my car.", m:"Report a crime."},
  {s:"I need to dispute a ticket.", m:"Challenge a fine."},
  {s:"When is my court date?", m:"Ask about legal matters."},
  {s:"Could you recommend a lawyer?", m:"Ask for legal help."},
  {s:"Do you offer free consultations?", m:"Ask a professional."},
  {s:"What are your rates?", m:"Ask about fees."},
  {s:"I'd like to get a second quote.", m:"Compare prices."},
  {s:"Could you send me an invoice?", m:"Ask for a bill."},
  {s:"When is payment due?", m:"Ask about deadlines."},
  {s:"I'd like to pay the deposit today.", m:"Secure a service."},
  {s:"Is the deposit refundable?", m:"Ask before paying."},
  {s:"Could I get that in writing?", m:"Confirm an agreement."},
  {s:"I'd like to review the contract.", m:"Before signing."},
  {s:"Could you explain this clause?", m:"Ask about contract terms."},
  {s:"I have a question about my lease.", m:"Talk to a landlord."},
  {s:"The sink is leaking.", m:"Report a home repair."},
  {s:"The heater isn't working.", m:"Report a home repair."},
  {s:"Could you send someone to fix it?", m:"Ask a landlord."},
  {s:"When will the repair be done?", m:"Ask about timing."},
  {s:"I'd like to schedule a repair.", m:"Book a service visit."},
  {s:"Do you charge for estimates?", m:"Ask a contractor."},
  {s:"Could you clean the gutters?", m:"Hire home services."},
  {s:"I need a plumber.", m:"Find a professional."},
  {s:"Do you guarantee your work?", m:"Ask a contractor."},
  {s:"I'd like to get my carpets cleaned.", m:"Hire a service."},
  {s:"Could you mow the lawn weekly?", m:"Hire yard help."},
  {s:"The Wi-Fi is down.", m:"Report internet problems."},
  {s:"Could you reset the router?", m:"Ask tech support."},
  {s:"My bill seems too high.", m:"Question a utility bill."},
  {s:"I'd like to set up autopay.", m:"Automate payments."},
  {s:"Could you waive the late fee?", m:"Ask for forgiveness politely."},
  {s:"I never received the bill.", m:"Explain a missed payment."},
  {s:"Could you send me a copy?", m:"Ask for documents."},
  {s:"I'd like to change my address.", m:"Update your info."},
  {s:"Could you update my contact info?", m:"Update records."},
  {s:"I need to add someone to my account.", m:"Manage accounts."},
  {s:"Could I get a copy of my statement?", m:"At a bank."},
  {s:"I'd like to close this account.", m:"End an account."},
  {s:"What happens if I miss a payment?", m:"Ask about consequences."},
  {s:"Could you explain these charges?", m:"Ask about a bill."},
  {s:"I'd like to enroll my child in school.", m:"At a school office."},
  {s:"What documents do you need?", m:"Ask about enrollment."},
  {s:"When does school start?", m:"Ask about dates."},
  {s:"Could I meet the teacher?", m:"At a school."},
  {s:"How is my child doing?", m:"Ask about progress."},
  {s:"Could we schedule a conference?", m:"Meet about your child."},
  {s:"My child will be absent tomorrow.", m:"Notify the school."},
  {s:"What time does school end?", m:"Ask about schedule."},
  {s:"Is there an after-school program?", m:"Ask about activities."},
  {s:"Could I volunteer?", m:"Offer help at school."},
  {s:"I'd like to join the PTA.", m:"Get involved."},
  {s:"When are parent-teacher conferences?", m:"Ask about meetings."},
  {s:"Could you excuse my child from PE?", m:"Write a school note."},
  {s:"I need a copy of the transcript.", m:"Request school records."},
  {s:"Could you write a recommendation letter?", m:"Ask a teacher."},
  {s:"What colleges do you suggest?", m:"Ask a counselor."},
  {s:"I'd like to invite you over for dinner.", m:"Invite someone."},
  {s:"Are you free this weekend?", m:"Make plans."},
  {s:"Could we reschedule for Saturday?", m:"Change plans."},
  {s:"I have to cancel, sorry.", m:"Cancel politely."},
  {s:"Thanks for having us over.", m:"Thank a host."},
  {s:"Could I bring anything?", m:"Offer to contribute."},
  {s:"It was great seeing you.", m:"Say goodbye warmly."},
  {s:"Let's get together soon.", m:"Suggest meeting again."},
  {s:"Happy birthday!", m:"Celebrate someone."},
  {s:"Congratulations on the new job!", m:"Share joy."},
  {s:"I'm sorry for your loss.", m:"Express sympathy."},
  {s:"Get well soon.", m:"Wish recovery."},
  {s:"Call me if you need anything.", m:"Offer help."},
  {s:"Drive safe.", m:"Say goodbye with care."},
  {s:"Have a safe trip.", m:"Wish someone well."}
];
(function(){
  var wOff = 0, sOff = 0;
  function dayOfYear(d){var s=new Date(d.getFullYear(),0,0);return Math.floor((d-s)/864e5);}
  function idx(off,n){var i=(dayOfYear(new Date())+off)%n;return i<0?i+n:i;}
  function fmtDate(off){var d=new Date();d.setDate(d.getDate()+off);
    return d.toLocaleDateString('en-US',{month:'short',day:'numeric'});}
  function speak(t){try{if('speechSynthesis' in window){speechSynthesis.cancel();
    speechSynthesis.speak(new SpeechSynthesisUtterance(t));}}catch(e){}}
  function render(){
    var w=WORDS[idx(wOff,WORDS.length)];
    document.getElementById('dw-word').textContent=w.w;
    document.getElementById('dw-meta').textContent=w.pos+'  '+w.ipa;
    document.getElementById('dw-def').textContent=w.def;
    document.getElementById('dw-ex').textContent='“'+w.ex+'”';
    document.getElementById('dw-date').textContent=fmtDate(wOff);
    var s=SENTENCES[idx(sOff,SENTENCES.length)];
    document.getElementById('ds-text').textContent='“'+s.s+'”';
    document.getElementById('ds-meaning').textContent=s.m;
    document.getElementById('ds-date').textContent=fmtDate(sOff);
  }
  document.getElementById('dw-prev').addEventListener('click',function(){wOff--;render();});
  document.getElementById('dw-next').addEventListener('click',function(){wOff++;render();});
  document.getElementById('ds-prev').addEventListener('click',function(){sOff--;render();});
  document.getElementById('ds-next').addEventListener('click',function(){sOff++;render();});
  document.getElementById('dw-speak').addEventListener('click',function(){
    var w=WORDS[idx(wOff,WORDS.length)];speak(w.w+'. '+w.def+' '+w.ex);});
  document.getElementById('ds-speak').addEventListener('click',function(){
    var s=SENTENCES[idx(sOff,SENTENCES.length)];speak(s.s);});
  render();
})();
