/* Daily word & sentence data for the ESLnote homepage. Rotates by day of year.
   Level: intermediate to advanced. */
var WORDS = [
{w:"meticulous",pos:"adjective",ipa:"/məˈtɪkjələs/",def:"Very careful and precise.",ex:"She keeps meticulous records of every expense."},
{w:"ambiguous",pos:"adjective",ipa:"/æmˈbɪɡjuəs/",def:"Having more than one possible meaning; unclear.",ex:"His answer was ambiguous, so nobody knew what he had decided."},
{w:"inevitable",pos:"adjective",ipa:"/ɪnˈevɪtəbəl/",def:"Certain to happen; unavoidable.",ex:"Some stress during finals week is inevitable."},
{w:"resilient",pos:"adjective",ipa:"/rɪˈzɪliənt/",def:"Able to recover quickly from problems.",ex:"Children are remarkably resilient after hardship."},
{w:"controversial",pos:"adjective",ipa:"/ˌkɑːntrəˈvɜːrʃəl/",def:"Causing public disagreement.",ex:"The new policy proved highly controversial."},
{w:"phenomenon",pos:"noun",ipa:"/fəˈnɑːmɪnɑːn/",def:"Something remarkable that can be observed.",ex:"Rapid urban growth is a worldwide phenomenon."},
{w:"implication",pos:"noun",ipa:"/ˌɪmplɪˈkeɪʃən/",def:"Something suggested without being said directly; a likely consequence.",ex:"The implication of his silence was clear: he disagreed."},
{w:"perspective",pos:"noun",ipa:"/pərˈspektɪv/",def:"A particular way of seeing things.",ex:"Travel gave her a new perspective on life."},
{w:"obstacle",pos:"noun",ipa:"/ˈɑːbstəkəl/",def:"Something that blocks progress.",ex:"Lack of funding was a major obstacle."},
{w:"accomplish",pos:"verb",ipa:"/əˈkɑːmplɪʃ/",def:"To succeed in doing something.",ex:"She accomplished more in a year than most do in five."},
{w:"dilemma",pos:"noun",ipa:"/dɪˈlemə/",def:"A difficult choice between two options.",ex:"He faced the dilemma of choosing between two job offers."},
{w:"procrastinate",pos:"verb",ipa:"/proʊˈkræstɪneɪt/",def:"To delay doing something you should do.",ex:"Stop procrastinating and start your essay."},
{w:"skeptical",pos:"adjective",ipa:"/ˈskeptɪkəl/",def:"Doubting that something is true.",ex:"She was skeptical of the salesman's promises."},
{w:"subtle",pos:"adjective",ipa:"/ˈsʌtəl/",def:"Not obvious; delicate.",ex:"There is a subtle difference between the two words."},
{w:"thrive",pos:"verb",ipa:"/θraɪv/",def:"To grow or succeed strongly.",ex:"Small businesses thrive in this neighborhood."},
{w:"deteriorate",pos:"verb",ipa:"/dɪˈtɪriəreɪt/",def:"To become worse.",ex:"His health deteriorated rapidly."},
{w:"nonetheless",pos:"adverb",ipa:"/ˌnʌnðəˈles/",def:"Despite what was just said; however.",ex:"It was raining; nonetheless, we went hiking."},
{w:"reluctant",pos:"adjective",ipa:"/rɪˈlʌktənt/",def:"Unwilling; not wanting to do something.",ex:"He was reluctant to admit the mistake."},
{w:"coherent",pos:"adjective",ipa:"/koʊˈhɪrənt/",def:"Clear and logical.",ex:"Write a coherent paragraph with a clear main idea."},
{w:"paradox",pos:"noun",ipa:"/ˈpærədɑːks/",def:"A statement that seems contradictory but may be true.",ex:"It is a paradox that doing less can sometimes achieve more."},
{w:"indispensable",pos:"adjective",ipa:"/ˌɪndɪˈspensəbəl/",def:"Absolutely necessary.",ex:"Good communication is indispensable in any team."},
{w:"mitigate",pos:"verb",ipa:"/ˈmɪtɪɡeɪt/",def:"To make something less severe.",ex:"Planting trees helps mitigate air pollution."},
{w:"pragmatic",pos:"adjective",ipa:"/præɡˈmætɪk/",def:"Practical rather than idealistic.",ex:"Let's take a pragmatic approach to the budget."},
{w:"evoke",pos:"verb",ipa:"/ɪˈvoʊk/",def:"To bring a feeling or memory to mind.",ex:"The song evoked memories of her childhood."},
{w:"integrity",pos:"noun",ipa:"/ɪnˈteɡrəti/",def:"Honesty and strong moral principles.",ex:"Voters expect integrity from their leaders."},
{w:"compromise",pos:"noun",ipa:"/ˈkɑːmprəmaɪz/",def:"An agreement where both sides give up something.",ex:"They reached a compromise after hours of discussion."},
{w:"anticipate",pos:"verb",ipa:"/ænˈtɪsɪpeɪt/",def:"To expect that something will happen.",ex:"We anticipate heavy traffic on Friday."},
{w:"feasible",pos:"adjective",ipa:"/ˈfiːzəbəl/",def:"Possible and practical to do.",ex:"It is not feasible to finish by tomorrow."},
{w:"criteria",pos:"noun",ipa:"/kraɪˈtɪriə/",def:"Standards used to judge something. (plural of criterion)",ex:"Price is only one of our criteria."},
{w:"bias",pos:"noun",ipa:"/ˈbaɪəs/",def:"An unfair preference for or against something.",ex:"The hiring process must be free of bias."},
{w:"profound",pos:"adjective",ipa:"/proʊˈfaʊnd/",def:"Very deep; showing great insight.",ex:"The book had a profound effect on me."},
{w:"strive",pos:"verb",ipa:"/straɪv/",def:"To try very hard.",ex:"We strive to improve every day."},
{w:"diminish",pos:"verb",ipa:"/dɪˈmɪnɪʃ/",def:"To become or make smaller.",ex:"His influence diminished over time."},
{w:"encompass",pos:"verb",ipa:"/ɪnˈkʌmpəs/",def:"To include everything.",ex:"The course encompasses grammar, writing, and speaking."},
{w:"articulate",pos:"adjective",ipa:"/ɑːrˈtɪkjələt/",def:"Able to express ideas clearly.",ex:"She is an articulate speaker."},
{w:"apprehensive",pos:"adjective",ipa:"/ˌæprɪˈhensɪv/",def:"Worried about the future.",ex:"He felt apprehensive before the interview."},
{w:"complacent",pos:"adjective",ipa:"/kəmˈpleɪsənt/",def:"Too satisfied; not worried about improving.",ex:"Don't get complacent — keep practicing."},
{w:"disparity",pos:"noun",ipa:"/dɪˈspærəti/",def:"A noticeable difference.",ex:"There is a growing disparity between rich and poor."},
{w:"eloquent",pos:"adjective",ipa:"/ˈeləkwənt/",def:"Fluent and persuasive in speaking.",ex:"She gave an eloquent speech."},
{w:"fluctuate",pos:"verb",ipa:"/ˈflʌktʃueɪt/",def:"To rise and fall irregularly.",ex:"Prices fluctuate with the seasons."},
{w:"genuine",pos:"adjective",ipa:"/ˈdʒenjuɪn/",def:"Real; sincere.",ex:"He showed genuine interest in my story."},
{w:"hinder",pos:"verb",ipa:"/ˈhɪndər/",def:"To slow down or make difficult.",ex:"Poor lighting hindered our work."},
{w:"innovative",pos:"adjective",ipa:"/ˈɪnəveɪtɪv/",def:"Introducing new ideas.",ex:"The company is known for innovative designs."},
{w:"incentive",pos:"noun",ipa:"/ɪnˈsentɪv/",def:"Something that encourages action.",ex:"Bonuses are a strong incentive."},
{w:"jeopardize",pos:"verb",ipa:"/ˈdʒepərdaɪz/",def:"To put at risk.",ex:"Don't jeopardize your health by skipping sleep."},
{w:"lucrative",pos:"adjective",ipa:"/ˈluːkrətɪv/",def:"Producing a lot of profit.",ex:"Real estate can be a lucrative investment."},
{w:"mandatory",pos:"adjective",ipa:"/ˈmændətɔːri/",def:"Required by rule.",ex:"Attendance at orientation is mandatory."},
{w:"notion",pos:"noun",ipa:"/ˈnoʊʃən/",def:"An idea or belief.",ex:"He rejected the notion that money buys happiness."},
{w:"obsolete",pos:"adjective",ipa:"/ˌɑːbsəˈliːt/",def:"No longer used; out of date.",ex:"Fax machines are nearly obsolete."},
{w:"persist",pos:"verb",ipa:"/pərˈsɪst/",def:"To continue firmly.",ex:"If you persist, you will succeed."},
{w:"plausible",pos:"adjective",ipa:"/ˈplɔːzəbəl/",def:"Seeming reasonable or true.",ex:"She gave a plausible excuse."},
{w:"predominant",pos:"adjective",ipa:"/prɪˈdɑːmɪnənt/",def:"Most common or strongest.",ex:"English is the predominant language in the office."},
{w:"reimburse",pos:"verb",ipa:"/ˌriːɪmˈbɜːrs/",def:"To pay back money someone spent.",ex:"The company will reimburse your travel costs."},
{w:"scrutinize",pos:"verb",ipa:"/ˈskruːtənaɪz/",def:"To examine very carefully.",ex:"Investors scrutinized the report."},
{w:"spontaneous",pos:"adjective",ipa:"/spɑːnˈteɪniəs/",def:"Done naturally without planning.",ex:"We took a spontaneous road trip."},
{w:"substantial",pos:"adjective",ipa:"/səbˈstænʃəl/",def:"Large in size or importance.",ex:"He made a substantial donation."},
{w:"suppress",pos:"verb",ipa:"/səˈpres/",def:"To hold back or stop.",ex:"She tried to suppress her laughter."},
{w:"tangible",pos:"adjective",ipa:"/ˈtændʒəbəl/",def:"Clear enough to be real or measured.",ex:"We need tangible results, not promises."},
{w:"tedious",pos:"adjective",ipa:"/ˈtiːdiəs/",def:"Boring and long.",ex:"Data entry is tedious work."},
{w:"undermine",pos:"verb",ipa:"/ˌʌndərˈmaɪn/",def:"To gradually weaken.",ex:"Constant criticism undermines confidence."},
{w:"adversity",pos:"noun",ipa:"/ædˈvɜːrsəti/",def:"Hardship; difficult times.",ex:"She overcame adversity to graduate."},
{w:"benevolent",pos:"adjective",ipa:"/bəˈnevələnt/",def:"Kind and generous.",ex:"A benevolent donor funded the library."},
{w:"candid",pos:"adjective",ipa:"/ˈkændɪd/",def:"Honest and direct.",ex:"Let me be candid: the plan won't work."},
{w:"decipher",pos:"verb",ipa:"/dɪˈsaɪfər/",def:"To figure out the meaning of something.",ex:"I couldn't decipher his handwriting."},
{w:"emulate",pos:"verb",ipa:"/ˈemjəleɪt/",def:"To imitate in order to equal or excel.",ex:"She emulates her mentor's work ethic."},
{w:"facet",pos:"noun",ipa:"/ˈfæsɪt/",def:"One aspect of something.",ex:"Every facet of the project was reviewed."},
{w:"gratify",pos:"verb",ipa:"/ˈɡrætɪfaɪ/",def:"To please or satisfy.",ex:"It gratified him to see her succeed."},
{w:"hasten",pos:"verb",ipa:"/ˈheɪsən/",def:"To speed up.",ex:"The rain hastened our departure."},
{w:"impeccable",pos:"adjective",ipa:"/ɪmˈpekəbəl/",def:"Flawless.",ex:"His English pronunciation is impeccable."},
{w:"jubilant",pos:"adjective",ipa:"/ˈdʒuːbɪlənt/",def:"Extremely joyful.",ex:"The jubilant crowd cheered."},
{w:"keen",pos:"adjective",ipa:"/kiːn/",def:"Eager; having a sharp mind.",ex:"She has a keen eye for detail."},
{w:"lavish",pos:"adjective",ipa:"/ˈlævɪʃ/",def:"Extravagant; generous in amount.",ex:"They threw a lavish party."},
{w:"meager",pos:"adjective",ipa:"/ˈmiːɡər/",def:"Too small; inadequate.",ex:"He lived on a meager salary."},
{w:"novice",pos:"noun",ipa:"/ˈnɑːvɪs/",def:"A beginner.",ex:"The course is designed for novices."},
{w:"opulent",pos:"adjective",ipa:"/ˈɑːpjələnt/",def:"Luxurious.",ex:"The hotel lobby was opulent."},
{w:"peril",pos:"noun",ipa:"/ˈperəl/",def:"Serious danger.",ex:"They were in grave peril."},
{w:"quandary",pos:"noun",ipa:"/ˈkwɑːndəri/",def:"A state of confusion over what to do.",ex:"I'm in a quandary about which offer to accept."},
{w:"rift",pos:"noun",ipa:"/rɪft/",def:"A serious break in a relationship.",ex:"The argument caused a rift between them."},
{w:"serene",pos:"adjective",ipa:"/səˈriːn/",def:"Calm and peaceful.",ex:"The lake was serene at dawn."},
{w:"tenacious",pos:"adjective",ipa:"/tɪˈneɪʃəs/",def:"Holding firmly; persistent.",ex:"Her tenacious effort paid off."},
{w:"unanimous",pos:"adjective",ipa:"/juːˈnænɪməs/",def:"Fully agreed by everyone.",ex:"The vote was unanimous."},
{w:"venerate",pos:"verb",ipa:"/ˈvenəreɪt/",def:"To respect deeply.",ex:"He is venerated as a national hero."},
{w:"whimsical",pos:"adjective",ipa:"/ˈwɪmzɪkəl/",def:"Playful and unusual.",ex:"The garden had a whimsical design."},
{w:"yearn",pos:"verb",ipa:"/jɜːrn/",def:"To long for deeply.",ex:"She yearned to travel abroad."},
{w:"zealous",pos:"adjective",ipa:"/ˈzeləs/",def:"Very enthusiastic.",ex:"A zealous volunteer organized the drive."},
{w:"abridge",pos:"verb",ipa:"/əˈbrɪdʒ/",def:"To shorten.",ex:"The novel was abridged for students."},
{w:"bolster",pos:"verb",ipa:"/ˈboʊlstər/",def:"To support or strengthen.",ex:"Good reviews bolstered sales."},
{w:"concise",pos:"adjective",ipa:"/kənˈsaɪs/",def:"Brief and clear.",ex:"Write a concise summary."},
{w:"deplete",pos:"verb",ipa:"/dɪˈpliːt/",def:"To use up.",ex:"Overfishing has depleted the stock."},
{w:"elicit",pos:"verb",ipa:"/ɪˈlɪsɪt/",def:"To draw out a response.",ex:"The question elicited laughter."},
{w:"fortify",pos:"verb",ipa:"/ˈfɔːrtɪfaɪ/",def:"To strengthen.",ex:"Vitamins fortify the immune system."},
{w:"grapple",pos:"verb",ipa:"/ˈɡræpəl/",def:"To struggle with.",ex:"She grappled with the difficult decision."},
{w:"hamper",pos:"verb",ipa:"/ˈhæmpər/",def:"To slow down.",ex:"Fog hampered the rescue effort."},
{w:"ignite",pos:"verb",ipa:"/ɪɡˈnaɪt/",def:"To set on fire; to spark.",ex:"His speech ignited the crowd."},
{w:"jargon",pos:"noun",ipa:"/ˈdʒɑːrɡən/",def:"Specialized language.",ex:"Avoid technical jargon in your essay."},
{w:"kindle",pos:"verb",ipa:"/ˈkɪndəl/",def:"To start a fire; to arouse.",ex:"The story kindled her interest."},
{w:"lucid",pos:"adjective",ipa:"/ˈluːsɪd/",def:"Clear and easy to understand.",ex:"He gave a lucid explanation."},
{w:"mediocre",pos:"adjective",ipa:"/ˌmiːdiˈoʊkər/",def:"Average; not very good.",ex:"The movie was mediocre."},
{w:"nurture",pos:"verb",ipa:"/ˈnɜːrtʃər/",def:"To care for and encourage growth.",ex:"Parents nurture their children's talents."},
{w:"onset",pos:"noun",ipa:"/ˈɑːnset/",def:"The beginning.",ex:"At the onset of winter, prices rise."},
{w:"placate",pos:"verb",ipa:"/ˈpleɪkeɪt/",def:"To calm someone who is angry.",ex:"He tried to placate the upset customer."},
{w:"quench",pos:"verb",ipa:"/kwentʃ/",def:"To satisfy thirst; to put out.",ex:"Cold water quenched his thirst."},
{w:"rebuff",pos:"verb",ipa:"/rɪˈbʌf/",def:"To reject bluntly.",ex:"She rebuffed his offer."},
{w:"scrupulous",pos:"adjective",ipa:"/ˈskruːpjələs/",def:"Diligent and honest.",ex:"He is scrupulous about details."},
{w:"terse",pos:"adjective",ipa:"/tɜːrs/",def:"Brief and to the point.",ex:"He gave a terse reply."},
{w:"unwitting",pos:"adjective",ipa:"/ʌnˈwɪtɪŋ/",def:"Not aware; unintentional.",ex:"He was an unwitting accomplice."},
{w:"vehement",pos:"adjective",ipa:"/ˈviːəmənt/",def:"Showing strong feeling.",ex:"She was vehement in her denial."},
{w:"waver",pos:"verb",ipa:"/ˈweɪvər/",def:"To hesitate; to be unsteady.",ex:"Never waver in your principles."},
{w:"yield",pos:"verb",ipa:"/jiːld/",def:"To produce; to give way.",ex:"The farm yields two crops a year."},
{w:"allure",pos:"noun",ipa:"/əˈlʊr/",def:"Attractive quality.",ex:"The allure of city life drew them."},
{w:"brink",pos:"noun",ipa:"/brɪŋk/",def:"The edge of something.",ex:"The company was on the brink of collapse."},
{w:"coalesce",pos:"verb",ipa:"/ˌkoʊəˈles/",def:"To come together and form one.",ex:"The groups coalesced into a movement."},
{w:"deference",pos:"noun",ipa:"/ˈdefərəns/",def:"Respectful regard.",ex:"In deference to her age, they spoke softly."},
{w:"embolden",pos:"verb",ipa:"/ɪmˈboʊldən/",def:"To give courage.",ex:"Success emboldened him to try again."},
{w:"fallacy",pos:"noun",ipa:"/ˈfæləsi/",def:"A false belief.",ex:"It's a fallacy that money buys happiness."},
{w:"grueling",pos:"adjective",ipa:"/ˈɡruːəlɪŋ/",def:"Extremely tiring.",ex:"The marathon was grueling."},
{w:"herald",pos:"verb",ipa:"/ˈherəld/",def:"To announce; to signal.",ex:"The news heralded a new era."},
{w:"impetus",pos:"noun",ipa:"/ˈɪmpɪtəs/",def:"The force that starts something.",ex:"The crisis gave impetus to reform."},
{w:"jovial",pos:"adjective",ipa:"/ˈdʒoʊviəl/",def:"Cheerful and friendly.",ex:"Our jovial host made everyone laugh."},
{w:"knack",pos:"noun",ipa:"/næk/",def:"A natural skill.",ex:"She has a knack for languages."},
{w:"lament",pos:"verb",ipa:"/ləˈment/",def:"To mourn or regret.",ex:"He lamented the lost opportunity."},
{w:"magnanimous",pos:"adjective",ipa:"/mæɡˈnænɪməs/",def:"Generous in forgiving.",ex:"She was magnanimous in victory."},
{w:"nebulous",pos:"adjective",ipa:"/ˈnebjələs/",def:"Vague; unclear.",ex:"His plans for the future are nebulous."},
{w:"opportune",pos:"adjective",ipa:"/ˌɑːpərˈtuːn/",def:"Well-timed; convenient.",ex:"This is an opportune moment to invest."},
{w:"pinnacle",pos:"noun",ipa:"/ˈpɪnəkəl/",def:"The highest point.",ex:"She reached the pinnacle of her career."},
{w:"quintessential",pos:"adjective",ipa:"/ˌkwɪntəˈsenʃəl/",def:"The perfect example.",ex:"He is the quintessential teacher."},
{w:"rancor",pos:"noun",ipa:"/ˈræŋkər/",def:"Bitter resentment.",ex:"The debate ended without rancor."},
{w:"sagacious",pos:"adjective",ipa:"/səˈɡeɪʃəs/",def:"Wise.",ex:"Her sagacious advice saved the project."},
{w:"tacit",pos:"adjective",ipa:"/ˈtæsɪt/",def:"Understood without being said.",ex:"We had a tacit agreement."},
{w:"unabashed",pos:"adjective",ipa:"/ˌʌnəˈbæʃt/",def:"Not embarrassed.",ex:"He was unabashed about his mistakes."},
{w:"vex",pos:"verb",ipa:"/veks/",def:"To annoy.",ex:"The delay vexed the travelers."},
{w:"wan",pos:"adjective",ipa:"/wɑːn/",def:"Pale; weak.",ex:"She gave a wan smile."},
{w:"xenophobia",pos:"noun",ipa:"/ˌzenəˈfoʊbiə/",def:"Fear of foreigners.",ex:"Education can reduce xenophobia."},
{w:"yoke",pos:"noun",ipa:"/joʊk/",def:"Something that oppresses.",ex:"They threw off the yoke of tyranny."},
{w:"zenith",pos:"noun",ipa:"/ˈziːnɪθ/",def:"The highest point.",ex:"The empire was at its zenith."},
{w:"acumen",pos:"noun",ipa:"/əˈkjuːmən/",def:"Sharp judgment.",ex:"Her business acumen impressed investors."},
{w:"banal",pos:"adjective",ipa:"/bəˈnɑːl/",def:"Unoriginal; boring.",ex:"The lecture was banal."},
{w:"catalyst",pos:"noun",ipa:"/ˈkætəlɪst/",def:"Something that speeds up change.",ex:"The protest was a catalyst for reform."},
{w:"defunct",pos:"adjective",ipa:"/dɪˈfʌŋkt/",def:"No longer working or existing.",ex:"The company is defunct."},
{w:"effervescent",pos:"adjective",ipa:"/ˌefərˈvesənt/",def:"Bubbly; lively.",ex:"Her effervescent personality lit up the room."},
{w:"frugal",pos:"adjective",ipa:"/ˈfruːɡəl/",def:"Careful with money.",ex:"He is frugal but not cheap."},
{w:"garrulous",pos:"adjective",ipa:"/ˈɡærələs/",def:"Very talkative.",ex:"The garrulous driver told stories the whole ride."},
{w:"hackneyed",pos:"adjective",ipa:"/ˈhæknid/",def:"Overused; clichéd.",ex:"Avoid hackneyed phrases in your writing."},
{w:"inane",pos:"adjective",ipa:"/ɪˈneɪn/",def:"Silly; meaningless.",ex:"He made an inane comment."},
{w:"jostle",pos:"verb",ipa:"/ˈdʒɑːsəl/",def:"To push roughly.",ex:"Fans jostled for a better view."},
{w:"kinetic",pos:"adjective",ipa:"/kɪˈnetɪk/",def:"Relating to motion; energetic.",ex:"The dance had a kinetic energy."},
{w:"lurid",pos:"adjective",ipa:"/ˈlʊrɪd/",def:"Shocking and sensational.",ex:"The tabloid printed lurid details."},
{w:"morose",pos:"adjective",ipa:"/məˈroʊs/",def:"Gloomy.",ex:"He was morose after the defeat."},
{w:"nefarious",pos:"adjective",ipa:"/nɪˈferiəs/",def:"Wicked.",ex:"The villain had a nefarious plan."},
{w:"obfuscate",pos:"verb",ipa:"/ˈɑːbfəskeɪt/",def:"To make unclear.",ex:"Politicians often obfuscate the truth."},
{w:"paragon",pos:"noun",ipa:"/ˈpærəɡɑːn/",def:"A perfect example.",ex:"She is a paragon of patience."},
{w:"quixotic",pos:"adjective",ipa:"/kwɪkˈsɑːtɪk/",def:"Unrealistically idealistic.",ex:"His quixotic quest failed."},
{w:"respite",pos:"noun",ipa:"/ˈrespɪt/",def:"A short rest.",ex:"The weekend gave us a brief respite."},
{w:"stoic",pos:"adjective",ipa:"/ˈstoʊɪk/",def:"Enduring pain without complaint.",ex:"She remained stoic throughout."},
{w:"tirade",pos:"noun",ipa:"/ˈtaɪreɪd/",def:"A long angry speech.",ex:"He launched into a tirade."},
{w:"unctuous",pos:"adjective",ipa:"/ˈʌŋktʃuəs/",def:"Excessively flattering.",ex:"The unctuous salesman annoyed us."},
{w:"vacillate",pos:"verb",ipa:"/ˈvæsɪleɪt/",def:"To waver between options.",ex:"Stop vacillating and decide."},
{w:"winsome",pos:"adjective",ipa:"/ˈwɪnsəm/",def:"Charming.",ex:"Her winsome smile won them over."},
{w:"yammer",pos:"verb",ipa:"/ˈjæmər/",def:"To talk loudly and persistently.",ex:"He yammered about his problems."},
{w:"zany",pos:"adjective",ipa:"/ˈzeɪni/",def:"Crazy and funny.",ex:"The zany comedy had us laughing."},
{w:"accolade",pos:"noun",ipa:"/ˈækəleɪd/",def:"An award or praise.",ex:"She received accolades for her research."},
{w:"brevity",pos:"noun",ipa:"/ˈbrevəti/",def:"Briefness.",ex:"Brevity is valued in business writing."},
{w:"capricious",pos:"adjective",ipa:"/kəˈprɪʃəs/",def:"Changing mood quickly.",ex:"The capricious weather ruined our plans."},
{w:"daunt",pos:"verb",ipa:"/dɔːnt/",def:"To intimidate.",ex:"The challenge did not daunt her."},
{w:"ebullient",pos:"adjective",ipa:"/ɪˈbʌliənt/",def:"Cheerful and full of energy.",ex:"The ebullient fans celebrated."},
{w:"fathom",pos:"verb",ipa:"/ˈfæðəm/",def:"To understand deeply.",ex:"I can't fathom why he left."},
{w:"grimace",pos:"noun",ipa:"/ˈɡrɪməs/",def:"A twisted facial expression.",ex:"He grimaced at the bitter taste."},
{w:"haphazard",pos:"adjective",ipa:"/hæpˈhæzərd/",def:"Random; disorganized.",ex:"The files were stored in a haphazard way."},
{w:"illicit",pos:"adjective",ipa:"/ɪˈlɪsɪt/",def:"Illegal.",ex:"He was arrested for illicit trading."},
{w:"judicious",pos:"adjective",ipa:"/dʒuːˈdɪʃəs/",def:"Showing good judgment.",ex:"She made a judicious decision."},
{w:"kudos",pos:"noun",ipa:"/ˈkuːdɑːs/",def:"Praise.",ex:"Kudos to the team for finishing early."},
{w:"lethargic",pos:"adjective",ipa:"/ləˈθɑːrdʒɪk/",def:"Sluggish; tired.",ex:"The heat made us lethargic."},
{w:"mellifluous",pos:"adjective",ipa:"/məˈlɪfluəs/",def:"Sweet-sounding.",ex:"Her mellifluous voice soothed the baby."},
{w:"nonchalant",pos:"adjective",ipa:"/ˌnɑːnʃəˈlɑːnt/",def:"Calm and relaxed.",ex:"He gave a nonchalant shrug."},
{w:"ostentatious",pos:"adjective",ipa:"/ˌɑːstənˈteɪʃəs/",def:"Showy.",ex:"Their ostentatious mansion impressed no one."},
{w:"permeate",pos:"verb",ipa:"/ˈpɜːrmieɪt/",def:"To spread through.",ex:"The smell of coffee permeated the house."},
{w:"quagmire",pos:"noun",ipa:"/ˈkwæɡmaɪər/",def:"A difficult situation.",ex:"The project became a bureaucratic quagmire."},
{w:"renege",pos:"verb",ipa:"/rɪˈneɡ/",def:"To go back on a promise.",ex:"He reneged on the deal."},
{w:"solicitous",pos:"adjective",ipa:"/səˈlɪsɪtəs/",def:"Showing care; attentive.",ex:"The solicitous nurse checked on him hourly."},
{w:"tenet",pos:"noun",ipa:"/ˈtenɪt/",def:"A core belief.",ex:"Honesty is a central tenet of the company."},
{w:"upbraid",pos:"verb",ipa:"/ʌpˈbreɪd/",def:"To scold.",ex:"She upbraided him for being late."},
{w:"vilify",pos:"verb",ipa:"/ˈvɪlɪfaɪ/",def:"To speak badly of.",ex:"The press vilified the candidate."},
{w:"watershed",pos:"noun",ipa:"/ˈwɔːtərʃed/",def:"A turning point.",ex:"The election was a watershed moment."},
{w:"yore",pos:"noun",ipa:"/jɔːr/",def:"Time long past.",ex:"In days of yore, letters took weeks."},
{w:"abate",pos:"verb",ipa:"/əˈbeɪt/",def:"To lessen.",ex:"The storm finally abated."},
{w:"belie",pos:"verb",ipa:"/bɪˈlaɪ/",def:"To give a false impression of.",ex:"Her smile belied her anger."},
{w:"cajole",pos:"verb",ipa:"/kəˈdʒoʊl/",def:"To persuade gently.",ex:"He cajoled her into attending."},
{w:"deride",pos:"verb",ipa:"/dɪˈraɪd/",def:"To mock.",ex:"Critics derided the proposal."},
{w:"efface",pos:"verb",ipa:"/ɪˈfeɪs/",def:"To erase.",ex:"Time had effaced the inscription."},
{w:"fastidious",pos:"adjective",ipa:"/fæˈstɪdiəs/",def:"Very attentive to detail.",ex:"She is fastidious about grammar."},
{w:"gumption",pos:"noun",ipa:"/ˈɡʌmpʃən/",def:"Initiative; courage.",ex:"It took gumption to start a business."},
{w:"harbinger",pos:"noun",ipa:"/ˈhɑːrbɪndʒər/",def:"A sign of what's coming.",ex:"Robins are harbingers of spring."},
{w:"insipid",pos:"adjective",ipa:"/ɪnˈsɪpɪd/",def:"Lacking flavor or interest.",ex:"The soup was insipid."},
{w:"jettison",pos:"verb",ipa:"/ˈdʒetɪsən/",def:"To throw away.",ex:"They jettisoned the old plan."},
{w:"lobby",pos:"verb",ipa:"/ˈlɑːbi/",def:"To try to influence.",ex:"They lobbied for better funding."},
{w:"languish",pos:"verb",ipa:"/ˈlæŋɡwɪʃ/",def:"To weaken; to suffer neglect.",ex:"The project languished for years."},
{w:"malleable",pos:"adjective",ipa:"/ˈmæliəbəl/",def:"Easily shaped or influenced.",ex:"Young minds are malleable."},
{w:"nascent",pos:"adjective",ipa:"/ˈnæsənt/",def:"Just beginning.",ex:"The nascent industry grew fast."},
{w:"obdurate",pos:"adjective",ipa:"/ˈɑːbdʊrət/",def:"Stubborn.",ex:"He remained obdurate despite the evidence."},
{w:"prodigal",pos:"adjective",ipa:"/ˈprɑːdɪɡəl/",def:"Wasteful.",ex:"His prodigal spending drained his savings."},
{w:"quell",pos:"verb",ipa:"/kwel/",def:"To put an end to.",ex:"Police quelled the riot."},
{w:"relegate",pos:"verb",ipa:"/ˈreləɡeɪt/",def:"To assign to a lower position.",ex:"The files were relegated to storage."},
{w:"solicit",pos:"verb",ipa:"/səˈlɪsɪt/",def:"To ask for.",ex:"They solicited donations."},
{w:"surreptitious",pos:"adjective",ipa:"/ˌsʌrəpˈtɪʃəs/",def:"Secretive.",ex:"He took a surreptitious glance."},
{w:"transient",pos:"adjective",ipa:"/ˈtrænʃənt/",def:"Temporary.",ex:"Fame is transient."},
{w:"undulate",pos:"verb",ipa:"/ˈʌndʒəleɪt/",def:"To move in waves.",ex:"The fields undulated in the wind."},
{w:"veracity",pos:"noun",ipa:"/vəˈræsəti/",def:"Truthfulness.",ex:"Reporters questioned the veracity of the claim."},
{w:"wistful",pos:"adjective",ipa:"/ˈwɪstfəl/",def:"Sadly longing.",ex:"She gave a wistful sigh."},
{w:"exonerate",pos:"verb",ipa:"/ɪɡˈzɑːnəreɪt/",def:"To clear of blame.",ex:"DNA evidence exonerated him."},
{w:"zeal",pos:"noun",ipa:"/ziːl/",def:"Great enthusiasm.",ex:"She pursued her studies with zeal."},
{w:"absolve",pos:"verb",ipa:"/əbˈzɑːlv/",def:"To free from blame.",ex:"The inquiry absolved him."},
{w:"bucolic",pos:"adjective",ipa:"/bjuːˈkɑːlɪk/",def:"Rural and pleasant.",ex:"They retired to a bucolic village."},
{w:"copious",pos:"adjective",ipa:"/ˈkoʊpiəs/",def:"Abundant.",ex:"She took copious notes."},
{w:"dearth",pos:"noun",ipa:"/dɜːrθ/",def:"A lack.",ex:"There is a dearth of affordable housing."},
{w:"endemic",pos:"adjective",ipa:"/enˈdemɪk/",def:"Regularly found in a region.",ex:"Malaria is endemic in the region."},
{w:"florid",pos:"adjective",ipa:"/ˈflɔːrɪd/",def:"Overly ornate.",ex:"He writes in a florid style."},
{w:"gregarious",pos:"adjective",ipa:"/ɡreˈɡeriəs/",def:"Sociable.",ex:"She is gregarious and loves parties."},
{w:"hyperbole",pos:"noun",ipa:"/haɪˈpɜːrbəli/",def:"Exaggeration.",ex:"Calling it “the worst ever” is hyperbole."},
{w:"immutable",pos:"adjective",ipa:"/ɪˈmjuːtəbəl/",def:"Unchangeable.",ex:"The laws of physics are immutable."},
{w:"juxtapose",pos:"verb",ipa:"/ˌdʒʌkstəˈpoʊz/",def:"To place side by side for contrast.",ex:"The exhibit juxtaposes old and new."},
{w:"kismet",pos:"noun",ipa:"/ˈkɪzmet/",def:"Fate.",ex:"Meeting her was pure kismet."},
{w:"loquacious",pos:"adjective",ipa:"/loʊˈkweɪʃəs/",def:"Very talkative.",ex:"The loquacious guide entertained us."},
{w:"magnate",pos:"noun",ipa:"/ˈmæɡneɪt/",def:"A powerful businessperson.",ex:"The oil magnate donated millions."},
{w:"neophyte",pos:"noun",ipa:"/ˈniːəfaɪt/",def:"A beginner.",ex:"As a neophyte cook, she burned the rice."},
{w:"onerous",pos:"adjective",ipa:"/ˈɑːnərəs/",def:"Burdensome.",ex:"The onerous workload exhausted the team."},
{w:"parsimonious",pos:"adjective",ipa:"/ˌpɑːrsɪˈmoʊniəs/",def:"Very unwilling to spend.",ex:"His parsimonious habits annoyed his friends."},
{w:"quarry",pos:"noun",ipa:"/ˈkwɔːri/",def:"Something hunted.",ex:"The detective pursued his quarry."},
{w:"rhapsody",pos:"noun",ipa:"/ˈræpsədi/",def:"Great delight.",ex:"She was in rhapsody over the news."},
{w:"sanguine",pos:"adjective",ipa:"/ˈsæŋɡwɪn/",def:"Optimistic.",ex:"He is sanguine about the future."},
{w:"tenuous",pos:"adjective",ipa:"/ˈtenjuəs/",def:"Weak; shaky.",ex:"Their claim to the land is tenuous."},
{w:"umbrage",pos:"noun",ipa:"/ˈʌmbrɪdʒ/",def:"Offense.",ex:"He took umbrage at the remark."},
{w:"verisimilitude",pos:"noun",ipa:"/ˌverɪsɪˈmɪlɪtuːd/",def:"Appearance of truth.",ex:"The novel lacks verisimilitude."},
{w:"wheedle",pos:"verb",ipa:"/ˈwiːdəl/",def:"To persuade with flattery.",ex:"She wheedled him into helping."},
{w:"yesteryear",pos:"noun",ipa:"/ˈjestəryɪr/",def:"The past.",ex:"The fashions of yesteryear returned."},
{w:"abhor",pos:"verb",ipa:"/æbˈhɔːr/",def:"To hate deeply.",ex:"She abhors cruelty."},
{w:"braggadocio",pos:"noun",ipa:"/ˌbræɡəˈdoʊtʃoʊ/",def:"Boastful talk.",ex:"His braggadocio annoyed everyone."},
{w:"conciliatory",pos:"adjective",ipa:"/kənˈsɪliətɔːri/",def:"Intended to reconcile.",ex:"She made a conciliatory gesture."},
{w:"desiccate",pos:"verb",ipa:"/ˈdesɪkeɪt/",def:"To dry out.",ex:"The heat desiccated the crops."},
{w:"ephemeral",pos:"adjective",ipa:"/ɪˈfemərəl/",def:"Very short-lived.",ex:"Fashion trends are ephemeral."},
{w:"frenetic",pos:"adjective",ipa:"/frəˈnetɪk/",def:"Wildly excited or active.",ex:"The frenetic pace tired us."},
{w:"grandiose",pos:"adjective",ipa:"/ˈɡrændioʊs/",def:"Overly grand.",ex:"He had grandiose plans."},
{w:"hubris",pos:"noun",ipa:"/ˈhjuːbrɪs/",def:"Excessive pride.",ex:"His hubris led to his downfall."},
{w:"incongruous",pos:"adjective",ipa:"/ɪnˈkɑːŋɡruəs/",def:"Out of place.",ex:"An incongruous modern lamp sat in the antique room."},
{w:"jocular",pos:"adjective",ipa:"/ˈdʒɑːkjələr/",def:"Joking.",ex:"He made a jocular remark."},
{w:"laconic",pos:"adjective",ipa:"/ləˈkɑːnɪk/",def:"Using few words.",ex:"His laconic reply ended the discussion."},
{w:"mawkish",pos:"adjective",ipa:"/ˈmɔːkɪʃ/",def:"Overly sentimental.",ex:"The movie's ending was mawkish."},
{w:"noxious",pos:"adjective",ipa:"/ˈnɑːkʃəs/",def:"Harmful.",ex:"The factory emitted noxious fumes."},
{w:"opalescent",pos:"adjective",ipa:"/ˌoʊpəˈlesənt/",def:"Shimmering like an opal.",ex:"The opalescent sea glowed."},
{w:"petulant",pos:"adjective",ipa:"/ˈpetʃələnt/",def:"Childishly sulky.",ex:"The petulant teen slammed the door."},
{w:"querulous",pos:"adjective",ipa:"/ˈkwerələs/",def:"Complaining.",ex:"The querulous customer demanded a manager."},
{w:"recalcitrant",pos:"adjective",ipa:"/rɪˈkælsɪtrənt/",def:"Stubbornly resistant.",ex:"The recalcitrant student refused help."},
{w:"salubrious",pos:"adjective",ipa:"/səˈluːbriəs/",def:"Healthful.",ex:"The salubrious mountain air revived him."},
{w:"trepidation",pos:"noun",ipa:"/ˌtrepɪˈdeɪʃən/",def:"Fearful uncertainty.",ex:"She opened the letter with trepidation."},
{w:"unseemly",pos:"adjective",ipa:"/ʌnˈsiːmli/",def:"Improper.",ex:"His unseemly outburst shocked us."},
{w:"vitriolic",pos:"adjective",ipa:"/ˌvɪtriˈɑːlɪk/",def:"Bitterly critical.",ex:"The review was vitriolic."},
{w:"wanton",pos:"adjective",ipa:"/ˈwɑːntən/",def:"Deliberate and unprovoked.",ex:"It was a wanton act of vandalism."},
{w:"abstruse",pos:"adjective",ipa:"/æbˈstruːs/",def:"Hard to understand.",ex:"The lecture was abstruse."},
{w:"bromide",pos:"noun",ipa:"/ˈbroʊmaɪd/",def:"A trite remark.",ex:"His speech was full of bromides."},
{w:"chicanery",pos:"noun",ipa:"/ʃɪˈkeɪnəri/",def:"Trickery.",ex:"The election was marred by chicanery."},
{w:"diatribe",pos:"noun",ipa:"/ˈdaɪətraɪb/",def:"A harsh criticism.",ex:"The article was a diatribe against the mayor."},
{w:"elegiac",pos:"adjective",ipa:"/ˌelɪˈdʒaɪək/",def:"Mournful.",ex:"He wrote an elegiac poem."},
{w:"feckless",pos:"adjective",ipa:"/ˈfekləs/",def:"Irresponsible.",ex:"The feckless manager ignored complaints."},
{w:"gallivant",pos:"verb",ipa:"/ˈɡælɪvænt/",def:"To travel for pleasure.",ex:"They gallivanted across Europe."},
{w:"hedonism",pos:"noun",ipa:"/ˈhiːdənɪzəm/",def:"Pursuit of pleasure.",ex:"He rejected hedonism for simplicity."},
{w:"iconoclast",pos:"noun",ipa:"/aɪˈkɑːnəklæst/",def:"One who challenges traditions.",ex:"She was an iconoclast in the art world."},
{w:"jejune",pos:"adjective",ipa:"/dʒəˈdʒuːn/",def:"Naive; dull.",ex:"His jejune opinions bored us."},
{w:"kowtow",pos:"verb",ipa:"/ˌkaʊˈtaʊ/",def:"To act submissively.",ex:"She refused to kowtow to the boss."},
{w:"lugubrious",pos:"adjective",ipa:"/ləˈɡuːbriəs/",def:"Mournful.",ex:"The lugubrious music set the tone."},
{w:"meretricious",pos:"adjective",ipa:"/ˌmerɪˈtrɪʃəs/",def:"Flashy but worthless.",ex:"The meretricious ad fooled no one."},
{w:"nugatory",pos:"adjective",ipa:"/ˈnuːɡətɔːri/",def:"Worthless.",ex:"His efforts were nugatory."},
{w:"ossify",pos:"verb",ipa:"/ˈɑːsɪfaɪ/",def:"To become rigid.",ex:"Bureaucracy ossified the process."},
{w:"pusillanimous",pos:"adjective",ipa:"/ˌpjuːsɪˈlænɪməs/",def:"Cowardly.",ex:"It was a pusillanimous decision."},
{w:"quiescent",pos:"adjective",ipa:"/kwiˈesənt/",def:"Inactive; quiet.",ex:"The volcano is quiescent."},
{w:"redolent",pos:"adjective",ipa:"/ˈredələnt/",def:"Reminding one of; fragrant.",ex:"The air was redolent of pine."},
{w:"sententious",pos:"adjective",ipa:"/senˈtenʃəs/",def:"Preachy.",ex:"His sententious lecture bored us."},
{w:"torpor",pos:"noun",ipa:"/ˈtɔːrpər/",def:"Mental sluggishness.",ex:"The heat induced torpor."},
{w:"ubiquitous",pos:"adjective",ipa:"/juːˈbɪkwɪtəs/",def:"Everywhere.",ex:"Smartphones are ubiquitous."},
{w:"vacuous",pos:"adjective",ipa:"/ˈvækjuəs/",def:"Empty-headed.",ex:"His vacuous smile revealed nothing."},
{w:"waggish",pos:"adjective",ipa:"/ˈwæɡɪʃ/",def:"Playfully humorous.",ex:"His waggish remarks lightened the mood."},
{w:"zephyr",pos:"noun",ipa:"/ˈzefər/",def:"A gentle breeze.",ex:"A zephyr cooled the evening."},
{w:"affectation",pos:"noun",ipa:"/ˌæfekˈteɪʃən/",def:"Artificial behavior.",ex:"His accent is an affectation."},
{w:"bowdlerize",pos:"verb",ipa:"/ˈbaʊdləraɪz/",def:"To censor.",ex:"The film was bowdlerized for TV."},
{w:"credulous",pos:"adjective",ipa:"/ˈkredʒələs/",def:"Too ready to believe.",ex:"Credulous buyers fell for the scam."},
{w:"desultory",pos:"adjective",ipa:"/ˈdesəltɔːri/",def:"Random; disconnected.",ex:"They made desultory conversation."},
{w:"ersatz",pos:"adjective",ipa:"/ˈerzɑːts/",def:"Artificial substitute.",ex:"The ersatz leather cracked."},
{w:"fulminate",pos:"verb",ipa:"/ˈfʊlmɪneɪt/",def:"To protest loudly.",ex:"She fulminated against the decision."},
{w:"grandiloquent",pos:"adjective",ipa:"/ɡrænˈdɪləkwənt/",def:"Pompous in speech.",ex:"His grandiloquent speech bored us."},
{w:"hegemony",pos:"noun",ipa:"/hɪˈdʒeməni/",def:"Dominance.",ex:"The company sought market hegemony."},
{w:"importune",pos:"verb",ipa:"/ˌɪmpɔːrˈtuːn/",def:"To beg urgently.",ex:"He importuned her for help."},
{w:"jibe",pos:"noun",ipa:"/dʒaɪb/",def:"A taunting remark.",ex:"He ignored their jibes."},
{w:"klutz",pos:"noun",ipa:"/klʌts/",def:"A clumsy person.",ex:"I'm such a klutz in the kitchen."},
{w:"lachrymose",pos:"adjective",ipa:"/ˈlækrɪmoʊs/",def:"Tearful.",ex:"The lachrymose farewell moved us."},
{w:"mendacious",pos:"adjective",ipa:"/menˈdeɪʃəs/",def:"Lying.",ex:"His mendacious claims were exposed."},
{w:"noisome",pos:"adjective",ipa:"/ˈnɔɪsəm/",def:"Smelly; offensive.",ex:"The noisome alley was avoided."},
{w:"objurgate",pos:"verb",ipa:"/ˈɑːbdʒərɡeɪt/",def:"To scold harshly.",ex:"The coach objurgated the team."},
{w:"paucity",pos:"noun",ipa:"/ˈpɔːsəti/",def:"Scarcity.",ex:"There is a paucity of evidence."},
{w:"quisling",pos:"noun",ipa:"/ˈkwɪzlɪŋ/",def:"A traitor.",ex:"He was branded a quisling."},
{w:"repudiate",pos:"verb",ipa:"/rɪˈpjuːdieɪt/",def:"To reject.",ex:"She repudiated the accusation."},
{w:"sybarite",pos:"noun",ipa:"/ˈsɪbəraɪt/",def:"A luxury lover.",ex:"The sybarite booked a five-star suite."},
{w:"temerity",pos:"noun",ipa:"/təˈmerəti/",def:"Boldness.",ex:"He had the temerity to complain."},
{w:"upshot",pos:"noun",ipa:"/ˈʌpʃɑːt/",def:"The final result.",ex:"The upshot was a compromise."},
{w:"vituperate",pos:"verb",ipa:"/vaɪˈtuːpəreɪt/",def:"To blame abusively.",ex:"Critics vituperated the film."},
{w:"wherewithal",pos:"noun",ipa:"/ˈwerwɪðɔːl/",def:"The means to do something.",ex:"She lacked the wherewithal to travel."},
{w:"abrogate",pos:"verb",ipa:"/ˈæbrəɡeɪt/",def:"To abolish.",ex:"The treaty was abrogated."},
{w:"burnish",pos:"verb",ipa:"/ˈbɜːrnɪʃ/",def:"To polish.",ex:"He burnished his reputation."},
{w:"construe",pos:"verb",ipa:"/kənˈstruː/",def:"To interpret.",ex:"Her silence was construed as agreement."},
{w:"deign",pos:"verb",ipa:"/deɪn/",def:"To do something beneath one's dignity.",ex:"He didn't deign to reply."},
{w:"excoriate",pos:"verb",ipa:"/ɪkˈskɔːrieɪt/",def:"To criticize severely.",ex:"The report excoriated the agency."},
{w:"fungible",pos:"adjective",ipa:"/ˈfʌndʒəbəl/",def:"Interchangeable.",ex:"Money is fungible."},
{w:"gainsay",pos:"verb",ipa:"/ˌɡeɪnˈseɪ/",def:"To deny.",ex:"None could gainsay the facts."},
{w:"hector",pos:"verb",ipa:"/ˈhektər/",def:"To bully.",ex:"He hectored his staff."},
{w:"inveigh",pos:"verb",ipa:"/ɪnˈveɪ/",def:"To protest strongly.",ex:"She inveighed against corruption."},
{w:"juncture",pos:"noun",ipa:"/ˈdʒʌŋktʃər/",def:"A critical point.",ex:"At this juncture, we must decide."},
{w:"kvetch",pos:"verb",ipa:"/kvetʃ/",def:"To complain.",ex:"He kvetched about the service."},
{w:"lampoon",pos:"verb",ipa:"/læmˈpuːn/",def:"To mock publicly.",ex:"The cartoon lampooned the mayor."},
{w:"maudlin",pos:"adjective",ipa:"/ˈmɔːdlɪn/",def:"Overly sentimental.",ex:"The maudlin song made her cry."},
{w:"nettlesome",pos:"adjective",ipa:"/ˈnetəlsəm/",def:"Irritating.",ex:"A nettlesome problem persisted."},
{w:"officious",pos:"adjective",ipa:"/əˈfɪʃəs/",def:"Overly eager to help; meddling.",ex:"The officious clerk annoyed us."},
{w:"promulgate",pos:"verb",ipa:"/ˈprɑːməlɡeɪt/",def:"To announce officially.",ex:"The law was promulgated in June."},
{w:"quotidian",pos:"adjective",ipa:"/kwoʊˈtɪdiən/",def:"Everyday; ordinary.",ex:"She wrote about quotidian life."},
{w:"ribald",pos:"adjective",ipa:"/ˈrɪbəld/",def:"Coarsely humorous.",ex:"His ribald jokes offended some."},
{w:"sartorial",pos:"adjective",ipa:"/sɑːrˈtɔːriəl/",def:"Relating to clothing.",ex:"He is known for sartorial elegance."},
{w:"traduce",pos:"verb",ipa:"/trəˈduːs/",def:"To slander.",ex:"Rivals traduced her reputation."},
{w:"untoward",pos:"adjective",ipa:"/ʌnˈtɔːrd/",def:"Unexpected and unpleasant.",ex:"Nothing untoward happened."},
{w:"verbiage",pos:"noun",ipa:"/ˈvɜːrbiɪdʒ/",def:"Excessive wordiness.",ex:"Cut the verbiage from your essay."},
{w:"windfall",pos:"noun",ipa:"/ˈwɪndfɔːl/",def:"Unexpected good fortune.",ex:"The refund was a windfall."},
{w:"abeyance",pos:"noun",ipa:"/əˈbeɪəns/",def:"Temporary suspension.",ex:"The plan is in abeyance."},
{w:"adulation",pos:"noun",ipa:"/ˌædʒəˈleɪʃən/",def:"Excessive praise.",ex:"The singer basked in adulation."},
{w:"bellicose",pos:"adjective",ipa:"/ˈbelɪkoʊs/",def:"Warlike.",ex:"His bellicose speech alarmed allies."},
{w:"calumny",pos:"noun",ipa:"/ˈkæləmni/",def:"Slander.",ex:"She sued over the calumny."},
{w:"deleterious",pos:"adjective",ipa:"/ˌdeləˈtɪriəs/",def:"Harmful.",ex:"Smoking has deleterious effects."},
{w:"efficacious",pos:"adjective",ipa:"/ˌefɪˈkeɪʃəs/",def:"Effective.",ex:"The treatment proved efficacious."},
{w:"fatuous",pos:"adjective",ipa:"/ˈfætʃuəs/",def:"Foolish.",ex:"He made a fatuous remark."},
{w:"gauche",pos:"adjective",ipa:"/ɡoʊʃ/",def:"Socially awkward.",ex:"His gauche manners embarrassed him."},
{w:"harangue",pos:"noun",ipa:"/həˈræŋ/",def:"A lengthy scolding.",ex:"We endured his harangue."},
{w:"insouciant",pos:"adjective",ipa:"/ɪnˈsuːsiənt/",def:"Carefree.",ex:"She gave an insouciant shrug."},
{w:"jeremiad",pos:"noun",ipa:"/ˌdʒerəˈmaɪəd/",def:"A long lament.",ex:"His jeremiad bored the audience."},
{w:"knavery",pos:"noun",ipa:"/ˈneɪvəri/",def:"Dishonesty.",ex:"The knavery was exposed."},
{w:"limpid",pos:"adjective",ipa:"/ˈlɪmpɪd/",def:"Clear.",ex:"Her limpid prose was a joy."},
{w:"minatory",pos:"adjective",ipa:"/ˈmɪnətɔːri/",def:"Threatening.",ex:"He sent a minatory letter."},
{w:"nocturnal",pos:"adjective",ipa:"/nɑːkˈtɜːrnəl/",def:"Active at night.",ex:"Owls are nocturnal."},
{w:"obtuse",pos:"adjective",ipa:"/ɑːbˈtuːs/",def:"Slow to understand.",ex:"Are you being deliberately obtuse?"},
{w:"puerile",pos:"adjective",ipa:"/ˈpjʊrəl/",def:"Childish.",ex:"Stop your puerile bickering."},
{w:"qualm",pos:"noun",ipa:"/kwɑːm/",def:"A misgiving.",ex:"She had no qualms about leaving."},
{w:"raconteur",pos:"noun",ipa:"/ˌrækɑːnˈtɜːr/",def:"A skilled storyteller.",ex:"Grandpa was a born raconteur."},
{w:"scion",pos:"noun",ipa:"/ˈsaɪən/",def:"A descendant of a notable family.",ex:"The scion inherited the firm."},
{w:"truculent",pos:"adjective",ipa:"/ˈtrʌkjələnt/",def:"Aggressive.",ex:"The truculent teen argued constantly."},
{w:"untenable",pos:"adjective",ipa:"/ʌnˈtenəbəl/",def:"Indefensible.",ex:"His position became untenable."},
{w:"vainglorious",pos:"adjective",ipa:"/ˌveɪnˈɡlɔːriəs/",def:"Boastful.",ex:"The vainglorious athlete bragged."},
{w:"welter",pos:"noun",ipa:"/ˈweltər/",def:"A confused mass.",ex:"A welter of details overwhelmed us."},
{w:"antediluvian",pos:"adjective",ipa:"/ˌæntɪdəˈluːviən/",def:"Ridiculously old-fashioned.",ex:"His antediluvian views shocked us."},
{w:"bloviate",pos:"verb",ipa:"/ˈbloʊvieɪt/",def:"To talk at length pompously.",ex:"The candidate bloviated for an hour."},
{w:"celerity",pos:"noun",ipa:"/səˈlerəti/",def:"Swiftness.",ex:"She acted with celerity."},
{w:"disabuse",pos:"verb",ipa:"/ˌdɪsəˈbjuːz/",def:"To free from a false belief.",ex:"Let me disabuse you of that notion."},
{w:"encomium",pos:"noun",ipa:"/enˈkoʊmiəm/",def:"Glowing praise.",ex:"The review was an encomium."},
{w:"flummox",pos:"verb",ipa:"/ˈflʌməks/",def:"To confuse.",ex:"The question flummoxed him."},
{w:"gloaming",pos:"noun",ipa:"/ˈɡloʊmɪŋ/",def:"Twilight.",ex:"We walked home in the gloaming."},
{w:"hagiography",pos:"noun",ipa:"/ˌhæɡiˈɑːɡrəfi/",def:"An uncritical biography.",ex:"The book was pure hagiography."},
{w:"imbue",pos:"verb",ipa:"/ɪmˈbjuː/",def:"To fill with a quality.",ex:"The story is imbued with hope."},
{w:"jocund",pos:"adjective",ipa:"/ˈdʒɑːkənd/",def:"Cheerful.",ex:"A jocund mood filled the room."},
{w:"ken",pos:"noun",ipa:"/ken/",def:"Range of knowledge.",ex:"That topic is beyond my ken."},
{w:"legerdemain",pos:"noun",ipa:"/ˌledʒərdəˈmeɪn/",def:"Sleight of hand; trickery.",ex:"The contract was pure legerdemain."},
{w:"mull",pos:"verb",ipa:"/mʌl/",def:"To think over.",ex:"Let me mull it over."},
{w:"niggle",pos:"verb",ipa:"/ˈnɪɡəl/",def:"To cause slight worry.",ex:"A doubt niggled at him."},
{w:"oneiric",pos:"adjective",ipa:"/oʊˈnaɪrɪk/",def:"Dreamlike.",ex:"The film had an oneiric quality."}
];
var SENTENCES = [
{s:"Would you mind clarifying that?",m:"A polite way to ask for an explanation."},
{s:"I wanted to follow up on our conversation.",m:"Use this when contacting someone again about a previous topic."},
{s:"Please don't hesitate to reach out.",m:"A formal way to say “contact me anytime.”"},
{s:"I appreciate your prompt response.",m:"Thank someone for replying quickly. (email-friendly)"},
{s:"Could you shed some light on this?",m:"Ask someone to explain something unclear."},
{s:"Let's touch base next week.",m:"Let's talk again next week to share updates."},
{s:"I'm swamped with work right now.",m:"I'm extremely busy. (informal)"},
{s:"The ball is in your court.",m:"It's your turn to act or decide."},
{s:"Don't beat around the bush.",m:"Say what you mean directly."},
{s:"Don't jump to conclusions.",m:"Don't decide before you know the facts."},
{s:"Let's play it by ear.",m:"Let's decide later depending on the situation."},
{s:"I'm torn between two options.",m:"I can't decide between two choices."},
{s:"That backfired on me.",m:"My plan produced the opposite result."},
{s:"Food for thought.",m:"Something worth thinking about."},
{s:"That's the elephant in the room.",m:"The obvious problem nobody mentions."},
{s:"You hit the nail on the head.",m:"You said exactly the right thing."},
{s:"I had to bite the bullet.",m:"I forced myself to do something unpleasant."},
{s:"I've been burning the midnight oil.",m:"I've been working late into the night."},
{s:"It cost an arm and a leg.",m:"It was extremely expensive."},
{s:"Don't cut corners on quality.",m:"Don't do things cheaply or carelessly."},
{s:"I'm getting the hang of it.",m:"I'm learning how to do it."},
{s:"Let's go the extra mile.",m:"Let's make more effort than expected."},
{s:"In the long run, it's worth it.",m:"Over a long time, it will pay off."},
{s:"Don't miss the boat on this.",m:"Don't miss this opportunity."},
{s:"We need to get on the same page.",m:"We need to agree and understand each other."},
{s:"He showed up out of the blue.",m:"He appeared unexpectedly."},
{s:"It's not rocket science.",m:"It's not that difficult."},
{s:"I'm feeling a bit under the weather.",m:"I'm feeling slightly sick. (polite)"},
{s:"That's easier said than done.",m:"Saying it is easier than doing it."},
{s:"Actions speak louder than words.",m:"What you do matters more than what you say."},
{s:"It's a win-win situation.",m:"Both sides benefit."},
{s:"I can't put my finger on it.",m:"I sense something but can't explain what."},
{s:"Let's get down to business.",m:"Let's start working seriously."},
{s:"Time is of the essence.",m:"We must act quickly. (formal)"},
{s:"I'll keep you in the loop.",m:"I'll keep you informed."},
{s:"That rings a bell.",m:"That sounds familiar."},
{s:"I'm all ears.",m:"I'm listening carefully."},
{s:"It's a blessing in disguise.",m:"Something bad that turned out well."},
{s:"Don't count your chickens before they hatch.",m:"Don't assume success too early."},
{s:"The early bird catches the worm.",m:"People who act early get the advantage."},
{s:"When in Rome, do as the Romans do.",m:"Follow local customs when visiting somewhere new."},
{s:"Better safe than sorry.",m:"It's wiser to be careful."},
{s:"Two heads are better than one.",m:"Working together produces better ideas."},
{s:"A picture is worth a thousand words.",m:"Images explain better than descriptions."},
{s:"No pain, no gain.",m:"You must work hard to succeed."},
{s:"Kill two birds with one stone.",m:"Do two things with one action."},
{s:"Where there's a will, there's a way.",m:"If you want something enough, you'll find a way."},
{s:"Don't put all your eggs in one basket.",m:"Don't risk everything on one plan."},
{s:"Every cloud has a silver lining.",m:"Something good comes from bad situations."},
{s:"You can't judge a book by its cover.",m:"Don't judge by appearance."},
{s:"The grass is always greener on the other side.",m:"Other people's situations look better than they really are."},
{s:"Beggars can't be choosers.",m:"Be grateful for what you get when you have no choice."},
{s:"A penny saved is a penny earned.",m:"Saving money is like earning it."},
{s:"Look before you leap.",m:"Think carefully before you act."},
{s:"Honesty is the best policy.",m:"Telling the truth is always wisest."},
{s:"Rome wasn't built in a day.",m:"Great things take time."},
{s:"Curiosity killed the cat.",m:"Being too nosy can cause trouble. (playful warning)"},
{s:"Don't bite off more than you can chew.",m:"Don't take on more than you can handle."},
{s:"Let sleeping dogs lie.",m:"Don't restart old conflicts."},
{s:"The best of both worlds.",m:"The advantages of two different situations at once."},
{s:"Let's get the ball rolling.",m:"Let's start."},
{s:"I'm on the fence about it.",m:"I can't decide."},
{s:"It's a no-brainer.",m:"The decision is obvious."},
{s:"Don't get cold feet.",m:"Don't become too nervous to act."},
{s:"Let's sleep on it.",m:"Let's decide tomorrow."},
{s:"I'm running on fumes.",m:"I'm exhausted but continuing. (informal)"},
{s:"That hit home.",m:"That affected me deeply."},
{s:"Let's cut to the chase.",m:"Let's get to the point."},
{s:"I'm in over my head.",m:"This is too difficult for me."},
{s:"Don't rock the boat.",m:"Don't cause trouble."},
{s:"It's water under the bridge.",m:"It's in the past; let's move on."},
{s:"I'm burning out.",m:"I'm exhausted from overwork."},
{s:"Let's think outside the box.",m:"Let's be creative."},
{s:"I'm at a crossroads.",m:"I must make an important decision."},
{s:"Don't put words in my mouth.",m:"Don't claim I said something I didn't."},
{s:"It's a slippery slope.",m:"One small step could lead to worse things."},
{s:"I'm walking on eggshells.",m:"I'm being very careful not to upset someone."},
{s:"Let's bury the hatchet.",m:"Let's make peace."},
{s:"I'm pulling your leg.",m:"I'm joking."},
{s:"Don't make a mountain out of a molehill.",m:"Don't exaggerate a small problem."},
{s:"It's like finding a needle in a haystack.",m:"It's nearly impossible to find."},
{s:"I'm snowed under with emails.",m:"I have too many emails."},
{s:"Let's iron out the details.",m:"Let's resolve the small problems."},
{s:"I'm feeling blue.",m:"I'm feeling sad."},
{s:"Don't throw in the towel.",m:"Don't give up."},
{s:"It's a drop in the bucket.",m:"It's a very small amount."},
{s:"I'm on cloud nine.",m:"I'm extremely happy."},
{s:"Let's call a spade a spade.",m:"Let's speak honestly."},
{s:"I'm stuck between a rock and a hard place.",m:"Both choices are bad."},
{s:"Don't bite the hand that feeds you.",m:"Don't harm those who help you."},
{s:"It's déjà vu all over again.",m:"This feels like it's happened before. (informal)"},
{s:"I'm seeing red.",m:"I'm very angry. (informal)"},
{s:"Let's get our ducks in a row.",m:"Let's organize everything."},
{s:"I'm barking up the wrong tree.",m:"I'm pursuing the wrong idea."},
{s:"It's not my cup of tea.",m:"It's not something I enjoy."},
{s:"I'm all thumbs today.",m:"I'm very clumsy today."},
{s:"Let's hit the road.",m:"Let's leave."},
{s:"I'm down in the dumps.",m:"I'm depressed. (informal)"},
{s:"Don't spill the beans.",m:"Don't reveal the secret."},
{s:"I'm tickled pink.",m:"I'm very pleased. (informal)"},
{s:"Let's paint the town red.",m:"Let's celebrate wildly. (informal)"},
{s:"I'm green with envy.",m:"I'm very jealous."},
{s:"Don't let the cat out of the bag.",m:"Don't reveal the secret."},
{s:"It's a catch-22.",m:"A problem with no good solution."},
{s:"I'm between jobs right now.",m:"A polite way to say unemployed."},
{s:"Let's circle back to this.",m:"Let's discuss this again later."},
{s:"I'm slammed today.",m:"I'm extremely busy. (informal)"},
{s:"Don't reinvent the wheel.",m:"Don't redo what already works."},
{s:"It's par for the course.",m:"It's normal for the situation."},
{s:"I'm in the same boat.",m:"I'm in the same difficult situation."},
{s:"Let's take the plunge.",m:"Let's commit to it."},
{s:"I'm at my wit's end.",m:"I don't know what to do anymore."},
{s:"Don't look a gift horse in the mouth.",m:"Don't criticize a gift."},
{s:"It's six of one, half a dozen of the other.",m:"Both options are the same."},
{s:"I'm rolling with the punches.",m:"I'm adapting to difficulties."},
{s:"Let's not beat a dead horse.",m:"Let's stop discussing something settled."},
{s:"I'm feeling antsy.",m:"I'm restless and nervous. (informal)"},
{s:"Don't cry over spilled milk.",m:"Don't regret what's done."},
{s:"It's the tip of the iceberg.",m:"It's only a small visible part."},
{s:"I'm on thin ice.",m:"I'm in a risky situation."},
{s:"I'm keeping my fingers crossed.",m:"I'm hoping for good luck."},
{s:"Don't put the cart before the horse.",m:"Do things in the right order."},
{s:"It's a double-edged sword.",m:"It has both advantages and disadvantages."},
{s:"I'm out of the loop.",m:"I don't have the latest information."},
{s:"Let's put our heads together.",m:"Let's solve it as a team."},
{s:"I'm running out of steam.",m:"I'm losing energy."},
{s:"Don't throw the baby out with the bathwater.",m:"Don't discard everything; keep the good parts."},
{s:"It's a shot in the dark.",m:"A guess with little chance of success."},
{s:"Let's separate the wheat from the chaff.",m:"Let's distinguish the good from the bad. (formal)"},
{s:"I'm up to my ears in work.",m:"I have too much work. (informal)"},
{s:"Don't burn your bridges.",m:"Don't destroy relationships you may need."},
{s:"It's neither here nor there.",m:"It doesn't matter."},
{s:"I'm flying by the seat of my pants.",m:"I'm improvising. (informal)"},
{s:"Let's nip it in the bud.",m:"Let's stop the problem early."},
{s:"I'm chomping at the bit.",m:"I'm eager to start."},
{s:"Don't get your hopes up.",m:"Don't expect too much."},
{s:"It's a red herring.",m:"A misleading clue."},
{s:"I'm treading water.",m:"I'm barely keeping up."},
{s:"Let's read between the lines.",m:"Let's understand the hidden meaning."},
{s:"I'm caught off guard.",m:"I'm surprised and unprepared."},
{s:"Don't shoot the messenger.",m:"Don't blame the bearer of bad news."},
{s:"It's a Pyrrhic victory.",m:"A win that costs too much. (advanced)"},
{s:"I'm walking a tightrope.",m:"I'm in a delicate situation."},
{s:"Let's table this discussion.",m:"Let's postpone this. (US usage)"},
{s:"I'm going down a rabbit hole.",m:"I'm getting lost in details."},
{s:"Don't move the goalposts.",m:"Don't change the rules unfairly."},
{s:"It's a perfect storm.",m:"Many bad things happening at once."},
{s:"I'm in hot water.",m:"I'm in trouble."},
{s:"Let's pick your brain.",m:"Let me ask your advice. (informal)"},
{s:"I'm drawing a blank.",m:"I can't remember."},
{s:"Let me play devil's advocate.",m:"Let me argue the opposite side to test the idea."},
{s:"It's a house of cards.",m:"Something fragile that could collapse."},
{s:"I'm clutching at straws.",m:"Trying anything in desperation."},
{s:"Let's not split hairs.",m:"Let's not argue over small details."},
{s:"I'm on autopilot.",m:"I'm doing it without thinking."},
{s:"Don't rest on your laurels.",m:"Don't stop trying after success."},
{s:"It's sink or swim.",m:"You must succeed or fail on your own."},
{s:"I'm spinning my wheels.",m:"I'm working hard with no progress."},
{s:"Let's strike while the iron is hot.",m:"Let's act now while we can."},
{s:"I'm taking it with a grain of salt.",m:"I'm not fully believing it."},
{s:"Don't throw good money after bad.",m:"Stop investing in failure."},
{s:"It's the calm before the storm.",m:"Quiet before trouble."},
{s:"I'm under the gun.",m:"I'm under pressure. (informal)"},
{s:"Let's weigh the pros and cons.",m:"Let's consider advantages and disadvantages."},
{s:"I'm winging it.",m:"I'm improvising. (informal)"},
{s:"Don't cross that bridge until you come to it.",m:"Don't worry about future problems yet."},
{s:"It's a tall order.",m:"It's a difficult request."},
{s:"I'm zoning out.",m:"I'm losing focus. (informal)"},
{s:"Let's agree to disagree.",m:"Let's accept our different opinions."},
{s:"I'm back to square one.",m:"I'm starting over."},
{s:"Don't open a can of worms.",m:"Don't start a complicated problem."},
{s:"It's a labor of love.",m:"Work done for passion, not money."},
{s:"I'm feeling the pinch.",m:"Money is tight. (informal)"},
{s:"Don't pass the buck.",m:"Don't shift blame to others."},
{s:"It's a marathon, not a sprint.",m:"Pace yourself for the long term."},
{s:"I'm in seventh heaven.",m:"I'm extremely happy."},
{s:"I'm on a roll.",m:"I'm having continuous success."},
{s:"Don't rain on my parade.",m:"Don't spoil my happiness."},
{s:"It's all Greek to me.",m:"I can't understand it."},
{s:"I'm out of my depth.",m:"This is beyond my ability."},
{s:"Let's get down to brass tacks.",m:"Let's discuss the essentials."},
{s:"I'm pulling an all-nighter.",m:"I'm working all night."},
{s:"Don't sweat the small stuff.",m:"Don't worry about minor things."},
{s:"It's a blessing and a curse.",m:"It has good and bad sides."},
{s:"I'm riding the wave.",m:"I'm benefiting from a good trend."},
{s:"Let's not make waves.",m:"Let's not cause trouble."},
{s:"I'm sitting pretty.",m:"I'm in a good situation. (informal)"},
{s:"Don't take it personally.",m:"It's not directed at you."},
{s:"It's a change of pace.",m:"Something different from usual."},
{s:"I'm turning over a new leaf.",m:"I'm starting fresh with better habits."},
{s:"Let's put it on the back burner.",m:"Let's postpone it."},
{s:"I'm up against the wall.",m:"I'm in a very difficult position."},
{s:"Don't waste your breath.",m:"Don't bother arguing."},
{s:"It's a done deal.",m:"It's decided and finished."},
{s:"I'm walking on air.",m:"I'm very happy."},
{s:"Let's shoot for the moon.",m:"Let's aim high."},
{s:"I'm at sixes and sevens.",m:"I'm confused and disorganized. (British)"},
{s:"Don't count on it.",m:"Don't rely on it happening."},
{s:"This hotel is a far cry from the last one.",m:"It's very different from something. (“a far cry from”)"},
{s:"I'm game.",m:"I'm willing to participate. (informal)"},
{s:"Let's take it one step at a time.",m:"Let's proceed gradually."},
{s:"I'm not cut out for this.",m:"I'm not suited for this."},
{s:"Don't get bent out of shape.",m:"Don't get upset. (informal)"},
{s:"It's a wild goose chase.",m:"A hopeless search."},
{s:"I'm on the same wavelength.",m:"We think alike."},
{s:"Let's keep our eyes on the prize.",m:"Let's stay focused on the goal."},
{s:"I'm out of pocket.",m:"I'm unavailable. (US informal)"},
{s:"Don't hold your breath.",m:"Don't expect it soon."},
{s:"It's a zero-sum game.",m:"One person's gain is another's loss."},
{s:"I'm phoning it in.",m:"I'm doing it with minimal effort. (informal)"},
{s:"Let's run it up the flagpole.",m:"Let's test the idea. (business, informal)"},
{s:"I'm in a rut.",m:"I'm stuck in a boring routine."},
{s:"Don't step on anyone's toes.",m:"Don't offend people while acting."},
{s:"It's a pipe dream.",m:"An unrealistic hope."},
{s:"I'm on pins and needles.",m:"I'm anxiously waiting."},
{s:"Let's move the needle.",m:"Let's make measurable progress. (business)"},
{s:"I'm out of sorts.",m:"I'm slightly unwell or irritable."},
{s:"Don't take no for an answer.",m:"Persist until you succeed."},
{s:"It's a tough sell.",m:"It's hard to convince people."},
{s:"I'm seeing the light at the end of the tunnel.",m:"The end of a difficulty is near."},
{s:"Let's not boil the ocean.",m:"Let's keep the scope reasonable. (business)"},
{s:"I'm drinking from a firehose.",m:"I'm overwhelmed with information. (informal)"},
{s:"Don't leave any stone unturned.",m:"Try every possible course of action."},
{s:"It's a game-changer.",m:"It changes everything dramatically."},
{s:"I'm firing on all cylinders.",m:"I'm working at full capacity."},
{s:"Let's peel back the onion.",m:"Let's examine layers of the problem. (business)"},
{s:"I'm navigating uncharted waters.",m:"I'm in an unfamiliar situation. (formal)"},
{s:"Don't let perfect be the enemy of good.",m:"Accept good enough; don't over-polish."},
{s:"It's a race against time.",m:"We must hurry."},
{s:"I'm building the plane while flying it.",m:"I'm figuring it out as I go. (informal)"},
{s:"Let's double-click on that.",m:"Let's examine that more closely. (business jargon)"},
{s:"I'm herding cats.",m:"I'm managing a chaotic group. (informal)"},
{s:"Don't bring a knife to a gunfight.",m:"Be properly prepared. (informal)"},
{s:"It's a level playing field.",m:"Everyone has a fair chance."},
{s:"I'm keeping my cards close to my chest.",m:"I'm hiding my plans."},
{s:"Let's raise the bar.",m:"Let's set higher standards."},
{s:"I'm punching above my weight.",m:"I'm competing beyond my level."},
{s:"Don't sell yourself short.",m:"Don't underestimate your value."},
{s:"It's a steep learning curve.",m:"It's difficult to learn quickly."},
{s:"I'm drowning in paperwork.",m:"I have too much paperwork. (informal)"},
{s:"Let's take a step back.",m:"Let's reconsider calmly."},
{s:"I'm weighing my options.",m:"I'm considering my choices. (formal)"},
{s:"Don't show your hand.",m:"Don't reveal your plans."},
{s:"It's an uphill battle.",m:"It's very difficult."},
{s:"I'm calling the shots.",m:"I'm making the decisions."},
{s:"Let's think on our feet.",m:"Let's react quickly and cleverly."},
{s:"I'm dropping the ball.",m:"I'm failing at my responsibilities."},
{s:"Don't go down with the ship.",m:"Don't fail with a failing project."},
{s:"Such is life.",m:"That's just how life is; accept it."},
{s:"I'm juggling too many balls.",m:"I have too many tasks at once."},
{s:"Let's not sugarcoat it.",m:"Let's be honest about the bad news."},
{s:"I'm running in circles.",m:"I'm busy but achieving nothing."},
{s:"Don't put me on the spot.",m:"Don't force me to answer immediately."},
{s:"It's a bitter pill to swallow.",m:"A hard truth to accept."},
{s:"I'm scraping the bottom of the barrel.",m:"I'm using the last or worst options."},
{s:"Let's get this show on the road.",m:"Let's begin."},
{s:"I'm bending over backwards.",m:"I'm trying very hard to help."},
{s:"Don't hold back.",m:"Say what you really think."},
{s:"It's a hard act to follow.",m:"It's difficult to do better than the previous person."},
{s:"I'm at the end of my rope.",m:"I can't take any more."},
{s:"Let's cross the Rubicon.",m:"Let's take an irreversible step. (advanced)"},
{s:"I'm fiddling while Rome burns.",m:"I'm ignoring a crisis. (advanced)"},
{s:"Don't meet trouble halfway.",m:"Don't worry prematurely."},
{s:"It's a Gordian knot.",m:"An extremely complex problem. (advanced)"},
{s:"I'm tilting at windmills.",m:"I'm fighting imaginary enemies. (advanced)"},
{s:"Let's not mince words.",m:"Let's speak plainly."},
{s:"I'm walking a fine line.",m:"I'm balancing carefully between two things."},
{s:"Don't upset the apple cart.",m:"Don't spoil the current situation."},
{s:"It's a shot across the bow.",m:"A warning of stronger action to come."},
{s:"I'm reading the tea leaves.",m:"I'm predicting from small signs."},
{s:"Let's put the pedal to the metal.",m:"Let's go faster / work harder. (informal)"},
{s:"I'm seeing stars.",m:"I'm dizzy. (informal)"},
{s:"People in glass houses shouldn't throw stones.",m:"Don't criticize others for faults you have."},
{s:"It's a tempest in a teapot.",m:"A big fuss over something small."},
{s:"I'm on the warpath.",m:"I'm angrily seeking confrontation. (informal)"},
{s:"Let's make hay while the sun shines.",m:"Take advantage of good conditions."},
{s:"I'm crying wolf.",m:"I'm raising false alarms."},
{s:"Don't change horses in midstream.",m:"Don't change plans midway."},
{s:"It's a wolf in sheep's clothing.",m:"Someone dangerous pretending to be harmless."},
{s:"Are you barking mad?",m:"Are you crazy? (British, playful)"},
{s:"Let's take the bull by the horns.",m:"Let's face the problem directly."},
{s:"I'm like a fish out of water.",m:"I feel out of place."},
{s:"Don't kill the goose that lays the golden eggs.",m:"Don't destroy your source of income."},
{s:"It's a white elephant.",m:"An expensive, useless possession."},
{s:"I'm as happy as a clam.",m:"I'm very happy. (informal)"},
{s:"Let's let the chips fall where they may.",m:"Let's accept whatever happens."},
{s:"I'm in the doghouse.",m:"Someone is angry with me. (informal)"},
{s:"Don't teach your grandmother to suck eggs.",m:"Don't give advice to an expert. (British, humorous)"},
{s:"It's raining cats and dogs.",m:"It's raining very heavily."},
{s:"I'm sick as a dog.",m:"I'm very ill. (informal)"},
{s:"Let's talk turkey.",m:"Let's discuss seriously. (US informal)"},
{s:"I'm chicken.",m:"I'm too scared. (informal)"},
{s:"Don't be a copycat.",m:"Don't imitate others. (playful)"},
{s:"It's a dog-eat-dog world.",m:"Ruthless competition."},
{s:"I'm the black sheep.",m:"I'm the odd one out in my family."},
{s:"Let's get off our high horse.",m:"Let's stop acting superior."},
{s:"I'm feeling sheepish.",m:"I'm embarrassed."},
{s:"Don't be such a scaredy-cat.",m:"Don't be so fearful. (playful)"},
{s:"It's a whale of a time.",m:"A wonderful time. (US informal)"},
{s:"I'm busy as a bee.",m:"I'm very busy."},
{s:"Let's make a beeline for the exit.",m:"Let's go straight to the exit."},
{s:"I'm as snug as a bug in a rug.",m:"I'm very comfortable. (playful)"},
{s:"Don't let the bedbugs bite.",m:"Sleep well. (playful goodnight)"},
{s:"It's a hive of activity.",m:"A very busy place."},
{s:"I'm a night owl.",m:"I'm active late at night."},
{s:"Let's not ruffle any feathers.",m:"Let's not upset anyone."},
{s:"I'm watching like a hawk.",m:"I'm observing very carefully."},
{s:"Don't be a sitting duck.",m:"Don't make yourself an easy target."},
{s:"It's a cat-and-mouse game.",m:"A pursuit where each tries to outsmart the other."},
{s:"I'm as free as a bird.",m:"I have no obligations."},
{s:"Let's feather our nest.",m:"Let's prepare for the future financially."},
{s:"I'm a lone wolf.",m:"I prefer to work alone."},
{s:"Don't be a guinea pig.",m:"Don't be a test subject."},
{s:"It's a paper tiger.",m:"Something threatening but actually weak."},
{s:"I'm as stubborn as a mule.",m:"I'm very stubborn."},
{s:"Let's separate the sheep from the goats.",m:"Let's distinguish good from bad."},
{s:"I'm feeling crabby.",m:"I'm irritable. (informal)"},
{s:"That sounds fishy.",m:"That sounds suspicious."},
{s:"It's a fish story.",m:"An exaggerated tale. (informal)"},
{s:"I'm in deep water.",m:"I'm in trouble."},
{s:"Let's dive in.",m:"Let's start enthusiastically."},
{s:"I'm swimming against the tide.",m:"I'm opposing the majority."},
{s:"Don't push the envelope.",m:"Don't go beyond limits."},
{s:"It's smooth sailing.",m:"Things are going easily."},
{s:"I'm up a creek without a paddle.",m:"I'm in trouble with no solution. (US informal)"},
{s:"Let's stay the course.",m:"Let's continue the plan."},
{s:"I'm bailing water.",m:"I'm dealing with urgent problems. (informal)"},
{s:"Don't jump ship.",m:"Don't abandon the team."},
{s:"It's full steam ahead.",m:"Proceed with full energy."},
{s:"I'm navigating choppy waters.",m:"I'm dealing with difficulties."},
{s:"Let's right the ship.",m:"Let's fix the problems. (business)"},
{s:"I'm dead in the water.",m:"My plan has failed completely. (informal)"},
{s:"Don't look back.",m:"Keep moving forward; don't regret."},
{s:"It's ancient history.",m:"It's long past and irrelevant."},
{s:"I'm going with the flow.",m:"I'm adapting to the situation."},
{s:"Let's make waves.",m:"Let's cause exciting change. (positive)"},
{s:"I'm testing the waters.",m:"I'm trying something cautiously."},
{s:"Don't muddy the waters.",m:"Don't make things confusing."},
{s:"Still waters run deep.",m:"Quiet people are often deep thinkers."},
{s:"I'm fishing for compliments.",m:"I'm trying to get praise. (informal)"},
{s:"Let's cast a wide net.",m:"Let's consider many options."},
{s:"I'm off the hook.",m:"I'm free from obligation. (informal)"},
{s:"Don't take the bait.",m:"Don't be provoked."},
{s:"It's a big fish in a small pond.",m:"An important person in a small group."},
{s:"I'm a small fish in a big pond.",m:"I'm unimportant in a large group."},
{s:"Let's not open Pandora's box.",m:"Let's not release new problems. (advanced)"},
{s:"I'm between Scylla and Charybdis.",m:"I'm between two dangers. (advanced)"},
{s:"He met his Waterloo.",m:"He suffered a final defeat. (advanced)"},
{s:"It's a Sisyphean task.",m:"An endless, futile task. (advanced)"},
{s:"I'm chasing a chimera.",m:"I'm pursuing something impossible. (advanced)"},
{s:"Let's not cross swords.",m:"Let's not argue."},
{s:"Don't be a Cassandra.",m:"Don't only predict bad outcomes. (advanced)"},
{s:"It's a Herculean effort.",m:"It requires enormous strength or effort. (advanced)"},
{s:"I'm fighting a losing battle.",m:"I'm trying something hopeless."},
{s:"Let's not build castles in the air.",m:"Let's not daydream unrealistically."},
{s:"I'm counting my blessings.",m:"I'm appreciating what I have."},
{s:"Don't spit into the wind.",m:"Don't do something self-defeating."},
{s:"It's a fool's errand.",m:"A hopeless undertaking."},
{s:"I'm at a turning point.",m:"My life is about to change."},
{s:"Let's turn the page.",m:"Let's move on to a new chapter."},
{s:"I'm starting with a clean slate.",m:"I'm starting fresh."},
{s:"Don't dwell on the past.",m:"Don't keep thinking about the past."},
{s:"It's time to face the music.",m:"It's time to accept consequences."},
{s:"I'm seizing the day.",m:"I'm making the most of today. (carpe diem)"},
{s:"Let's make every day count.",m:"Let's use each day well."}
];
(function(){
  var wOff = 0, sOff = 0;
  function dayOfYear(d){var s=new Date(d.getFullYear(),0,0);return Math.floor((d-s)/864e5);}
  function idx(off,n){var i=(dayOfYear(new Date())+off)%n;return i<0?i+n:i;}
  function fmtDate(off){var d=new Date();d.setDate(d.getDate()+off);
    return d.toLocaleDateString('en-US',{month:'short',day:'numeric'});}
  function speak(t){try{if('speechSynthesis' in window){speechSynthesis.cancel();
    speechSynthesis.speak(new SpeechSynthesisUtterance(t));}}catch(e){}}
  function render(){
    var w=WORDS[idx(wOff,WORDS.length)];
    document.getElementById('dw-word').textContent=w.w;
    document.getElementById('dw-meta').textContent=w.pos+'  '+w.ipa;
    document.getElementById('dw-def').textContent=w.def;
    document.getElementById('dw-ex').textContent='“'+w.ex+'”';
    document.getElementById('dw-date').textContent=fmtDate(wOff);
    var s=SENTENCES[idx(sOff,SENTENCES.length)];
    document.getElementById('ds-text').textContent='“'+s.s+'”';
    document.getElementById('ds-meaning').textContent=s.m;
    document.getElementById('ds-date').textContent=fmtDate(sOff);
  }
  document.getElementById('dw-prev').addEventListener('click',function(){wOff--;render();});
  document.getElementById('dw-next').addEventListener('click',function(){wOff++;render();});
  document.getElementById('ds-prev').addEventListener('click',function(){sOff--;render();});
  document.getElementById('ds-next').addEventListener('click',function(){sOff++;render();});
  document.getElementById('dw-speak').addEventListener('click',function(){
    var w=WORDS[idx(wOff,WORDS.length)];speak(w.w+'. '+w.def+' '+w.ex);});
  document.getElementById('ds-speak').addEventListener('click',function(){
    var s=SENTENCES[idx(sOff,SENTENCES.length)];speak(s.s);});
  render();
})();
